/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/linker/ng_module_factory';
import * as import1 from './app.module';
import * as import2 from '@angular/common/src/common_module';
import * as import3 from '@angular/core/src/application_module';
import * as import4 from '@angular/platform-browser/src/browser';
import * as import5 from '@angular/forms/src/directives';
import * as import6 from '@angular/forms/src/form_providers';
import * as import7 from '@angular/router/src/router_module';
import * as import8 from './app-routing.module';
import * as import9 from '@angular/common/src/localization';
import * as import10 from '@angular/core/src/application_init';
import * as import11 from '@angular/core/src/testability/testability';
import * as import12 from '@angular/core/src/application_ref';
import * as import13 from '@angular/core/src/linker/compiler';
import * as import14 from '@angular/platform-browser/src/dom/events/hammer_gestures';
import * as import15 from '@angular/platform-browser/src/dom/events/event_manager';
import * as import16 from '@angular/platform-browser/src/dom/shared_styles_host';
import * as import17 from '@angular/platform-browser/src/dom/dom_renderer';
import * as import18 from '@angular/platform-browser/src/security/dom_sanitization_service';
import * as import19 from '@angular/core/src/animation/animation_queue';
import * as import20 from '@angular/core/src/linker/view_utils';
import * as import21 from '@angular/platform-browser/src/browser/title';
import * as import22 from '@angular/forms/src/directives/radio_control_value_accessor';
import * as import23 from '@angular/common/src/location/location';
import * as import24 from '@angular/router/src/url_tree';
import * as import25 from '@angular/router/src/router_outlet_map';
import * as import26 from '@angular/core/src/linker/system_js_ng_module_factory_loader';
import * as import27 from '@angular/router/src/router_preloader';
import * as import28 from './hero.service';
import * as import29 from './team.service';
import * as import30 from '@angular/core/src/di/injector';
import * as import31 from './about.component.ngfactory';
import * as import32 from './buyahome.component.ngfactory';
import * as import33 from './contactus.component.ngfactory';
import * as import34 from './dashboard.component.ngfactory';
import * as import35 from './hero-detail.component.ngfactory';
import * as import36 from './f-a-q.component.ngfactory';
import * as import37 from './heros.component.ngfactory';
import * as import38 from './home.component.ngfactory';
import * as import39 from './investors.component.ngfactory';
import * as import40 from './privacy.component.ngfactory';
import * as import41 from './sellyourhome.component.ngfactory';
import * as import42 from './terms.component.ngfactory';
import * as import43 from './wholesale.component.ngfactory';
import * as import44 from './app.component.ngfactory';
import * as import45 from '@angular/core/src/i18n/tokens';
import * as import46 from '@angular/core/src/application_tokens';
import * as import47 from '@angular/platform-browser/src/dom/events/dom_events';
import * as import48 from '@angular/platform-browser/src/dom/events/key_events';
import * as import49 from '@angular/core/src/zone/ng_zone';
import * as import50 from '@angular/platform-browser/src/dom/debug/ng_probe';
import * as import51 from '@angular/common/src/location/platform_location';
import * as import52 from '@angular/common/src/location/location_strategy';
import * as import53 from './about.component';
import * as import54 from './buyahome.component';
import * as import55 from './contactus.component';
import * as import56 from './dashboard.component';
import * as import57 from './hero-detail.component';
import * as import58 from './f-a-q.component';
import * as import59 from './heros.component';
import * as import60 from './home.component';
import * as import61 from './investors.component';
import * as import62 from './privacy.component';
import * as import63 from './sellyourhome.component';
import * as import64 from './terms.component';
import * as import65 from './wholesale.component';
import * as import66 from '@angular/router/src/url_handling_strategy';
import * as import67 from '@angular/router/src/route_reuse_strategy';
import * as import68 from '@angular/router/src/router';
import * as import69 from '@angular/core/src/console';
import * as import70 from '@angular/core/src/error_handler';
import * as import71 from '@angular/platform-browser/src/dom/dom_tokens';
import * as import72 from '@angular/platform-browser/src/dom/animation_driver';
import * as import73 from '@angular/core/src/render/api';
import * as import74 from '@angular/core/src/security';
import * as import75 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import76 from '@angular/core/src/change_detection/differs/keyvalue_differs';
import * as import77 from '@angular/core/src/linker/ng_module_factory_loader';
import * as import78 from '@angular/router/src/router_config_loader';
import * as import79 from '@angular/router/src/router_state';
class AppModuleInjector extends import0.NgModuleInjector<import1.AppModule> {
  _CommonModule_0:import2.CommonModule;
  _ApplicationModule_1:import3.ApplicationModule;
  _BrowserModule_2:import4.BrowserModule;
  _InternalFormsSharedModule_3:import5.InternalFormsSharedModule;
  _FormsModule_4:import6.FormsModule;
  _ROUTER_FORROOT_GUARD_5:any;
  _RouterModule_6:import7.RouterModule;
  _AppRoutingModule_7:import8.AppRoutingModule;
  _AppModule_8:import1.AppModule;
  __LOCALE_ID_9:any;
  __NgLocalization_10:import9.NgLocaleLocalization;
  _ErrorHandler_11:any;
  _ApplicationInitStatus_12:import10.ApplicationInitStatus;
  _Testability_13:import11.Testability;
  _ApplicationRef__14:import12.ApplicationRef_;
  __ApplicationRef_15:any;
  __Compiler_16:import13.Compiler;
  __APP_ID_17:any;
  __DOCUMENT_18:any;
  __HAMMER_GESTURE_CONFIG_19:import14.HammerGestureConfig;
  __EVENT_MANAGER_PLUGINS_20:any[];
  __EventManager_21:import15.EventManager;
  _DomSharedStylesHost_22:import16.DomSharedStylesHost;
  __AnimationDriver_23:any;
  __DomRootRenderer_24:import17.DomRootRenderer_;
  __NgProbeToken_25:any[];
  __RootRenderer_26:any;
  __DomSanitizer_27:import18.DomSanitizerImpl;
  __Sanitizer_28:any;
  __AnimationQueue_29:import19.AnimationQueue;
  __ViewUtils_30:import20.ViewUtils;
  __IterableDiffers_31:any;
  __KeyValueDiffers_32:any;
  __SharedStylesHost_33:any;
  __Title_34:import21.Title;
  __RadioControlRegistry_35:import22.RadioControlRegistry;
  __ROUTER_CONFIGURATION_36:any;
  __LocationStrategy_37:any;
  __Location_38:import23.Location;
  __UrlSerializer_39:import24.DefaultUrlSerializer;
  __RouterOutletMap_40:import25.RouterOutletMap;
  __NgModuleFactoryLoader_41:import26.SystemJsNgModuleLoader;
  __ROUTES_42:any[];
  __Router_43:any;
  __ActivatedRoute_44:any;
  _NoPreloading_45:import27.NoPreloading;
  _PreloadingStrategy_46:any;
  _RouterPreloader_47:import27.RouterPreloader;
  __PreloadAllModules_48:import27.PreloadAllModules;
  __ROUTER_INITIALIZER_49:any;
  __APP_BOOTSTRAP_LISTENER_50:any[];
  __HeroService_51:import28.HeroService;
  __TeamService_52:import29.TeamService;
  constructor(parent:import30.Injector) {
    super(parent,[
      import31.AboutComponentNgFactory,
      import32.BuyAHomeComponentNgFactory,
      import33.ContactUsComponentNgFactory,
      import34.DashboardComponentNgFactory,
      import35.HeroDetailComponentNgFactory,
      import36.FAQComponentNgFactory,
      import37.HerosComponentNgFactory,
      import38.HomeComponentNgFactory,
      import39.InvestorsComponentNgFactory,
      import40.PrivacyComponentNgFactory,
      import41.SellYourHomeComponentNgFactory,
      import42.TermsComponentNgFactory,
      import43.WholesaleComponentNgFactory,
      import44.AppComponentNgFactory
    ]
    ,[import44.AppComponentNgFactory]);
  }
  get _LOCALE_ID_9():any {
    if ((this.__LOCALE_ID_9 == null)) { (this.__LOCALE_ID_9 = import3._localeFactory(this.parent.get(import45.LOCALE_ID,(null as any)))); }
    return this.__LOCALE_ID_9;
  }
  get _NgLocalization_10():import9.NgLocaleLocalization {
    if ((this.__NgLocalization_10 == null)) { (this.__NgLocalization_10 = new import9.NgLocaleLocalization(this._LOCALE_ID_9)); }
    return this.__NgLocalization_10;
  }
  get _ApplicationRef_15():any {
    if ((this.__ApplicationRef_15 == null)) { (this.__ApplicationRef_15 = this._ApplicationRef__14); }
    return this.__ApplicationRef_15;
  }
  get _Compiler_16():import13.Compiler {
    if ((this.__Compiler_16 == null)) { (this.__Compiler_16 = new import13.Compiler()); }
    return this.__Compiler_16;
  }
  get _APP_ID_17():any {
    if ((this.__APP_ID_17 == null)) { (this.__APP_ID_17 = import46._appIdRandomProviderFactory()); }
    return this.__APP_ID_17;
  }
  get _DOCUMENT_18():any {
    if ((this.__DOCUMENT_18 == null)) { (this.__DOCUMENT_18 = import4._document()); }
    return this.__DOCUMENT_18;
  }
  get _HAMMER_GESTURE_CONFIG_19():import14.HammerGestureConfig {
    if ((this.__HAMMER_GESTURE_CONFIG_19 == null)) { (this.__HAMMER_GESTURE_CONFIG_19 = new import14.HammerGestureConfig()); }
    return this.__HAMMER_GESTURE_CONFIG_19;
  }
  get _EVENT_MANAGER_PLUGINS_20():any[] {
    if ((this.__EVENT_MANAGER_PLUGINS_20 == null)) { (this.__EVENT_MANAGER_PLUGINS_20 = [
      new import47.DomEventsPlugin(),
      new import48.KeyEventsPlugin(),
      new import14.HammerGesturesPlugin(this._HAMMER_GESTURE_CONFIG_19)
    ]
    ); }
    return this.__EVENT_MANAGER_PLUGINS_20;
  }
  get _EventManager_21():import15.EventManager {
    if ((this.__EventManager_21 == null)) { (this.__EventManager_21 = new import15.EventManager(this._EVENT_MANAGER_PLUGINS_20,this.parent.get(import49.NgZone))); }
    return this.__EventManager_21;
  }
  get _AnimationDriver_23():any {
    if ((this.__AnimationDriver_23 == null)) { (this.__AnimationDriver_23 = import4._resolveDefaultAnimationDriver()); }
    return this.__AnimationDriver_23;
  }
  get _DomRootRenderer_24():import17.DomRootRenderer_ {
    if ((this.__DomRootRenderer_24 == null)) { (this.__DomRootRenderer_24 = new import17.DomRootRenderer_(this._DOCUMENT_18,this._EventManager_21,this._DomSharedStylesHost_22,this._AnimationDriver_23,this._APP_ID_17)); }
    return this.__DomRootRenderer_24;
  }
  get _NgProbeToken_25():any[] {
    if ((this.__NgProbeToken_25 == null)) { (this.__NgProbeToken_25 = [import7.routerNgProbeToken()]); }
    return this.__NgProbeToken_25;
  }
  get _RootRenderer_26():any {
    if ((this.__RootRenderer_26 == null)) { (this.__RootRenderer_26 = import50._createConditionalRootRenderer(this._DomRootRenderer_24,this.parent.get(import50.NgProbeToken,(null as any)),this._NgProbeToken_25)); }
    return this.__RootRenderer_26;
  }
  get _DomSanitizer_27():import18.DomSanitizerImpl {
    if ((this.__DomSanitizer_27 == null)) { (this.__DomSanitizer_27 = new import18.DomSanitizerImpl()); }
    return this.__DomSanitizer_27;
  }
  get _Sanitizer_28():any {
    if ((this.__Sanitizer_28 == null)) { (this.__Sanitizer_28 = this._DomSanitizer_27); }
    return this.__Sanitizer_28;
  }
  get _AnimationQueue_29():import19.AnimationQueue {
    if ((this.__AnimationQueue_29 == null)) { (this.__AnimationQueue_29 = new import19.AnimationQueue(this.parent.get(import49.NgZone))); }
    return this.__AnimationQueue_29;
  }
  get _ViewUtils_30():import20.ViewUtils {
    if ((this.__ViewUtils_30 == null)) { (this.__ViewUtils_30 = new import20.ViewUtils(this._RootRenderer_26,this._Sanitizer_28,this._AnimationQueue_29)); }
    return this.__ViewUtils_30;
  }
  get _IterableDiffers_31():any {
    if ((this.__IterableDiffers_31 == null)) { (this.__IterableDiffers_31 = import3._iterableDiffersFactory()); }
    return this.__IterableDiffers_31;
  }
  get _KeyValueDiffers_32():any {
    if ((this.__KeyValueDiffers_32 == null)) { (this.__KeyValueDiffers_32 = import3._keyValueDiffersFactory()); }
    return this.__KeyValueDiffers_32;
  }
  get _SharedStylesHost_33():any {
    if ((this.__SharedStylesHost_33 == null)) { (this.__SharedStylesHost_33 = this._DomSharedStylesHost_22); }
    return this.__SharedStylesHost_33;
  }
  get _Title_34():import21.Title {
    if ((this.__Title_34 == null)) { (this.__Title_34 = new import21.Title()); }
    return this.__Title_34;
  }
  get _RadioControlRegistry_35():import22.RadioControlRegistry {
    if ((this.__RadioControlRegistry_35 == null)) { (this.__RadioControlRegistry_35 = new import22.RadioControlRegistry()); }
    return this.__RadioControlRegistry_35;
  }
  get _ROUTER_CONFIGURATION_36():any {
    if ((this.__ROUTER_CONFIGURATION_36 == null)) { (this.__ROUTER_CONFIGURATION_36 = {}); }
    return this.__ROUTER_CONFIGURATION_36;
  }
  get _LocationStrategy_37():any {
    if ((this.__LocationStrategy_37 == null)) { (this.__LocationStrategy_37 = import7.provideLocationStrategy(this.parent.get(import51.PlatformLocation),this.parent.get(import52.APP_BASE_HREF,(null as any)),this._ROUTER_CONFIGURATION_36)); }
    return this.__LocationStrategy_37;
  }
  get _Location_38():import23.Location {
    if ((this.__Location_38 == null)) { (this.__Location_38 = new import23.Location(this._LocationStrategy_37)); }
    return this.__Location_38;
  }
  get _UrlSerializer_39():import24.DefaultUrlSerializer {
    if ((this.__UrlSerializer_39 == null)) { (this.__UrlSerializer_39 = new import24.DefaultUrlSerializer()); }
    return this.__UrlSerializer_39;
  }
  get _RouterOutletMap_40():import25.RouterOutletMap {
    if ((this.__RouterOutletMap_40 == null)) { (this.__RouterOutletMap_40 = new import25.RouterOutletMap()); }
    return this.__RouterOutletMap_40;
  }
  get _NgModuleFactoryLoader_41():import26.SystemJsNgModuleLoader {
    if ((this.__NgModuleFactoryLoader_41 == null)) { (this.__NgModuleFactoryLoader_41 = new import26.SystemJsNgModuleLoader(this._Compiler_16,this.parent.get(import26.SystemJsNgModuleLoaderConfig,(null as any)))); }
    return this.__NgModuleFactoryLoader_41;
  }
  get _ROUTES_42():any[] {
      if ((this.__ROUTES_42 == null)) { (this.__ROUTES_42 = [[
        {
          path: '',
          redirectTo: '/home',
          pathMatch: 'full'
        }
        ,
        {
          path: 'about',
          component: import53.AboutComponent
        }
        ,
        {
          path: 'buy',
          component: import54.BuyAHomeComponent
        }
        ,
        {
          path: 'contactus',
          component: import55.ContactUsComponent
        }
        ,
        {
          path: 'dashboard',
          component: import56.DashboardComponent
        }
        ,
        {
          path: 'detail/:id',
          component: import57.HeroDetailComponent
        }
        ,
        {
          path: 'faq',
          component: import58.FAQComponent
        }
        ,
        {
          path: 'heros',
          component: import59.HerosComponent
        }
        ,
        {
          path: 'home',
          component: import60.HomeComponent
        }
        ,
        {
          path: 'investors',
          component: import61.InvestorsComponent
        }
        ,
        {
          path: 'privacy',
          component: import62.PrivacyComponent
        }
        ,
        {
          path: 'sell',
          component: import63.SellYourHomeComponent
        }
        ,
        {
          path: 'terms',
          component: import64.TermsComponent
        }
        ,
        {
          path: 'wholesale',
          component: import65.WholesaleComponent
        }

      ]
    ]); }
    return this.__ROUTES_42;
  }
  get _Router_43():any {
    if ((this.__Router_43 == null)) { (this.__Router_43 = import7.setupRouter(this._ApplicationRef_15,this._UrlSerializer_39,this._RouterOutletMap_40,this._Location_38,this,this._NgModuleFactoryLoader_41,this._Compiler_16,this._ROUTES_42,this._ROUTER_CONFIGURATION_36,this.parent.get(import66.UrlHandlingStrategy,(null as any)),this.parent.get(import67.RouteReuseStrategy,(null as any)))); }
    return this.__Router_43;
  }
  get _ActivatedRoute_44():any {
    if ((this.__ActivatedRoute_44 == null)) { (this.__ActivatedRoute_44 = import7.rootRoute(this._Router_43)); }
    return this.__ActivatedRoute_44;
  }
  get _PreloadAllModules_48():import27.PreloadAllModules {
    if ((this.__PreloadAllModules_48 == null)) { (this.__PreloadAllModules_48 = new import27.PreloadAllModules()); }
    return this.__PreloadAllModules_48;
  }
  get _ROUTER_INITIALIZER_49():any {
    if ((this.__ROUTER_INITIALIZER_49 == null)) { (this.__ROUTER_INITIALIZER_49 = import7.initialRouterNavigation(this._Router_43,this._ApplicationRef_15,this._RouterPreloader_47,this._ROUTER_CONFIGURATION_36)); }
    return this.__ROUTER_INITIALIZER_49;
  }
  get _APP_BOOTSTRAP_LISTENER_50():any[] {
    if ((this.__APP_BOOTSTRAP_LISTENER_50 == null)) { (this.__APP_BOOTSTRAP_LISTENER_50 = [this._ROUTER_INITIALIZER_49]); }
    return this.__APP_BOOTSTRAP_LISTENER_50;
  }
  get _HeroService_51():import28.HeroService {
    if ((this.__HeroService_51 == null)) { (this.__HeroService_51 = new import28.HeroService()); }
    return this.__HeroService_51;
  }
  get _TeamService_52():import29.TeamService {
    if ((this.__TeamService_52 == null)) { (this.__TeamService_52 = new import29.TeamService()); }
    return this.__TeamService_52;
  }
  createInternal():import1.AppModule {
    this._CommonModule_0 = new import2.CommonModule();
    this._ApplicationModule_1 = new import3.ApplicationModule();
    this._BrowserModule_2 = new import4.BrowserModule(this.parent.get(import4.BrowserModule,(null as any)));
    this._InternalFormsSharedModule_3 = new import5.InternalFormsSharedModule();
    this._FormsModule_4 = new import6.FormsModule();
    this._ROUTER_FORROOT_GUARD_5 = import7.provideForRootGuard(this.parent.get(import68.Router,(null as any)));
    this._RouterModule_6 = new import7.RouterModule(this._ROUTER_FORROOT_GUARD_5);
    this._AppRoutingModule_7 = new import8.AppRoutingModule();
    this._AppModule_8 = new import1.AppModule();
    this._ErrorHandler_11 = import4.errorHandler();
    this._ApplicationInitStatus_12 = new import10.ApplicationInitStatus(this.parent.get(import10.APP_INITIALIZER,(null as any)));
    this._Testability_13 = new import11.Testability(this.parent.get(import49.NgZone));
    this._ApplicationRef__14 = new import12.ApplicationRef_(this.parent.get(import49.NgZone),this.parent.get(import69.Console),this,this._ErrorHandler_11,this,this._ApplicationInitStatus_12,this.parent.get(import11.TestabilityRegistry,(null as any)),this._Testability_13);
    this._DomSharedStylesHost_22 = new import16.DomSharedStylesHost(this._DOCUMENT_18);
    this._NoPreloading_45 = new import27.NoPreloading();
    this._PreloadingStrategy_46 = this._NoPreloading_45;
    this._RouterPreloader_47 = new import27.RouterPreloader(this._Router_43,this._NgModuleFactoryLoader_41,this._Compiler_16,this,this._PreloadingStrategy_46);
    return this._AppModule_8;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.CommonModule)) { return this._CommonModule_0; }
    if ((token === import3.ApplicationModule)) { return this._ApplicationModule_1; }
    if ((token === import4.BrowserModule)) { return this._BrowserModule_2; }
    if ((token === import5.InternalFormsSharedModule)) { return this._InternalFormsSharedModule_3; }
    if ((token === import6.FormsModule)) { return this._FormsModule_4; }
    if ((token === import7.ROUTER_FORROOT_GUARD)) { return this._ROUTER_FORROOT_GUARD_5; }
    if ((token === import7.RouterModule)) { return this._RouterModule_6; }
    if ((token === import8.AppRoutingModule)) { return this._AppRoutingModule_7; }
    if ((token === import1.AppModule)) { return this._AppModule_8; }
    if ((token === import45.LOCALE_ID)) { return this._LOCALE_ID_9; }
    if ((token === import9.NgLocalization)) { return this._NgLocalization_10; }
    if ((token === import70.ErrorHandler)) { return this._ErrorHandler_11; }
    if ((token === import10.ApplicationInitStatus)) { return this._ApplicationInitStatus_12; }
    if ((token === import11.Testability)) { return this._Testability_13; }
    if ((token === import12.ApplicationRef_)) { return this._ApplicationRef__14; }
    if ((token === import12.ApplicationRef)) { return this._ApplicationRef_15; }
    if ((token === import13.Compiler)) { return this._Compiler_16; }
    if ((token === import46.APP_ID)) { return this._APP_ID_17; }
    if ((token === import71.DOCUMENT)) { return this._DOCUMENT_18; }
    if ((token === import14.HAMMER_GESTURE_CONFIG)) { return this._HAMMER_GESTURE_CONFIG_19; }
    if ((token === import15.EVENT_MANAGER_PLUGINS)) { return this._EVENT_MANAGER_PLUGINS_20; }
    if ((token === import15.EventManager)) { return this._EventManager_21; }
    if ((token === import16.DomSharedStylesHost)) { return this._DomSharedStylesHost_22; }
    if ((token === import72.AnimationDriver)) { return this._AnimationDriver_23; }
    if ((token === import17.DomRootRenderer)) { return this._DomRootRenderer_24; }
    if ((token === import12.NgProbeToken)) { return this._NgProbeToken_25; }
    if ((token === import73.RootRenderer)) { return this._RootRenderer_26; }
    if ((token === import18.DomSanitizer)) { return this._DomSanitizer_27; }
    if ((token === import74.Sanitizer)) { return this._Sanitizer_28; }
    if ((token === import19.AnimationQueue)) { return this._AnimationQueue_29; }
    if ((token === import20.ViewUtils)) { return this._ViewUtils_30; }
    if ((token === import75.IterableDiffers)) { return this._IterableDiffers_31; }
    if ((token === import76.KeyValueDiffers)) { return this._KeyValueDiffers_32; }
    if ((token === import16.SharedStylesHost)) { return this._SharedStylesHost_33; }
    if ((token === import21.Title)) { return this._Title_34; }
    if ((token === import22.RadioControlRegistry)) { return this._RadioControlRegistry_35; }
    if ((token === import7.ROUTER_CONFIGURATION)) { return this._ROUTER_CONFIGURATION_36; }
    if ((token === import52.LocationStrategy)) { return this._LocationStrategy_37; }
    if ((token === import23.Location)) { return this._Location_38; }
    if ((token === import24.UrlSerializer)) { return this._UrlSerializer_39; }
    if ((token === import25.RouterOutletMap)) { return this._RouterOutletMap_40; }
    if ((token === import77.NgModuleFactoryLoader)) { return this._NgModuleFactoryLoader_41; }
    if ((token === import78.ROUTES)) { return this._ROUTES_42; }
    if ((token === import68.Router)) { return this._Router_43; }
    if ((token === import79.ActivatedRoute)) { return this._ActivatedRoute_44; }
    if ((token === import27.NoPreloading)) { return this._NoPreloading_45; }
    if ((token === import27.PreloadingStrategy)) { return this._PreloadingStrategy_46; }
    if ((token === import27.RouterPreloader)) { return this._RouterPreloader_47; }
    if ((token === import27.PreloadAllModules)) { return this._PreloadAllModules_48; }
    if ((token === import7.ROUTER_INITIALIZER)) { return this._ROUTER_INITIALIZER_49; }
    if ((token === import46.APP_BOOTSTRAP_LISTENER)) { return this._APP_BOOTSTRAP_LISTENER_50; }
    if ((token === import28.HeroService)) { return this._HeroService_51; }
    if ((token === import29.TeamService)) { return this._TeamService_52; }
    return notFoundResult;
  }
  destroyInternal():void {
    this._ApplicationRef__14.ngOnDestroy();
    this._DomSharedStylesHost_22.ngOnDestroy();
    this._RouterPreloader_47.ngOnDestroy();
  }
}
export const AppModuleNgFactory:import0.NgModuleFactory<import1.AppModule> = new import0.NgModuleFactory(AppModuleInjector,import1.AppModule);