/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

export const styles:any[] = ['h1[_ngcontent-%COMP%] {\r\n  font-size: 1.2em;\r\n  color: #999;\r\n  margin-bottom: 0;\r\n}\r\n\r\nh2[_ngcontent-%COMP%] {\r\n  font-size: 2em;\r\n  margin-top: 0;\r\n  padding-top: 0;\r\n}\r\n\r\nnav[_ngcontent-%COMP%]   a[_ngcontent-%COMP%] {\r\n  padding: 5px 10px;\r\n  text-decoration: none;\r\n  margin-top: 10px;\r\n  display: inline-block;\r\n  background-color: #eee;\r\n  border-radius: 4px;\r\n}\r\n\r\n  nav[_ngcontent-%COMP%]   a[_ngcontent-%COMP%]:visited, a[_ngcontent-%COMP%]:link {\r\n    color: #607D8B;\r\n  }\r\n\r\n  nav[_ngcontent-%COMP%]   a[_ngcontent-%COMP%]:hover {\r\n    color: #039be5;\r\n    background-color: #CFD8DC;\r\n  }\r\n\r\n  nav[_ngcontent-%COMP%]   a.active[_ngcontent-%COMP%] {\r\n    color: #039be5;\r\n  }'];