/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

export const styles:any[] = ['a[_ngcontent-%COMP%]:link, a[_ngcontent-%COMP%]:visited, a[_ngcontent-%COMP%] {\r\n  color:white;\r\n}\r\n\r\n.footer[_ngcontent-%COMP%] {\r\n  \r\n  background-color: #000;\r\n  color: white;\r\n}\r\n\r\na[_ngcontent-%COMP%]:hover{\r\n  color:white;\r\n  font-weight:bold;\r\n  cursor:pointer;\r\n}'];