/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from './header.component';
import * as import1 from '@angular/core/src/change_detection/change_detection_util';
import * as import2 from '@angular/core/src/linker/view';
import * as import3 from '@angular/core/src/linker/view_utils';
import * as import4 from '@angular/core/src/render/api';
import * as import5 from '@angular/core/src/metadata/view';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/constants';
import * as import8 from '@angular/core/src/linker/component_factory';
import * as import9 from './header.component.css.shim.ngstyle';
import * as import10 from '../node_modules/@angular/router/src/directives/router_link.ngfactory';
import * as import11 from '../node_modules/@angular/router/src/directives/router_link_active.ngfactory';
import * as import12 from '@angular/core/src/linker/query_list';
import * as import13 from '@angular/router/src/router';
import * as import14 from '@angular/router/src/router_state';
import * as import15 from '@angular/common/src/location/location_strategy';
import * as import16 from '@angular/core/src/linker/element_ref';
import * as import17 from '@angular/router/src/directives/router_link';
import * as import18 from '@angular/router/src/directives/router_link_active';
export class Wrapper_HeaderComponent {
  /*private*/ _eventHandler:Function;
  context:import0.HeaderComponent;
  /*private*/ _changed:boolean;
  /*private*/ _expr_0:any;
  constructor() {
    this._changed = false;
    this.context = new import0.HeaderComponent();
    this._expr_0 = import1.UNINITIALIZED;
  }
  ngOnDetach(view:import2.AppView<any>,componentView:import2.AppView<any>,el:any):void {
  }
  ngOnDestroy():void {
  }
  check_title(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_0,currValue))) {
      this._changed = true;
      this.context.title = currValue;
      this._expr_0 = currValue;
    }
  }
  ngDoCheck(view:import2.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this._changed;
    this._changed = false;
    if (!throwOnChange) { if ((view.numberOfChecks === 0)) { this.context.ngOnInit(); } }
    return changed;
  }
  checkHost(view:import2.AppView<any>,componentView:import2.AppView<any>,el:any,throwOnChange:boolean):void {
  }
  handleEvent(eventName:string,$event:any):boolean {
    var result:boolean = true;
    return result;
  }
  subscribe(view:import2.AppView<any>,_eventHandler:any):void {
    this._eventHandler = _eventHandler;
  }
}
var renderType_HeaderComponent_Host:import4.RenderComponentType = import3.createRenderComponentType('',0,import5.ViewEncapsulation.None,([] as any[]),{});
class View_HeaderComponent_Host0 extends import2.AppView<any> {
  _el_0:any;
  compView_0:import2.AppView<import0.HeaderComponent>;
  _HeaderComponent_0_3:Wrapper_HeaderComponent;
  constructor(viewUtils:import3.ViewUtils,parentView:import2.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_HeaderComponent_Host0,renderType_HeaderComponent_Host,import6.ViewType.HOST,viewUtils,parentView,parentIndex,parentElement,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import8.ComponentRef<any> {
    this._el_0 = import3.selectOrCreateRenderHostElement(this.renderer,'header',import3.EMPTY_INLINE_ARRAY,rootSelector,(null as any));
    this.compView_0 = new View_HeaderComponent0(this.viewUtils,this,0,this._el_0);
    this._HeaderComponent_0_3 = new Wrapper_HeaderComponent();
    this.compView_0.create(this._HeaderComponent_0_3.context);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return new import8.ComponentRef_<any>(0,this,this._el_0,this._HeaderComponent_0_3.context);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.HeaderComponent) && (0 === requestNodeIndex))) { return this._HeaderComponent_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._HeaderComponent_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this.compView_0.internalDetectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
export const HeaderComponentNgFactory:import8.ComponentFactory<import0.HeaderComponent> = new import8.ComponentFactory<import0.HeaderComponent>('header',View_HeaderComponent_Host0,import0.HeaderComponent);
const styles_HeaderComponent:any[] = [import9.styles];
var renderType_HeaderComponent:import4.RenderComponentType = import3.createRenderComponentType('',0,import5.ViewEncapsulation.Emulated,styles_HeaderComponent,{});
export class View_HeaderComponent0 extends import2.AppView<import0.HeaderComponent> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _el_6:any;
  _text_7:any;
  _el_8:any;
  _text_9:any;
  _el_10:any;
  _text_11:any;
  _el_12:any;
  _RouterLinkWithHref_12_3:import10.Wrapper_RouterLinkWithHref;
  _RouterLinkActive_12_4:import11.Wrapper_RouterLinkActive;
  _query_RouterLink_12_0:import12.QueryList<any>;
  _query_RouterLinkWithHref_12_1:import12.QueryList<any>;
  _text_13:any;
  _text_14:any;
  _el_15:any;
  _RouterLinkWithHref_15_3:import10.Wrapper_RouterLinkWithHref;
  _RouterLinkActive_15_4:import11.Wrapper_RouterLinkActive;
  _query_RouterLink_15_0:import12.QueryList<any>;
  _query_RouterLinkWithHref_15_1:import12.QueryList<any>;
  _text_16:any;
  _text_17:any;
  _el_18:any;
  _RouterLinkWithHref_18_3:import10.Wrapper_RouterLinkWithHref;
  _RouterLinkActive_18_4:import11.Wrapper_RouterLinkActive;
  _query_RouterLink_18_0:import12.QueryList<any>;
  _query_RouterLinkWithHref_18_1:import12.QueryList<any>;
  _text_19:any;
  _text_20:any;
  _text_21:any;
  _text_22:any;
  _text_23:any;
  _el_24:any;
  _text_25:any;
  _el_26:any;
  _text_27:any;
  _el_28:any;
  _text_29:any;
  _el_30:any;
  _text_31:any;
  _el_32:any;
  _el_33:any;
  _text_34:any;
  _el_35:any;
  _el_36:any;
  _text_37:any;
  _el_38:any;
  _el_39:any;
  _text_40:any;
  _el_41:any;
  _el_42:any;
  _text_43:any;
  _el_44:any;
  _el_45:any;
  _text_46:any;
  _el_47:any;
  _el_48:any;
  _text_49:any;
  _el_50:any;
  _el_51:any;
  _text_52:any;
  _el_53:any;
  _text_54:any;
  _text_55:any;
  _text_56:any;
  _text_57:any;
  _text_58:any;
  _el_59:any;
  _text_60:any;
  _el_61:any;
  _text_62:any;
  _el_63:any;
  _text_64:any;
  _text_65:any;
  _text_66:any;
  _text_67:any;
  _text_68:any;
  _text_69:any;
  _text_70:any;
  _el_71:any;
  _text_72:any;
  _el_73:any;
  _text_74:any;
  _el_75:any;
  _text_76:any;
  _el_77:any;
  _text_78:any;
  _text_79:any;
  _el_80:any;
  _text_81:any;
  _text_82:any;
  _text_83:any;
  _el_84:any;
  _text_85:any;
  _el_86:any;
  _text_87:any;
  _el_88:any;
  _el_89:any;
  _RouterLinkWithHref_89_3:import10.Wrapper_RouterLinkWithHref;
  _RouterLinkActive_89_4:import11.Wrapper_RouterLinkActive;
  _query_RouterLink_89_0:import12.QueryList<any>;
  _query_RouterLinkWithHref_89_1:import12.QueryList<any>;
  _text_90:any;
  _text_91:any;
  _el_92:any;
  _el_93:any;
  _RouterLinkWithHref_93_3:import10.Wrapper_RouterLinkWithHref;
  _RouterLinkActive_93_4:import11.Wrapper_RouterLinkActive;
  _query_RouterLink_93_0:import12.QueryList<any>;
  _query_RouterLinkWithHref_93_1:import12.QueryList<any>;
  _text_94:any;
  _text_95:any;
  _el_96:any;
  _el_97:any;
  _RouterLinkWithHref_97_3:import10.Wrapper_RouterLinkWithHref;
  _RouterLinkActive_97_4:import11.Wrapper_RouterLinkActive;
  _query_RouterLink_97_0:import12.QueryList<any>;
  _query_RouterLinkWithHref_97_1:import12.QueryList<any>;
  _text_98:any;
  _text_99:any;
  _el_100:any;
  _el_101:any;
  _RouterLinkWithHref_101_3:import10.Wrapper_RouterLinkWithHref;
  _RouterLinkActive_101_4:import11.Wrapper_RouterLinkActive;
  _query_RouterLink_101_0:import12.QueryList<any>;
  _query_RouterLinkWithHref_101_1:import12.QueryList<any>;
  _text_102:any;
  _text_103:any;
  _el_104:any;
  _el_105:any;
  _RouterLinkWithHref_105_3:import10.Wrapper_RouterLinkWithHref;
  _RouterLinkActive_105_4:import11.Wrapper_RouterLinkActive;
  _query_RouterLink_105_0:import12.QueryList<any>;
  _query_RouterLinkWithHref_105_1:import12.QueryList<any>;
  _text_106:any;
  _text_107:any;
  _el_108:any;
  _el_109:any;
  _RouterLinkWithHref_109_3:import10.Wrapper_RouterLinkWithHref;
  _RouterLinkActive_109_4:import11.Wrapper_RouterLinkActive;
  _query_RouterLink_109_0:import12.QueryList<any>;
  _query_RouterLinkWithHref_109_1:import12.QueryList<any>;
  _text_110:any;
  _text_111:any;
  _text_112:any;
  _text_113:any;
  _text_114:any;
  _text_115:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import2.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_HeaderComponent0,renderType_HeaderComponent,import6.ViewType.COMPONENT,viewUtils,parentView,parentIndex,parentElement,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import8.ComponentRef<any> {
    const parentRenderNode:any = this.renderer.createViewRoot(this.parentElement);
    this._el_0 = import3.createRenderElement(this.renderer,parentRenderNode,'div',new import3.InlineArray2(2,'class','container-fluid col-xs-12 header'),(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n  ',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,this._el_0,'div',new import3.InlineArray2(2,'class','container col-xs-12'),(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'\n    ',(null as any));
    this._el_4 = import3.createRenderElement(this.renderer,this._el_2,'div',new import3.InlineArray2(2,'class','row'),(null as any));
    this._text_5 = this.renderer.createText(this._el_4,'\n      ',(null as any));
    this._el_6 = import3.createRenderElement(this.renderer,this._el_4,'div',new import3.InlineArray2(2,'class','col-xs-12 col-sm-7 right channel'),(null as any));
    this._text_7 = this.renderer.createText(this._el_6,'\n        ',(null as any));
    this._el_8 = import3.createRenderElement(this.renderer,this._el_6,'div',new import3.InlineArray2(2,'class','row'),(null as any));
    this._text_9 = this.renderer.createText(this._el_8,'\n          ',(null as any));
    this._el_10 = import3.createRenderElement(this.renderer,this._el_8,'nav',new import3.InlineArray2(2,'class','topnav'),(null as any));
    this._text_11 = this.renderer.createText(this._el_10,'\n            ',(null as any));
    this._el_12 = import3.createRenderElement(this.renderer,this._el_10,'a',new import3.InlineArray8(6,'class','col-xs-4 center','routerLink','/faq','routerLinkActive','active'),(null as any));
    this._RouterLinkWithHref_12_3 = new import10.Wrapper_RouterLinkWithHref(this.parentView.injectorGet(import13.Router,this.parentIndex),this.parentView.injectorGet(import14.ActivatedRoute,this.parentIndex),this.parentView.injectorGet(import15.LocationStrategy,this.parentIndex));
    this._RouterLinkActive_12_4 = new import11.Wrapper_RouterLinkActive(this.parentView.injectorGet(import13.Router,this.parentIndex),new import16.ElementRef(this._el_12),this.renderer,this.ref);
    this._query_RouterLink_12_0 = new import12.QueryList<any>();
    this._query_RouterLinkWithHref_12_1 = new import12.QueryList<any>();
    this._text_13 = this.renderer.createText(this._el_12,'FAQ',(null as any));
    this._text_14 = this.renderer.createText(this._el_10,'\n            ',(null as any));
    this._el_15 = import3.createRenderElement(this.renderer,this._el_10,'a',new import3.InlineArray8(6,'class','col-xs-4 center','routerLink','/investors','routerLinkActive','active'),(null as any));
    this._RouterLinkWithHref_15_3 = new import10.Wrapper_RouterLinkWithHref(this.parentView.injectorGet(import13.Router,this.parentIndex),this.parentView.injectorGet(import14.ActivatedRoute,this.parentIndex),this.parentView.injectorGet(import15.LocationStrategy,this.parentIndex));
    this._RouterLinkActive_15_4 = new import11.Wrapper_RouterLinkActive(this.parentView.injectorGet(import13.Router,this.parentIndex),new import16.ElementRef(this._el_15),this.renderer,this.ref);
    this._query_RouterLink_15_0 = new import12.QueryList<any>();
    this._query_RouterLinkWithHref_15_1 = new import12.QueryList<any>();
    this._text_16 = this.renderer.createText(this._el_15,'INVESTORS',(null as any));
    this._text_17 = this.renderer.createText(this._el_10,'\n            ',(null as any));
    this._el_18 = import3.createRenderElement(this.renderer,this._el_10,'a',new import3.InlineArray8(6,'class','col-xs-4 center','routerLink','/contactus','routerLinkActive','active'),(null as any));
    this._RouterLinkWithHref_18_3 = new import10.Wrapper_RouterLinkWithHref(this.parentView.injectorGet(import13.Router,this.parentIndex),this.parentView.injectorGet(import14.ActivatedRoute,this.parentIndex),this.parentView.injectorGet(import15.LocationStrategy,this.parentIndex));
    this._RouterLinkActive_18_4 = new import11.Wrapper_RouterLinkActive(this.parentView.injectorGet(import13.Router,this.parentIndex),new import16.ElementRef(this._el_18),this.renderer,this.ref);
    this._query_RouterLink_18_0 = new import12.QueryList<any>();
    this._query_RouterLinkWithHref_18_1 = new import12.QueryList<any>();
    this._text_19 = this.renderer.createText(this._el_18,'CONTACT US',(null as any));
    this._text_20 = this.renderer.createText(this._el_10,'\n          ',(null as any));
    this._text_21 = this.renderer.createText(this._el_8,'\n        ',(null as any));
    this._text_22 = this.renderer.createText(this._el_6,'\n      ',(null as any));
    this._text_23 = this.renderer.createText(this._el_4,'\n      ',(null as any));
    this._el_24 = import3.createRenderElement(this.renderer,this._el_4,'div',new import3.InlineArray2(2,'class','col-xs-12 col-sm-3 center channel'),(null as any));
    this._text_25 = this.renderer.createText(this._el_24,'\n        ',(null as any));
    this._el_26 = import3.createRenderElement(this.renderer,this._el_24,'div',new import3.InlineArray2(2,'class','row'),(null as any));
    this._text_27 = this.renderer.createText(this._el_26,'\n          ',(null as any));
    this._el_28 = import3.createRenderElement(this.renderer,this._el_26,'nav',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_29 = this.renderer.createText(this._el_28,'\n            ',(null as any));
    this._el_30 = import3.createRenderElement(this.renderer,this._el_28,'div',new import3.InlineArray2(2,'class','col-xs-3'),(null as any));
    this._text_31 = this.renderer.createText(this._el_28,'\n            ',(null as any));
    this._el_32 = import3.createRenderElement(this.renderer,this._el_28,'div',new import3.InlineArray2(2,'class','col-xs-1'),(null as any));
    this._el_33 = import3.createRenderElement(this.renderer,this._el_32,'i',new import3.InlineArray2(2,'class','fa fa-facebook col-xs-1'),(null as any));
    this._text_34 = this.renderer.createText(this._el_28,'\n            ',(null as any));
    this._el_35 = import3.createRenderElement(this.renderer,this._el_28,'div',new import3.InlineArray2(2,'class','col-xs-1'),(null as any));
    this._el_36 = import3.createRenderElement(this.renderer,this._el_35,'i',new import3.InlineArray2(2,'class','fa fa-twitter col-xs-1'),(null as any));
    this._text_37 = this.renderer.createText(this._el_28,'\n            ',(null as any));
    this._el_38 = import3.createRenderElement(this.renderer,this._el_28,'div',new import3.InlineArray2(2,'class','col-xs-1'),(null as any));
    this._el_39 = import3.createRenderElement(this.renderer,this._el_38,'i',new import3.InlineArray2(2,'class','fa fa-linkedin col-xs-1'),(null as any));
    this._text_40 = this.renderer.createText(this._el_28,'\n            ',(null as any));
    this._el_41 = import3.createRenderElement(this.renderer,this._el_28,'div',new import3.InlineArray2(2,'class','col-xs-1'),(null as any));
    this._el_42 = import3.createRenderElement(this.renderer,this._el_41,'i',new import3.InlineArray2(2,'class','fa fa-google-plus col-xs-1'),(null as any));
    this._text_43 = this.renderer.createText(this._el_28,'\n            ',(null as any));
    this._el_44 = import3.createRenderElement(this.renderer,this._el_28,'div',new import3.InlineArray2(2,'class','col-xs-1'),(null as any));
    this._el_45 = import3.createRenderElement(this.renderer,this._el_44,'i',new import3.InlineArray2(2,'class','fa fa-youtube col-xs-1'),(null as any));
    this._text_46 = this.renderer.createText(this._el_28,'\n            ',(null as any));
    this._el_47 = import3.createRenderElement(this.renderer,this._el_28,'div',new import3.InlineArray2(2,'class','col-xs-1'),(null as any));
    this._el_48 = import3.createRenderElement(this.renderer,this._el_47,'i',new import3.InlineArray2(2,'class','fa fa-instagram col-xs-1'),(null as any));
    this._text_49 = this.renderer.createText(this._el_28,'\n            ',(null as any));
    this._el_50 = import3.createRenderElement(this.renderer,this._el_28,'div',new import3.InlineArray2(2,'class','col-xs-1'),(null as any));
    this._el_51 = import3.createRenderElement(this.renderer,this._el_50,'i',new import3.InlineArray2(2,'class','fa fa-pinterest col-xs-1'),(null as any));
    this._text_52 = this.renderer.createText(this._el_28,'\n            ',(null as any));
    this._el_53 = import3.createRenderElement(this.renderer,this._el_28,'div',new import3.InlineArray2(2,'class','col-xs-2'),(null as any));
    this._text_54 = this.renderer.createText(this._el_28,'\n          ',(null as any));
    this._text_55 = this.renderer.createText(this._el_26,'\n        ',(null as any));
    this._text_56 = this.renderer.createText(this._el_24,'\n        ',(null as any));
    this._text_57 = this.renderer.createText(this._el_24,'\n\n      ',(null as any));
    this._text_58 = this.renderer.createText(this._el_4,'\n      ',(null as any));
    this._el_59 = import3.createRenderElement(this.renderer,this._el_4,'div',new import3.InlineArray2(2,'class','col-xs-12 col-sm-2 center channel'),(null as any));
    this._text_60 = this.renderer.createText(this._el_59,'\n        ',(null as any));
    this._el_61 = import3.createRenderElement(this.renderer,this._el_59,'div',new import3.InlineArray2(2,'class','row'),(null as any));
    this._text_62 = this.renderer.createText(this._el_61,'\n          ',(null as any));
    this._el_63 = import3.createRenderElement(this.renderer,this._el_61,'div',new import3.InlineArray2(2,'class','col-xs-12 phone'),(null as any));
    this._text_64 = this.renderer.createText(this._el_63,'\n            (813) 444-4567\n          ',(null as any));
    this._text_65 = this.renderer.createText(this._el_61,'\n        ',(null as any));
    this._text_66 = this.renderer.createText(this._el_59,'\n      ',(null as any));
    this._text_67 = this.renderer.createText(this._el_4,'\n    ',(null as any));
    this._text_68 = this.renderer.createText(this._el_2,'\n  ',(null as any));
    this._text_69 = this.renderer.createText(this._el_0,'\n',(null as any));
    this._text_70 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._el_71 = import3.createRenderElement(this.renderer,parentRenderNode,'div',new import3.InlineArray2(2,'class','container-fluid col-xs-12 banner'),(null as any));
    this._text_72 = this.renderer.createText(this._el_71,'\n  ',(null as any));
    this._el_73 = import3.createRenderElement(this.renderer,this._el_71,'div',new import3.InlineArray2(2,'class','container col-xs-12'),(null as any));
    this._text_74 = this.renderer.createText(this._el_73,'\n    ',(null as any));
    this._el_75 = import3.createRenderElement(this.renderer,this._el_73,'div',new import3.InlineArray2(2,'class','row'),(null as any));
    this._text_76 = this.renderer.createText(this._el_75,'\n      ',(null as any));
    this._el_77 = import3.createRenderElement(this.renderer,this._el_75,'div',new import3.InlineArray2(2,'class','col-xs-12 col-sm-4 col-md-3'),(null as any));
    this._text_78 = this.renderer.createText(this._el_77,'\n        ',(null as any));
    this._text_79 = this.renderer.createText(this._el_77,'\n        ',(null as any));
    this._el_80 = import3.createRenderElement(this.renderer,this._el_77,'img',new import3.InlineArray4(4,'class','col-xs-12 col-sm-12 logo','src','../images/logo.jpg'),(null as any));
    this._text_81 = this.renderer.createText(this._el_77,'\n        ',(null as any));
    this._text_82 = this.renderer.createText(this._el_77,'\n      ',(null as any));
    this._text_83 = this.renderer.createText(this._el_75,' \n      ',(null as any));
    this._el_84 = import3.createRenderElement(this.renderer,this._el_75,'div',new import3.InlineArray2(2,'class','col-xs-12 col-sm-8 col-md-9'),(null as any));
    this._text_85 = this.renderer.createText(this._el_84,'\n\n        ',(null as any));
    this._el_86 = import3.createRenderElement(this.renderer,this._el_84,'ul',new import3.InlineArray2(2,'class','nav nav-pills'),(null as any));
    this._text_87 = this.renderer.createText(this._el_86,'\n          ',(null as any));
    this._el_88 = import3.createRenderElement(this.renderer,this._el_86,'li',new import3.InlineArray2(2,'role','presentation'),(null as any));
    this._el_89 = import3.createRenderElement(this.renderer,this._el_88,'a',new import3.InlineArray8(6,'class','center','routerLink','/home','routerLinkActive','active'),(null as any));
    this._RouterLinkWithHref_89_3 = new import10.Wrapper_RouterLinkWithHref(this.parentView.injectorGet(import13.Router,this.parentIndex),this.parentView.injectorGet(import14.ActivatedRoute,this.parentIndex),this.parentView.injectorGet(import15.LocationStrategy,this.parentIndex));
    this._RouterLinkActive_89_4 = new import11.Wrapper_RouterLinkActive(this.parentView.injectorGet(import13.Router,this.parentIndex),new import16.ElementRef(this._el_89),this.renderer,this.ref);
    this._query_RouterLink_89_0 = new import12.QueryList<any>();
    this._query_RouterLinkWithHref_89_1 = new import12.QueryList<any>();
    this._text_90 = this.renderer.createText(this._el_89,'HOME',(null as any));
    this._text_91 = this.renderer.createText(this._el_86,'\n          ',(null as any));
    this._el_92 = import3.createRenderElement(this.renderer,this._el_86,'li',new import3.InlineArray2(2,'role','presentation'),(null as any));
    this._el_93 = import3.createRenderElement(this.renderer,this._el_92,'a',new import3.InlineArray8(6,'class','center','routerLink','/about','routerLinkActive','active'),(null as any));
    this._RouterLinkWithHref_93_3 = new import10.Wrapper_RouterLinkWithHref(this.parentView.injectorGet(import13.Router,this.parentIndex),this.parentView.injectorGet(import14.ActivatedRoute,this.parentIndex),this.parentView.injectorGet(import15.LocationStrategy,this.parentIndex));
    this._RouterLinkActive_93_4 = new import11.Wrapper_RouterLinkActive(this.parentView.injectorGet(import13.Router,this.parentIndex),new import16.ElementRef(this._el_93),this.renderer,this.ref);
    this._query_RouterLink_93_0 = new import12.QueryList<any>();
    this._query_RouterLinkWithHref_93_1 = new import12.QueryList<any>();
    this._text_94 = this.renderer.createText(this._el_93,'ABOUT',(null as any));
    this._text_95 = this.renderer.createText(this._el_86,'\n          ',(null as any));
    this._el_96 = import3.createRenderElement(this.renderer,this._el_86,'li',new import3.InlineArray2(2,'role','presentation'),(null as any));
    this._el_97 = import3.createRenderElement(this.renderer,this._el_96,'a',new import3.InlineArray8(6,'class','center','routerLink','/buy','routerLinkActive','active'),(null as any));
    this._RouterLinkWithHref_97_3 = new import10.Wrapper_RouterLinkWithHref(this.parentView.injectorGet(import13.Router,this.parentIndex),this.parentView.injectorGet(import14.ActivatedRoute,this.parentIndex),this.parentView.injectorGet(import15.LocationStrategy,this.parentIndex));
    this._RouterLinkActive_97_4 = new import11.Wrapper_RouterLinkActive(this.parentView.injectorGet(import13.Router,this.parentIndex),new import16.ElementRef(this._el_97),this.renderer,this.ref);
    this._query_RouterLink_97_0 = new import12.QueryList<any>();
    this._query_RouterLinkWithHref_97_1 = new import12.QueryList<any>();
    this._text_98 = this.renderer.createText(this._el_97,'BUY A HOME',(null as any));
    this._text_99 = this.renderer.createText(this._el_86,'\n          ',(null as any));
    this._el_100 = import3.createRenderElement(this.renderer,this._el_86,'li',new import3.InlineArray2(2,'role','presentation'),(null as any));
    this._el_101 = import3.createRenderElement(this.renderer,this._el_100,'a',new import3.InlineArray8(6,'class','center','routerLink','/wholesale','routerLinkActive','active'),(null as any));
    this._RouterLinkWithHref_101_3 = new import10.Wrapper_RouterLinkWithHref(this.parentView.injectorGet(import13.Router,this.parentIndex),this.parentView.injectorGet(import14.ActivatedRoute,this.parentIndex),this.parentView.injectorGet(import15.LocationStrategy,this.parentIndex));
    this._RouterLinkActive_101_4 = new import11.Wrapper_RouterLinkActive(this.parentView.injectorGet(import13.Router,this.parentIndex),new import16.ElementRef(this._el_101),this.renderer,this.ref);
    this._query_RouterLink_101_0 = new import12.QueryList<any>();
    this._query_RouterLinkWithHref_101_1 = new import12.QueryList<any>();
    this._text_102 = this.renderer.createText(this._el_101,'WHOLESALE',(null as any));
    this._text_103 = this.renderer.createText(this._el_86,'\n          ',(null as any));
    this._el_104 = import3.createRenderElement(this.renderer,this._el_86,'li',new import3.InlineArray2(2,'role','presentation'),(null as any));
    this._el_105 = import3.createRenderElement(this.renderer,this._el_104,'a',new import3.InlineArray8(6,'class','center','routerLink','/sell','routerLinkActive','active'),(null as any));
    this._RouterLinkWithHref_105_3 = new import10.Wrapper_RouterLinkWithHref(this.parentView.injectorGet(import13.Router,this.parentIndex),this.parentView.injectorGet(import14.ActivatedRoute,this.parentIndex),this.parentView.injectorGet(import15.LocationStrategy,this.parentIndex));
    this._RouterLinkActive_105_4 = new import11.Wrapper_RouterLinkActive(this.parentView.injectorGet(import13.Router,this.parentIndex),new import16.ElementRef(this._el_105),this.renderer,this.ref);
    this._query_RouterLink_105_0 = new import12.QueryList<any>();
    this._query_RouterLinkWithHref_105_1 = new import12.QueryList<any>();
    this._text_106 = this.renderer.createText(this._el_105,'SELL YOUR HOME',(null as any));
    this._text_107 = this.renderer.createText(this._el_86,'\n          ',(null as any));
    this._el_108 = import3.createRenderElement(this.renderer,this._el_86,'li',new import3.InlineArray2(2,'role','presentation'),(null as any));
    this._el_109 = import3.createRenderElement(this.renderer,this._el_108,'a',new import3.InlineArray8(6,'class','center','routerLink','/blog','routerLinkActive','active'),(null as any));
    this._RouterLinkWithHref_109_3 = new import10.Wrapper_RouterLinkWithHref(this.parentView.injectorGet(import13.Router,this.parentIndex),this.parentView.injectorGet(import14.ActivatedRoute,this.parentIndex),this.parentView.injectorGet(import15.LocationStrategy,this.parentIndex));
    this._RouterLinkActive_109_4 = new import11.Wrapper_RouterLinkActive(this.parentView.injectorGet(import13.Router,this.parentIndex),new import16.ElementRef(this._el_109),this.renderer,this.ref);
    this._query_RouterLink_109_0 = new import12.QueryList<any>();
    this._query_RouterLinkWithHref_109_1 = new import12.QueryList<any>();
    this._text_110 = this.renderer.createText(this._el_109,'BLOG',(null as any));
    this._text_111 = this.renderer.createText(this._el_86,'\n        ',(null as any));
    this._text_112 = this.renderer.createText(this._el_84,'\n\n      ',(null as any));
    this._text_113 = this.renderer.createText(this._el_75,'\n    ',(null as any));
    this._text_114 = this.renderer.createText(this._el_73,'\n  ',(null as any));
    this._text_115 = this.renderer.createText(this._el_71,'\n',(null as any));
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_12,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_12));
    var disposable_1:Function = import3.subscribeToRenderElement(this,this._el_15,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_15));
    var disposable_2:Function = import3.subscribeToRenderElement(this,this._el_18,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_18));
    var disposable_3:Function = import3.subscribeToRenderElement(this,this._el_89,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_89));
    var disposable_4:Function = import3.subscribeToRenderElement(this,this._el_93,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_93));
    var disposable_5:Function = import3.subscribeToRenderElement(this,this._el_97,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_97));
    var disposable_6:Function = import3.subscribeToRenderElement(this,this._el_101,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_101));
    var disposable_7:Function = import3.subscribeToRenderElement(this,this._el_105,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_105));
    var disposable_8:Function = import3.subscribeToRenderElement(this,this._el_109,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_109));
    this.init((null as any),((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._el_8,
      this._text_9,
      this._el_10,
      this._text_11,
      this._el_12,
      this._text_13,
      this._text_14,
      this._el_15,
      this._text_16,
      this._text_17,
      this._el_18,
      this._text_19,
      this._text_20,
      this._text_21,
      this._text_22,
      this._text_23,
      this._el_24,
      this._text_25,
      this._el_26,
      this._text_27,
      this._el_28,
      this._text_29,
      this._el_30,
      this._text_31,
      this._el_32,
      this._el_33,
      this._text_34,
      this._el_35,
      this._el_36,
      this._text_37,
      this._el_38,
      this._el_39,
      this._text_40,
      this._el_41,
      this._el_42,
      this._text_43,
      this._el_44,
      this._el_45,
      this._text_46,
      this._el_47,
      this._el_48,
      this._text_49,
      this._el_50,
      this._el_51,
      this._text_52,
      this._el_53,
      this._text_54,
      this._text_55,
      this._text_56,
      this._text_57,
      this._text_58,
      this._el_59,
      this._text_60,
      this._el_61,
      this._text_62,
      this._el_63,
      this._text_64,
      this._text_65,
      this._text_66,
      this._text_67,
      this._text_68,
      this._text_69,
      this._text_70,
      this._el_71,
      this._text_72,
      this._el_73,
      this._text_74,
      this._el_75,
      this._text_76,
      this._el_77,
      this._text_78,
      this._text_79,
      this._el_80,
      this._text_81,
      this._text_82,
      this._text_83,
      this._el_84,
      this._text_85,
      this._el_86,
      this._text_87,
      this._el_88,
      this._el_89,
      this._text_90,
      this._text_91,
      this._el_92,
      this._el_93,
      this._text_94,
      this._text_95,
      this._el_96,
      this._el_97,
      this._text_98,
      this._text_99,
      this._el_100,
      this._el_101,
      this._text_102,
      this._text_103,
      this._el_104,
      this._el_105,
      this._text_106,
      this._text_107,
      this._el_108,
      this._el_109,
      this._text_110,
      this._text_111,
      this._text_112,
      this._text_113,
      this._text_114,
      this._text_115
    ]
    ),[
      disposable_0,
      disposable_1,
      disposable_2,
      disposable_3,
      disposable_4,
      disposable_5,
      disposable_6,
      disposable_7,
      disposable_8
    ]
    );
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import17.RouterLinkWithHref) && ((12 <= requestNodeIndex) && (requestNodeIndex <= 13)))) { return this._RouterLinkWithHref_12_3.context; }
    if (((token === import18.RouterLinkActive) && ((12 <= requestNodeIndex) && (requestNodeIndex <= 13)))) { return this._RouterLinkActive_12_4.context; }
    if (((token === import17.RouterLinkWithHref) && ((15 <= requestNodeIndex) && (requestNodeIndex <= 16)))) { return this._RouterLinkWithHref_15_3.context; }
    if (((token === import18.RouterLinkActive) && ((15 <= requestNodeIndex) && (requestNodeIndex <= 16)))) { return this._RouterLinkActive_15_4.context; }
    if (((token === import17.RouterLinkWithHref) && ((18 <= requestNodeIndex) && (requestNodeIndex <= 19)))) { return this._RouterLinkWithHref_18_3.context; }
    if (((token === import18.RouterLinkActive) && ((18 <= requestNodeIndex) && (requestNodeIndex <= 19)))) { return this._RouterLinkActive_18_4.context; }
    if (((token === import17.RouterLinkWithHref) && ((89 <= requestNodeIndex) && (requestNodeIndex <= 90)))) { return this._RouterLinkWithHref_89_3.context; }
    if (((token === import18.RouterLinkActive) && ((89 <= requestNodeIndex) && (requestNodeIndex <= 90)))) { return this._RouterLinkActive_89_4.context; }
    if (((token === import17.RouterLinkWithHref) && ((93 <= requestNodeIndex) && (requestNodeIndex <= 94)))) { return this._RouterLinkWithHref_93_3.context; }
    if (((token === import18.RouterLinkActive) && ((93 <= requestNodeIndex) && (requestNodeIndex <= 94)))) { return this._RouterLinkActive_93_4.context; }
    if (((token === import17.RouterLinkWithHref) && ((97 <= requestNodeIndex) && (requestNodeIndex <= 98)))) { return this._RouterLinkWithHref_97_3.context; }
    if (((token === import18.RouterLinkActive) && ((97 <= requestNodeIndex) && (requestNodeIndex <= 98)))) { return this._RouterLinkActive_97_4.context; }
    if (((token === import17.RouterLinkWithHref) && ((101 <= requestNodeIndex) && (requestNodeIndex <= 102)))) { return this._RouterLinkWithHref_101_3.context; }
    if (((token === import18.RouterLinkActive) && ((101 <= requestNodeIndex) && (requestNodeIndex <= 102)))) { return this._RouterLinkActive_101_4.context; }
    if (((token === import17.RouterLinkWithHref) && ((105 <= requestNodeIndex) && (requestNodeIndex <= 106)))) { return this._RouterLinkWithHref_105_3.context; }
    if (((token === import18.RouterLinkActive) && ((105 <= requestNodeIndex) && (requestNodeIndex <= 106)))) { return this._RouterLinkActive_105_4.context; }
    if (((token === import17.RouterLinkWithHref) && ((109 <= requestNodeIndex) && (requestNodeIndex <= 110)))) { return this._RouterLinkWithHref_109_3.context; }
    if (((token === import18.RouterLinkActive) && ((109 <= requestNodeIndex) && (requestNodeIndex <= 110)))) { return this._RouterLinkActive_109_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_12_0_0:any = '/faq';
    this._RouterLinkWithHref_12_3.check_routerLink(currVal_12_0_0,throwOnChange,false);
    this._RouterLinkWithHref_12_3.ngDoCheck(this,this._el_12,throwOnChange);
    const currVal_12_1_0:any = 'active';
    this._RouterLinkActive_12_4.check_routerLinkActive(currVal_12_1_0,throwOnChange,false);
    this._RouterLinkActive_12_4.ngDoCheck(this,this._el_12,throwOnChange);
    const currVal_15_0_0:any = '/investors';
    this._RouterLinkWithHref_15_3.check_routerLink(currVal_15_0_0,throwOnChange,false);
    this._RouterLinkWithHref_15_3.ngDoCheck(this,this._el_15,throwOnChange);
    const currVal_15_1_0:any = 'active';
    this._RouterLinkActive_15_4.check_routerLinkActive(currVal_15_1_0,throwOnChange,false);
    this._RouterLinkActive_15_4.ngDoCheck(this,this._el_15,throwOnChange);
    const currVal_18_0_0:any = '/contactus';
    this._RouterLinkWithHref_18_3.check_routerLink(currVal_18_0_0,throwOnChange,false);
    this._RouterLinkWithHref_18_3.ngDoCheck(this,this._el_18,throwOnChange);
    const currVal_18_1_0:any = 'active';
    this._RouterLinkActive_18_4.check_routerLinkActive(currVal_18_1_0,throwOnChange,false);
    this._RouterLinkActive_18_4.ngDoCheck(this,this._el_18,throwOnChange);
    const currVal_89_0_0:any = '/home';
    this._RouterLinkWithHref_89_3.check_routerLink(currVal_89_0_0,throwOnChange,false);
    this._RouterLinkWithHref_89_3.ngDoCheck(this,this._el_89,throwOnChange);
    const currVal_89_1_0:any = 'active';
    this._RouterLinkActive_89_4.check_routerLinkActive(currVal_89_1_0,throwOnChange,false);
    this._RouterLinkActive_89_4.ngDoCheck(this,this._el_89,throwOnChange);
    const currVal_93_0_0:any = '/about';
    this._RouterLinkWithHref_93_3.check_routerLink(currVal_93_0_0,throwOnChange,false);
    this._RouterLinkWithHref_93_3.ngDoCheck(this,this._el_93,throwOnChange);
    const currVal_93_1_0:any = 'active';
    this._RouterLinkActive_93_4.check_routerLinkActive(currVal_93_1_0,throwOnChange,false);
    this._RouterLinkActive_93_4.ngDoCheck(this,this._el_93,throwOnChange);
    const currVal_97_0_0:any = '/buy';
    this._RouterLinkWithHref_97_3.check_routerLink(currVal_97_0_0,throwOnChange,false);
    this._RouterLinkWithHref_97_3.ngDoCheck(this,this._el_97,throwOnChange);
    const currVal_97_1_0:any = 'active';
    this._RouterLinkActive_97_4.check_routerLinkActive(currVal_97_1_0,throwOnChange,false);
    this._RouterLinkActive_97_4.ngDoCheck(this,this._el_97,throwOnChange);
    const currVal_101_0_0:any = '/wholesale';
    this._RouterLinkWithHref_101_3.check_routerLink(currVal_101_0_0,throwOnChange,false);
    this._RouterLinkWithHref_101_3.ngDoCheck(this,this._el_101,throwOnChange);
    const currVal_101_1_0:any = 'active';
    this._RouterLinkActive_101_4.check_routerLinkActive(currVal_101_1_0,throwOnChange,false);
    this._RouterLinkActive_101_4.ngDoCheck(this,this._el_101,throwOnChange);
    const currVal_105_0_0:any = '/sell';
    this._RouterLinkWithHref_105_3.check_routerLink(currVal_105_0_0,throwOnChange,false);
    this._RouterLinkWithHref_105_3.ngDoCheck(this,this._el_105,throwOnChange);
    const currVal_105_1_0:any = 'active';
    this._RouterLinkActive_105_4.check_routerLinkActive(currVal_105_1_0,throwOnChange,false);
    this._RouterLinkActive_105_4.ngDoCheck(this,this._el_105,throwOnChange);
    const currVal_109_0_0:any = '/blog';
    this._RouterLinkWithHref_109_3.check_routerLink(currVal_109_0_0,throwOnChange,false);
    this._RouterLinkWithHref_109_3.ngDoCheck(this,this._el_109,throwOnChange);
    const currVal_109_1_0:any = 'active';
    this._RouterLinkActive_109_4.check_routerLinkActive(currVal_109_1_0,throwOnChange,false);
    this._RouterLinkActive_109_4.ngDoCheck(this,this._el_109,throwOnChange);
    if (!throwOnChange) {
      if (this._query_RouterLink_12_0.dirty) {
        this._query_RouterLink_12_0.reset(([] as any[]));
        this._RouterLinkActive_12_4.context.links = this._query_RouterLink_12_0;
        this._query_RouterLink_12_0.notifyOnChanges();
      }
      if (this._query_RouterLinkWithHref_12_1.dirty) {
        this._query_RouterLinkWithHref_12_1.reset([this._RouterLinkWithHref_12_3.context]);
        this._RouterLinkActive_12_4.context.linksWithHrefs = this._query_RouterLinkWithHref_12_1;
        this._query_RouterLinkWithHref_12_1.notifyOnChanges();
      }
      if (this._query_RouterLink_15_0.dirty) {
        this._query_RouterLink_15_0.reset(([] as any[]));
        this._RouterLinkActive_15_4.context.links = this._query_RouterLink_15_0;
        this._query_RouterLink_15_0.notifyOnChanges();
      }
      if (this._query_RouterLinkWithHref_15_1.dirty) {
        this._query_RouterLinkWithHref_15_1.reset([this._RouterLinkWithHref_15_3.context]);
        this._RouterLinkActive_15_4.context.linksWithHrefs = this._query_RouterLinkWithHref_15_1;
        this._query_RouterLinkWithHref_15_1.notifyOnChanges();
      }
      if (this._query_RouterLink_18_0.dirty) {
        this._query_RouterLink_18_0.reset(([] as any[]));
        this._RouterLinkActive_18_4.context.links = this._query_RouterLink_18_0;
        this._query_RouterLink_18_0.notifyOnChanges();
      }
      if (this._query_RouterLinkWithHref_18_1.dirty) {
        this._query_RouterLinkWithHref_18_1.reset([this._RouterLinkWithHref_18_3.context]);
        this._RouterLinkActive_18_4.context.linksWithHrefs = this._query_RouterLinkWithHref_18_1;
        this._query_RouterLinkWithHref_18_1.notifyOnChanges();
      }
      if (this._query_RouterLink_89_0.dirty) {
        this._query_RouterLink_89_0.reset(([] as any[]));
        this._RouterLinkActive_89_4.context.links = this._query_RouterLink_89_0;
        this._query_RouterLink_89_0.notifyOnChanges();
      }
      if (this._query_RouterLinkWithHref_89_1.dirty) {
        this._query_RouterLinkWithHref_89_1.reset([this._RouterLinkWithHref_89_3.context]);
        this._RouterLinkActive_89_4.context.linksWithHrefs = this._query_RouterLinkWithHref_89_1;
        this._query_RouterLinkWithHref_89_1.notifyOnChanges();
      }
      if (this._query_RouterLink_93_0.dirty) {
        this._query_RouterLink_93_0.reset(([] as any[]));
        this._RouterLinkActive_93_4.context.links = this._query_RouterLink_93_0;
        this._query_RouterLink_93_0.notifyOnChanges();
      }
      if (this._query_RouterLinkWithHref_93_1.dirty) {
        this._query_RouterLinkWithHref_93_1.reset([this._RouterLinkWithHref_93_3.context]);
        this._RouterLinkActive_93_4.context.linksWithHrefs = this._query_RouterLinkWithHref_93_1;
        this._query_RouterLinkWithHref_93_1.notifyOnChanges();
      }
      if (this._query_RouterLink_97_0.dirty) {
        this._query_RouterLink_97_0.reset(([] as any[]));
        this._RouterLinkActive_97_4.context.links = this._query_RouterLink_97_0;
        this._query_RouterLink_97_0.notifyOnChanges();
      }
      if (this._query_RouterLinkWithHref_97_1.dirty) {
        this._query_RouterLinkWithHref_97_1.reset([this._RouterLinkWithHref_97_3.context]);
        this._RouterLinkActive_97_4.context.linksWithHrefs = this._query_RouterLinkWithHref_97_1;
        this._query_RouterLinkWithHref_97_1.notifyOnChanges();
      }
      if (this._query_RouterLink_101_0.dirty) {
        this._query_RouterLink_101_0.reset(([] as any[]));
        this._RouterLinkActive_101_4.context.links = this._query_RouterLink_101_0;
        this._query_RouterLink_101_0.notifyOnChanges();
      }
      if (this._query_RouterLinkWithHref_101_1.dirty) {
        this._query_RouterLinkWithHref_101_1.reset([this._RouterLinkWithHref_101_3.context]);
        this._RouterLinkActive_101_4.context.linksWithHrefs = this._query_RouterLinkWithHref_101_1;
        this._query_RouterLinkWithHref_101_1.notifyOnChanges();
      }
      if (this._query_RouterLink_105_0.dirty) {
        this._query_RouterLink_105_0.reset(([] as any[]));
        this._RouterLinkActive_105_4.context.links = this._query_RouterLink_105_0;
        this._query_RouterLink_105_0.notifyOnChanges();
      }
      if (this._query_RouterLinkWithHref_105_1.dirty) {
        this._query_RouterLinkWithHref_105_1.reset([this._RouterLinkWithHref_105_3.context]);
        this._RouterLinkActive_105_4.context.linksWithHrefs = this._query_RouterLinkWithHref_105_1;
        this._query_RouterLinkWithHref_105_1.notifyOnChanges();
      }
      if (this._query_RouterLink_109_0.dirty) {
        this._query_RouterLink_109_0.reset(([] as any[]));
        this._RouterLinkActive_109_4.context.links = this._query_RouterLink_109_0;
        this._query_RouterLink_109_0.notifyOnChanges();
      }
      if (this._query_RouterLinkWithHref_109_1.dirty) {
        this._query_RouterLinkWithHref_109_1.reset([this._RouterLinkWithHref_109_3.context]);
        this._RouterLinkActive_109_4.context.linksWithHrefs = this._query_RouterLinkWithHref_109_1;
        this._query_RouterLinkWithHref_109_1.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._RouterLinkActive_12_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._RouterLinkActive_15_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._RouterLinkActive_18_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._RouterLinkActive_89_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._RouterLinkActive_93_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._RouterLinkActive_97_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._RouterLinkActive_101_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._RouterLinkActive_105_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._RouterLinkActive_109_4.context.ngAfterContentInit(); }
    }
    this._RouterLinkWithHref_12_3.checkHost(this,this,this._el_12,throwOnChange);
    this._RouterLinkWithHref_15_3.checkHost(this,this,this._el_15,throwOnChange);
    this._RouterLinkWithHref_18_3.checkHost(this,this,this._el_18,throwOnChange);
    this._RouterLinkWithHref_89_3.checkHost(this,this,this._el_89,throwOnChange);
    this._RouterLinkWithHref_93_3.checkHost(this,this,this._el_93,throwOnChange);
    this._RouterLinkWithHref_97_3.checkHost(this,this,this._el_97,throwOnChange);
    this._RouterLinkWithHref_101_3.checkHost(this,this,this._el_101,throwOnChange);
    this._RouterLinkWithHref_105_3.checkHost(this,this,this._el_105,throwOnChange);
    this._RouterLinkWithHref_109_3.checkHost(this,this,this._el_109,throwOnChange);
  }
  destroyInternal():void {
    this._RouterLinkWithHref_12_3.ngOnDestroy();
    this._RouterLinkActive_12_4.ngOnDestroy();
    this._RouterLinkWithHref_15_3.ngOnDestroy();
    this._RouterLinkActive_15_4.ngOnDestroy();
    this._RouterLinkWithHref_18_3.ngOnDestroy();
    this._RouterLinkActive_18_4.ngOnDestroy();
    this._RouterLinkWithHref_89_3.ngOnDestroy();
    this._RouterLinkActive_89_4.ngOnDestroy();
    this._RouterLinkWithHref_93_3.ngOnDestroy();
    this._RouterLinkActive_93_4.ngOnDestroy();
    this._RouterLinkWithHref_97_3.ngOnDestroy();
    this._RouterLinkActive_97_4.ngOnDestroy();
    this._RouterLinkWithHref_101_3.ngOnDestroy();
    this._RouterLinkActive_101_4.ngOnDestroy();
    this._RouterLinkWithHref_105_3.ngOnDestroy();
    this._RouterLinkActive_105_4.ngOnDestroy();
    this._RouterLinkWithHref_109_3.ngOnDestroy();
    this._RouterLinkActive_109_4.ngOnDestroy();
  }
  handleEvent_12(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._RouterLinkWithHref_12_3.handleEvent(eventName,$event) && result);
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.context.onSelect()) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_15(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._RouterLinkWithHref_15_3.handleEvent(eventName,$event) && result);
    return result;
  }
  handleEvent_18(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._RouterLinkWithHref_18_3.handleEvent(eventName,$event) && result);
    return result;
  }
  handleEvent_89(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._RouterLinkWithHref_89_3.handleEvent(eventName,$event) && result);
    return result;
  }
  handleEvent_93(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._RouterLinkWithHref_93_3.handleEvent(eventName,$event) && result);
    return result;
  }
  handleEvent_97(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._RouterLinkWithHref_97_3.handleEvent(eventName,$event) && result);
    return result;
  }
  handleEvent_101(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._RouterLinkWithHref_101_3.handleEvent(eventName,$event) && result);
    return result;
  }
  handleEvent_105(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._RouterLinkWithHref_105_3.handleEvent(eventName,$event) && result);
    return result;
  }
  handleEvent_109(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._RouterLinkWithHref_109_3.handleEvent(eventName,$event) && result);
    return result;
  }
}