/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

export const styles:any[] = ['.titlepage[_ngcontent-%COMP%]{\r\n  background-image:url(\'../images/Black_World_Banner.jpg\');\r\n  background-repeat:no-repeat;\r\n  color:white;\r\n}'];