/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from './privacy.component';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/view_utils';
import * as import4 from '@angular/core/src/metadata/view';
import * as import5 from '@angular/core/src/linker/view_type';
import * as import6 from '@angular/core/src/change_detection/constants';
import * as import7 from '@angular/core/src/linker/component_factory';
import * as import8 from './privacy.component.css.shim.ngstyle';
import * as import9 from './pagetitle.component';
import * as import10 from './pagetitle.component.ngfactory';
export class Wrapper_PrivacyComponent {
  /*private*/ _eventHandler:Function;
  context:import0.PrivacyComponent;
  /*private*/ _changed:boolean;
  constructor() {
    this._changed = false;
    this.context = new import0.PrivacyComponent();
  }
  ngOnDetach(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any):void {
  }
  ngOnDestroy():void {
  }
  ngDoCheck(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this._changed;
    this._changed = false;
    if (!throwOnChange) { if ((view.numberOfChecks === 0)) { this.context.ngOnInit(); } }
    return changed;
  }
  checkHost(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any,throwOnChange:boolean):void {
  }
  handleEvent(eventName:string,$event:any):boolean {
    var result:boolean = true;
    return result;
  }
  subscribe(view:import1.AppView<any>,_eventHandler:any):void {
    this._eventHandler = _eventHandler;
  }
}
var renderType_PrivacyComponent_Host:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.None,([] as any[]),{});
class View_PrivacyComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  compView_0:import1.AppView<import0.PrivacyComponent>;
  _PrivacyComponent_0_3:Wrapper_PrivacyComponent;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_PrivacyComponent_Host0,renderType_PrivacyComponent_Host,import5.ViewType.HOST,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.selectOrCreateRenderHostElement(this.renderer,'privacy',import3.EMPTY_INLINE_ARRAY,rootSelector,(null as any));
    this.compView_0 = new View_PrivacyComponent0(this.viewUtils,this,0,this._el_0);
    this._PrivacyComponent_0_3 = new Wrapper_PrivacyComponent();
    this.compView_0.create(this._PrivacyComponent_0_3.context);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return new import7.ComponentRef_<any>(0,this,this._el_0,this._PrivacyComponent_0_3.context);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.PrivacyComponent) && (0 === requestNodeIndex))) { return this._PrivacyComponent_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._PrivacyComponent_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this.compView_0.internalDetectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
export const PrivacyComponentNgFactory:import7.ComponentFactory<import0.PrivacyComponent> = new import7.ComponentFactory<import0.PrivacyComponent>('privacy',View_PrivacyComponent_Host0,import0.PrivacyComponent);
const styles_PrivacyComponent:any[] = [import8.styles];
var renderType_PrivacyComponent:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.Emulated,styles_PrivacyComponent,{});
export class View_PrivacyComponent0 extends import1.AppView<import0.PrivacyComponent> {
  _el_0:any;
  compView_0:import1.AppView<import9.PageTitleComponent>;
  _PageTitleComponent_0_3:import10.Wrapper_PageTitleComponent;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _text_6:any;
  _el_7:any;
  _text_8:any;
  _text_9:any;
  _el_10:any;
  _text_11:any;
  _text_12:any;
  _el_13:any;
  _text_14:any;
  _el_15:any;
  _text_16:any;
  _text_17:any;
  _text_18:any;
  _el_19:any;
  _text_20:any;
  _text_21:any;
  _el_22:any;
  _text_23:any;
  _text_24:any;
  _el_25:any;
  _text_26:any;
  _text_27:any;
  _el_28:any;
  _text_29:any;
  _text_30:any;
  _el_31:any;
  _text_32:any;
  _el_33:any;
  _text_34:any;
  _text_35:any;
  _text_36:any;
  _el_37:any;
  _text_38:any;
  _text_39:any;
  _el_40:any;
  _text_41:any;
  _text_42:any;
  _el_43:any;
  _text_44:any;
  _el_45:any;
  _text_46:any;
  _text_47:any;
  _text_48:any;
  _el_49:any;
  _text_50:any;
  _text_51:any;
  _el_52:any;
  _text_53:any;
  _el_54:any;
  _text_55:any;
  _text_56:any;
  _text_57:any;
  _el_58:any;
  _text_59:any;
  _text_60:any;
  _el_61:any;
  _text_62:any;
  _text_63:any;
  _el_64:any;
  _text_65:any;
  _text_66:any;
  _el_67:any;
  _text_68:any;
  _el_69:any;
  _text_70:any;
  _text_71:any;
  _text_72:any;
  _el_73:any;
  _text_74:any;
  _text_75:any;
  _el_76:any;
  _text_77:any;
  _text_78:any;
  _el_79:any;
  _text_80:any;
  _el_81:any;
  _text_82:any;
  _text_83:any;
  _text_84:any;
  _el_85:any;
  _text_86:any;
  _text_87:any;
  _el_88:any;
  _text_89:any;
  _el_90:any;
  _text_91:any;
  _text_92:any;
  _text_93:any;
  _el_94:any;
  _text_95:any;
  _el_96:any;
  _text_97:any;
  _text_98:any;
  _text_99:any;
  _el_100:any;
  _text_101:any;
  _text_102:any;
  _el_103:any;
  _text_104:any;
  _el_105:any;
  _text_106:any;
  _text_107:any;
  _text_108:any;
  _el_109:any;
  _text_110:any;
  _text_111:any;
  _text_112:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_PrivacyComponent0,renderType_PrivacyComponent,import5.ViewType.COMPONENT,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    const parentRenderNode:any = this.renderer.createViewRoot(this.parentElement);
    this._el_0 = import3.createRenderElement(this.renderer,parentRenderNode,'pagetitle',import3.EMPTY_INLINE_ARRAY,(null as any));
    this.compView_0 = new import10.View_PageTitleComponent0(this.viewUtils,this,0,this._el_0);
    this._PageTitleComponent_0_3 = new import10.Wrapper_PageTitleComponent();
    this.compView_0.create(this._PageTitleComponent_0_3.context);
    this._text_1 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,parentRenderNode,'div',new import3.InlineArray2(2,'class','container'),(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'\n  ',(null as any));
    this._el_4 = import3.createRenderElement(this.renderer,this._el_2,'h2',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_5 = this.renderer.createText(this._el_4,' Privacy Policy for I Buy As Is, Inc.',(null as any));
    this._text_6 = this.renderer.createText(this._el_2,'\n  ',(null as any));
    this._el_7 = import3.createRenderElement(this.renderer,this._el_2,'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_8 = this.renderer.createText(this._el_7,'At http://www.ibuyasis.com, one of our main priorities is the privacy of our visitors. This Privacy Policy document contains types of information that is collected and recorded by http://www.ibuyasis.com and how we use it.',(null as any));
    this._text_9 = this.renderer.createText(this._el_2,'\n  ',(null as any));
    this._el_10 = import3.createRenderElement(this.renderer,this._el_2,'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_11 = this.renderer.createText(this._el_10,'If you have additional questions or require more information about our Privacy Policy, do not hesitate to contact us through email at info@ibuyasis.com.',(null as any));
    this._text_12 = this.renderer.createText(this._el_2,'\n  ',(null as any));
    this._el_13 = import3.createRenderElement(this.renderer,this._el_2,'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_14 = this.renderer.createText(this._el_13,'\n    ',(null as any));
    this._el_15 = import3.createRenderElement(this.renderer,this._el_13,'strong',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_16 = this.renderer.createText(this._el_15,'Log Files',(null as any));
    this._text_17 = this.renderer.createText(this._el_13,'\n  ',(null as any));
    this._text_18 = this.renderer.createText(this._el_2,'\n  ',(null as any));
    this._el_19 = import3.createRenderElement(this.renderer,this._el_2,'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_20 = this.renderer.createText(this._el_19,'http://www.ibuyasis.com follows a standard procedure of using log files. These files log visitors when they visit websites. All hosting companies do this and a part of hosting services’ analytics. The information collected by log files include internet protocol (IP) addresses, browser type, Internet Service Provider (ISP), date and time stamp, referring/exit pages, and possibly the number of clicks. These are not linked to any information that is personally identifiable. The purpose of the information is for analyzing trends, administering the site, tracking users’ movement on the website, and gathering demographic information.',(null as any));
    this._text_21 = this.renderer.createText(this._el_2,'\n  ',(null as any));
    this._el_22 = import3.createRenderElement(this.renderer,this._el_2,'h3',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_23 = this.renderer.createText(this._el_22,'Cookies and Web Beacons',(null as any));
    this._text_24 = this.renderer.createText(this._el_2,'\n  ',(null as any));
    this._el_25 = import3.createRenderElement(this.renderer,this._el_2,'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_26 = this.renderer.createText(this._el_25,'Like any other website, http://www.ibuyasis.com uses ‘cookies’. These cookies are used to store information including visitors’ preferences, and the pages on the website that the visitor accessed or visited. The information is used to optimize the users’ experience by customizing our web page content based on visitors’ browser type and/or other information.',(null as any));
    this._text_27 = this.renderer.createText(this._el_2,'\n  ',(null as any));
    this._el_28 = import3.createRenderElement(this.renderer,this._el_2,'h3',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_29 = this.renderer.createText(this._el_28,'DoubleClick DART Cookie',(null as any));
    this._text_30 = this.renderer.createText(this._el_2,'\n  ',(null as any));
    this._el_31 = import3.createRenderElement(this.renderer,this._el_2,'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_32 = this.renderer.createText(this._el_31,'\n    Google is one of a third-party vendor on our site. It also uses cookies, known as DART cookies, to serve ads to our site visitors based upon their visit to www.website.com and other sites on the internet. However, visitors may choose to decline the use of DART cookies by visiting the Google ad and content network Privacy Policy at the following URL –\n    ',(null as any));
    this._el_33 = import3.createRenderElement(this.renderer,this._el_31,'a',new import3.InlineArray4(4,'href','http://www.google.com/privacy_ads.html','target','_blank'),(null as any));
    this._text_34 = this.renderer.createText(this._el_33,'http://www.google.com/privacy_ads.html',(null as any));
    this._text_35 = this.renderer.createText(this._el_31,'.\n  ',(null as any));
    this._text_36 = this.renderer.createText(this._el_2,'\n  ',(null as any));
    this._el_37 = import3.createRenderElement(this.renderer,this._el_2,'h3',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_38 = this.renderer.createText(this._el_37,'Our Advertising Partners',(null as any));
    this._text_39 = this.renderer.createText(this._el_2,'\n  ',(null as any));
    this._el_40 = import3.createRenderElement(this.renderer,this._el_2,'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_41 = this.renderer.createText(this._el_40,'Some of advertisers on our site may use cookies and web beacons. Our advertising partners include:',(null as any));
    this._text_42 = this.renderer.createText(this._el_2,'\n  ',(null as any));
    this._el_43 = import3.createRenderElement(this.renderer,this._el_2,'ul',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_44 = this.renderer.createText(this._el_43,'\n    ',(null as any));
    this._el_45 = import3.createRenderElement(this.renderer,this._el_43,'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_46 = this.renderer.createText(this._el_45,'Google',(null as any));
    this._text_47 = this.renderer.createText(this._el_43,'\n  ',(null as any));
    this._text_48 = this.renderer.createText(this._el_2,'\n  ',(null as any));
    this._el_49 = import3.createRenderElement(this.renderer,this._el_2,'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_50 = this.renderer.createText(this._el_49,'Each of our advertising partners has their own Privacy Policy for their website. For easier access, an updated and hyperlinked resource is maintained here:',(null as any));
    this._text_51 = this.renderer.createText(this._el_2,'\n  ',(null as any));
    this._el_52 = import3.createRenderElement(this.renderer,this._el_2,'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_53 = this.renderer.createText(this._el_52,'\n    ',(null as any));
    this._el_54 = import3.createRenderElement(this.renderer,this._el_52,'strong',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_55 = this.renderer.createText(this._el_54,'Privacy Policies',(null as any));
    this._text_56 = this.renderer.createText(this._el_52,'\n  ',(null as any));
    this._text_57 = this.renderer.createText(this._el_2,'\n  ',(null as any));
    this._el_58 = import3.createRenderElement(this.renderer,this._el_2,'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_59 = this.renderer.createText(this._el_58,'You may consult this list to find the Privacy Policy for each of the advertising partners of http://www.ibuyasis.com.',(null as any));
    this._text_60 = this.renderer.createText(this._el_2,'\n  ',(null as any));
    this._el_61 = import3.createRenderElement(this.renderer,this._el_2,'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_62 = this.renderer.createText(this._el_61,'Third-party ad servers or ad networks uses technologies like cookies, JavaScript, or Web Beacons that are used in their respective advertisements and links that appear on http://www.ibuyasis.com, which are sent directly to users’ browser. They automatically receive your IP address when this occurs. These technologies are used to measure the effectiveness of their advertising campaigns and/or to personalize the advertising content that you see on websites that you visit.',(null as any));
    this._text_63 = this.renderer.createText(this._el_2,'\n  ',(null as any));
    this._el_64 = import3.createRenderElement(this.renderer,this._el_2,'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_65 = this.renderer.createText(this._el_64,'Note that http://www.ibuyasis.com has no access to or control over these cookies that are used by third-party advertisers.',(null as any));
    this._text_66 = this.renderer.createText(this._el_2,'\n  ',(null as any));
    this._el_67 = import3.createRenderElement(this.renderer,this._el_2,'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_68 = this.renderer.createText(this._el_67,'\n    ',(null as any));
    this._el_69 = import3.createRenderElement(this.renderer,this._el_67,'strong',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_70 = this.renderer.createText(this._el_69,'Third Part Privacy Policies',(null as any));
    this._text_71 = this.renderer.createText(this._el_67,'\n  ',(null as any));
    this._text_72 = this.renderer.createText(this._el_2,'\n  ',(null as any));
    this._el_73 = import3.createRenderElement(this.renderer,this._el_2,'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_74 = this.renderer.createText(this._el_73,'http://www.ibuyasis.com’s Privacy Policy does not apply to other advertisers or websites. Thus, we are advising you to consult the respective Privacy Policies of these third-party ad servers for more detailed information. It may include their practices and instructions about how to opt-out of certain options. You may find a complete list of these Privacy Policies and their links here: Privacy Policy Links.',(null as any));
    this._text_75 = this.renderer.createText(this._el_2,'\n  ',(null as any));
    this._el_76 = import3.createRenderElement(this.renderer,this._el_2,'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_77 = this.renderer.createText(this._el_76,'You can choose to disable cookies through your individual browser options. To know more detailed information about cookie management with specific web browsers, it can be found at the browsers’ respective websites. What Are Cookies?',(null as any));
    this._text_78 = this.renderer.createText(this._el_2,'\n  ',(null as any));
    this._el_79 = import3.createRenderElement(this.renderer,this._el_2,'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_80 = this.renderer.createText(this._el_79,'\n    ',(null as any));
    this._el_81 = import3.createRenderElement(this.renderer,this._el_79,'strong',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_82 = this.renderer.createText(this._el_81,'Children’s Information',(null as any));
    this._text_83 = this.renderer.createText(this._el_79,'\n  ',(null as any));
    this._text_84 = this.renderer.createText(this._el_2,'\n  ',(null as any));
    this._el_85 = import3.createRenderElement(this.renderer,this._el_2,'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_86 = this.renderer.createText(this._el_85,'Another part of our priority is adding protection for children while using the internet. We encourage parents and guardians to observe, participate in, and/or monitor and guide their online activity.',(null as any));
    this._text_87 = this.renderer.createText(this._el_2,'\n  ',(null as any));
    this._el_88 = import3.createRenderElement(this.renderer,this._el_2,'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_89 = this.renderer.createText(this._el_88,'\n    http://www.ibuyasis.com does not knowingly collect any Personal Identifiable Information from children under the age of 13. If you think that your child provided this kind of information on\n    ',(null as any));
    this._el_90 = import3.createRenderElement(this.renderer,this._el_88,'a',new import3.InlineArray4(4,'href','https://buywebsitetrafficreviews.org/trafficwebsites/','target','_blank'),(null as any));
    this._text_91 = this.renderer.createText(this._el_90,'our website',(null as any));
    this._text_92 = this.renderer.createText(this._el_88,', we strongly encourage you to contact us immediately and we will do our best efforts to promptly remove such information from our records.\n  ',(null as any));
    this._text_93 = this.renderer.createText(this._el_2,'\n  ',(null as any));
    this._el_94 = import3.createRenderElement(this.renderer,this._el_2,'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_95 = this.renderer.createText(this._el_94,'\n    ',(null as any));
    this._el_96 = import3.createRenderElement(this.renderer,this._el_94,'strong',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_97 = this.renderer.createText(this._el_96,'Online Privacy Policy Only',(null as any));
    this._text_98 = this.renderer.createText(this._el_94,'\n  ',(null as any));
    this._text_99 = this.renderer.createText(this._el_2,'\n  ',(null as any));
    this._el_100 = import3.createRenderElement(this.renderer,this._el_2,'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_101 = this.renderer.createText(this._el_100,'This privacy policy applies only to our online activities and is valid for visitors to our website with regards to the information that they shared and/or collect in http://www.ibuyasis.com. This policy is not applicable to any information collected offline or via channels other than this website.',(null as any));
    this._text_102 = this.renderer.createText(this._el_2,'\n  ',(null as any));
    this._el_103 = import3.createRenderElement(this.renderer,this._el_2,'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_104 = this.renderer.createText(this._el_103,'\n    ',(null as any));
    this._el_105 = import3.createRenderElement(this.renderer,this._el_103,'strong',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_106 = this.renderer.createText(this._el_105,'Consent',(null as any));
    this._text_107 = this.renderer.createText(this._el_103,'\n  ',(null as any));
    this._text_108 = this.renderer.createText(this._el_2,'\n  ',(null as any));
    this._el_109 = import3.createRenderElement(this.renderer,this._el_2,'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_110 = this.renderer.createText(this._el_109,'By using our website, you hereby consent to our Privacy Policy and agree to its Terms and Conditions.',(null as any));
    this._text_111 = this.renderer.createText(this._el_2,'\n  ',(null as any));
    this._text_112 = this.renderer.createText(this._el_2,'\n',(null as any));
    this.init((null as any),((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._text_6,
      this._el_7,
      this._text_8,
      this._text_9,
      this._el_10,
      this._text_11,
      this._text_12,
      this._el_13,
      this._text_14,
      this._el_15,
      this._text_16,
      this._text_17,
      this._text_18,
      this._el_19,
      this._text_20,
      this._text_21,
      this._el_22,
      this._text_23,
      this._text_24,
      this._el_25,
      this._text_26,
      this._text_27,
      this._el_28,
      this._text_29,
      this._text_30,
      this._el_31,
      this._text_32,
      this._el_33,
      this._text_34,
      this._text_35,
      this._text_36,
      this._el_37,
      this._text_38,
      this._text_39,
      this._el_40,
      this._text_41,
      this._text_42,
      this._el_43,
      this._text_44,
      this._el_45,
      this._text_46,
      this._text_47,
      this._text_48,
      this._el_49,
      this._text_50,
      this._text_51,
      this._el_52,
      this._text_53,
      this._el_54,
      this._text_55,
      this._text_56,
      this._text_57,
      this._el_58,
      this._text_59,
      this._text_60,
      this._el_61,
      this._text_62,
      this._text_63,
      this._el_64,
      this._text_65,
      this._text_66,
      this._el_67,
      this._text_68,
      this._el_69,
      this._text_70,
      this._text_71,
      this._text_72,
      this._el_73,
      this._text_74,
      this._text_75,
      this._el_76,
      this._text_77,
      this._text_78,
      this._el_79,
      this._text_80,
      this._el_81,
      this._text_82,
      this._text_83,
      this._text_84,
      this._el_85,
      this._text_86,
      this._text_87,
      this._el_88,
      this._text_89,
      this._el_90,
      this._text_91,
      this._text_92,
      this._text_93,
      this._el_94,
      this._text_95,
      this._el_96,
      this._text_97,
      this._text_98,
      this._text_99,
      this._el_100,
      this._text_101,
      this._text_102,
      this._el_103,
      this._text_104,
      this._el_105,
      this._text_106,
      this._text_107,
      this._text_108,
      this._el_109,
      this._text_110,
      this._text_111,
      this._text_112
    ]
    ),(null as any));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import9.PageTitleComponent) && (0 === requestNodeIndex))) { return this._PageTitleComponent_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_0_0_0:any = this.context.title;
    this._PageTitleComponent_0_3.check_title(currVal_0_0_0,throwOnChange,false);
    this._PageTitleComponent_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this.compView_0.internalDetectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
  }
}