/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

export const styles:any[] = ['.propertysummary[_ngcontent-%COMP%] {\r\n  \r\n  background-color: aliceblue;\r\n  border: 0px solid #000000;\r\n  \r\n  \r\n  \r\n  -webkit-box-shadow: 10px 10px 5px 0px rgba(0,0,0,0.75);\r\n  -moz-box-shadow: 10px 10px 5px 0px rgba(0,0,0,0.75);\r\n  box-shadow: 10px 10px 5px 0px rgba(0,0,0,0.75);\r\n}\r\n\r\n  .propertysummary[_ngcontent-%COMP%]   h2[_ngcontent-%COMP%] {\r\n    color: black;\r\n  }\r\n\r\n  .propertysummary[_ngcontent-%COMP%]   h3[_ngcontent-%COMP%] {\r\n    color: blue;\r\n    border-top: 1px solid #000;\r\n    border-bottom: 1px solid #000;\r\n  }\r\n\r\n  .propertysummary[_ngcontent-%COMP%]   h4[_ngcontent-%COMP%] {\r\n    color: black;\r\n    text-decoration: underline;\r\n    font-size: smaller;\r\n  }\r\n\r\n  .propertysummary[_ngcontent-%COMP%]   img[_ngcontent-%COMP%] {\r\n    margin-top: 5px;\r\n  }\r\n\r\n  .propertysummary[_ngcontent-%COMP%]   about[_ngcontent-%COMP%] {\r\n    text-align: justify;\r\n    font-style: italic;\r\n  }'];