/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from './sellyourhome.component';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/view_utils';
import * as import4 from '@angular/core/src/metadata/view';
import * as import5 from '@angular/core/src/linker/view_type';
import * as import6 from '@angular/core/src/change_detection/constants';
import * as import7 from '@angular/core/src/linker/component_factory';
import * as import8 from './pagetitle.component';
import * as import9 from './pagetitle.component.ngfactory';
export class Wrapper_SellYourHomeComponent {
  /*private*/ _eventHandler:Function;
  context:import0.SellYourHomeComponent;
  /*private*/ _changed:boolean;
  constructor() {
    this._changed = false;
    this.context = new import0.SellYourHomeComponent();
  }
  ngOnDetach(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any):void {
  }
  ngOnDestroy():void {
  }
  ngDoCheck(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this._changed;
    this._changed = false;
    if (!throwOnChange) { if ((view.numberOfChecks === 0)) { this.context.ngOnInit(); } }
    return changed;
  }
  checkHost(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any,throwOnChange:boolean):void {
  }
  handleEvent(eventName:string,$event:any):boolean {
    var result:boolean = true;
    return result;
  }
  subscribe(view:import1.AppView<any>,_eventHandler:any):void {
    this._eventHandler = _eventHandler;
  }
}
var renderType_SellYourHomeComponent_Host:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.None,([] as any[]),{});
class View_SellYourHomeComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  compView_0:import1.AppView<import0.SellYourHomeComponent>;
  _SellYourHomeComponent_0_3:Wrapper_SellYourHomeComponent;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_SellYourHomeComponent_Host0,renderType_SellYourHomeComponent_Host,import5.ViewType.HOST,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.selectOrCreateRenderHostElement(this.renderer,'sellyourhome',import3.EMPTY_INLINE_ARRAY,rootSelector,(null as any));
    this.compView_0 = new View_SellYourHomeComponent0(this.viewUtils,this,0,this._el_0);
    this._SellYourHomeComponent_0_3 = new Wrapper_SellYourHomeComponent();
    this.compView_0.create(this._SellYourHomeComponent_0_3.context);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return new import7.ComponentRef_<any>(0,this,this._el_0,this._SellYourHomeComponent_0_3.context);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.SellYourHomeComponent) && (0 === requestNodeIndex))) { return this._SellYourHomeComponent_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._SellYourHomeComponent_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this.compView_0.internalDetectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
export const SellYourHomeComponentNgFactory:import7.ComponentFactory<import0.SellYourHomeComponent> = new import7.ComponentFactory<import0.SellYourHomeComponent>('sellyourhome',View_SellYourHomeComponent_Host0,import0.SellYourHomeComponent);
const styles_SellYourHomeComponent:any[] = ([] as any[]);
var renderType_SellYourHomeComponent:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.None,styles_SellYourHomeComponent,{});
export class View_SellYourHomeComponent0 extends import1.AppView<import0.SellYourHomeComponent> {
  _el_0:any;
  compView_0:import1.AppView<import8.PageTitleComponent>;
  _PageTitleComponent_0_3:import9.Wrapper_PageTitleComponent;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _text_6:any;
  _el_7:any;
  _text_8:any;
  _text_9:any;
  _el_10:any;
  _text_11:any;
  _text_12:any;
  _el_13:any;
  _text_14:any;
  _text_15:any;
  _el_16:any;
  _text_17:any;
  _text_18:any;
  _el_19:any;
  _text_20:any;
  _text_21:any;
  _el_22:any;
  _text_23:any;
  _text_24:any;
  _el_25:any;
  _text_26:any;
  _text_27:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_SellYourHomeComponent0,renderType_SellYourHomeComponent,import5.ViewType.COMPONENT,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    const parentRenderNode:any = this.renderer.createViewRoot(this.parentElement);
    this._el_0 = import3.createRenderElement(this.renderer,parentRenderNode,'pagetitle',import3.EMPTY_INLINE_ARRAY,(null as any));
    this.compView_0 = new import9.View_PageTitleComponent0(this.viewUtils,this,0,this._el_0);
    this._PageTitleComponent_0_3 = new import9.Wrapper_PageTitleComponent();
    this.compView_0.create(this._PageTitleComponent_0_3.context);
    this._text_1 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,parentRenderNode,'div',new import3.InlineArray2(2,'class','container'),(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'\n  ',(null as any));
    this._el_4 = import3.createRenderElement(this.renderer,this._el_2,'h2',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_5 = this.renderer.createText(this._el_4,'Selling Your Home? ',(null as any));
    this._text_6 = this.renderer.createText(this._el_2,'\n  ',(null as any));
    this._el_7 = import3.createRenderElement(this.renderer,this._el_2,'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_8 = this.renderer.createText(this._el_7,'Do you need to sell your home in the next 60 days? We can make this possible! No matter the situation we are here to help. After receiving your information, we can make you a cash offer within 24-48 hours. If the offer is agreed upon we can close quickly with no commission or closing costs to you. By speaking with our local real estate professionals, you are granted the opportunity to sell your home with no additional costs. We have over 45 combined years of experience in real estate. By submitting your information we are able to more accurately calculate a cash offer for you by compiling the proper research on your property. ',(null as any));
    this._text_9 = this.renderer.createText(this._el_2,'\n\n  ',(null as any));
    this._el_10 = import3.createRenderElement(this.renderer,this._el_2,'h3',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_11 = this.renderer.createText(this._el_10,'Sell home as is!',(null as any));
    this._text_12 = this.renderer.createText(this._el_2,'\n  ',(null as any));
    this._el_13 = import3.createRenderElement(this.renderer,this._el_2,'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_14 = this.renderer.createText(this._el_13,'We will buy your house for cash offer now! Your home gets our immediate attention. We work diligently to buy house and insure that you sell home as is, so that every cash offer transaction goes smoothly and that you are kept informed throughout the numerous steps involved in selling your house.',(null as any));
    this._text_15 = this.renderer.createText(this._el_2,'\n  ',(null as any));
    this._el_16 = import3.createRenderElement(this.renderer,this._el_2,'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_17 = this.renderer.createText(this._el_16,'Since we are private investors and not realtors we buy houses for cash, you pay no fees or commissions and you sell home as is.',(null as any));
    this._text_18 = this.renderer.createText(this._el_2,'\n  ',(null as any));
    this._el_19 = import3.createRenderElement(this.renderer,this._el_2,'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_20 = this.renderer.createText(this._el_19,'When you do business with I\'ll Buy Any House, you will find us knowledgeable and helpful, and we will answer all questions honestly and truthfully about selling home fast. We have several different options to help relieve you of selling house that has become a financial burden and put you and your family on the road to relief.',(null as any));
    this._text_21 = this.renderer.createText(this._el_2,'\n  ',(null as any));
    this._el_22 = import3.createRenderElement(this.renderer,this._el_2,'h3',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_23 = this.renderer.createText(this._el_22,'Call us today',(null as any));
    this._text_24 = this.renderer.createText(this._el_2,'\n\n  ',(null as any));
    this._el_25 = import3.createRenderElement(this.renderer,this._el_2,'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_26 = this.renderer.createText(this._el_25,'(813) 444-4567 or just go to the contact page and fill out the form, so we can call back and talk to you about selling your house after we do our due diligence so we can advise you how you can sell home fast.',(null as any));
    this._text_27 = this.renderer.createText(this._el_2,'\n\n',(null as any));
    this.init((null as any),((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._text_6,
      this._el_7,
      this._text_8,
      this._text_9,
      this._el_10,
      this._text_11,
      this._text_12,
      this._el_13,
      this._text_14,
      this._text_15,
      this._el_16,
      this._text_17,
      this._text_18,
      this._el_19,
      this._text_20,
      this._text_21,
      this._el_22,
      this._text_23,
      this._text_24,
      this._el_25,
      this._text_26,
      this._text_27
    ]
    ),(null as any));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import8.PageTitleComponent) && (0 === requestNodeIndex))) { return this._PageTitleComponent_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_0_0_0:any = this.context.title;
    this._PageTitleComponent_0_3.check_title(currVal_0_0_0,throwOnChange,false);
    this._PageTitleComponent_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this.compView_0.internalDetectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
  }
}