/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from './teammember.component';
import * as import1 from '@angular/core/src/change_detection/change_detection_util';
import * as import2 from '@angular/core/src/linker/view';
import * as import3 from '@angular/core/src/linker/view_utils';
import * as import4 from '@angular/core/src/render/api';
import * as import5 from '@angular/core/src/metadata/view';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/constants';
import * as import8 from '@angular/core/src/linker/component_factory';
import * as import9 from './team.service';
import * as import10 from '@angular/router/src/router_state';
import * as import11 from '@angular/common/src/location/location';
import * as import12 from './teammember.component.css.shim.ngstyle';
import * as import13 from '@angular/core/src/security';
export class Wrapper_TeammemberComponent {
  /*private*/ _eventHandler:Function;
  context:import0.TeammemberComponent;
  /*private*/ _changed:boolean;
  /*private*/ _expr_0:any;
  constructor(p0:any,p1:any,p2:any) {
    this._changed = false;
    this.context = new import0.TeammemberComponent(p0,p1,p2);
    this._expr_0 = import1.UNINITIALIZED;
  }
  ngOnDetach(view:import2.AppView<any>,componentView:import2.AppView<any>,el:any):void {
  }
  ngOnDestroy():void {
  }
  check_teammember(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_0,currValue))) {
      this._changed = true;
      this.context.teammember = currValue;
      this._expr_0 = currValue;
    }
  }
  ngDoCheck(view:import2.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this._changed;
    this._changed = false;
    if (!throwOnChange) { if ((view.numberOfChecks === 0)) { this.context.ngOnInit(); } }
    return changed;
  }
  checkHost(view:import2.AppView<any>,componentView:import2.AppView<any>,el:any,throwOnChange:boolean):void {
  }
  handleEvent(eventName:string,$event:any):boolean {
    var result:boolean = true;
    return result;
  }
  subscribe(view:import2.AppView<any>,_eventHandler:any):void {
    this._eventHandler = _eventHandler;
  }
}
var renderType_TeammemberComponent_Host:import4.RenderComponentType = import3.createRenderComponentType('',0,import5.ViewEncapsulation.None,([] as any[]),{});
class View_TeammemberComponent_Host0 extends import2.AppView<any> {
  _el_0:any;
  compView_0:import2.AppView<import0.TeammemberComponent>;
  _TeammemberComponent_0_3:Wrapper_TeammemberComponent;
  constructor(viewUtils:import3.ViewUtils,parentView:import2.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_TeammemberComponent_Host0,renderType_TeammemberComponent_Host,import6.ViewType.HOST,viewUtils,parentView,parentIndex,parentElement,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import8.ComponentRef<any> {
    this._el_0 = import3.selectOrCreateRenderHostElement(this.renderer,'teammember',import3.EMPTY_INLINE_ARRAY,rootSelector,(null as any));
    this.compView_0 = new View_TeammemberComponent0(this.viewUtils,this,0,this._el_0);
    this._TeammemberComponent_0_3 = new Wrapper_TeammemberComponent(this.injectorGet(import9.TeamService,this.parentIndex),this.injectorGet(import10.ActivatedRoute,this.parentIndex),this.injectorGet(import11.Location,this.parentIndex));
    this.compView_0.create(this._TeammemberComponent_0_3.context);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return new import8.ComponentRef_<any>(0,this,this._el_0,this._TeammemberComponent_0_3.context);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.TeammemberComponent) && (0 === requestNodeIndex))) { return this._TeammemberComponent_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._TeammemberComponent_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this.compView_0.internalDetectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
export const TeammemberComponentNgFactory:import8.ComponentFactory<import0.TeammemberComponent> = new import8.ComponentFactory<import0.TeammemberComponent>('teammember',View_TeammemberComponent_Host0,import0.TeammemberComponent);
const styles_TeammemberComponent:any[] = [import12.styles];
var renderType_TeammemberComponent:import4.RenderComponentType = import3.createRenderComponentType('',0,import5.ViewEncapsulation.Emulated,styles_TeammemberComponent,{});
export class View_TeammemberComponent0 extends import2.AppView<import0.TeammemberComponent> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _el_6:any;
  _text_7:any;
  _text_8:any;
  _el_9:any;
  _text_10:any;
  _el_11:any;
  _text_12:any;
  _text_13:any;
  _el_14:any;
  _text_15:any;
  _text_16:any;
  _el_17:any;
  _text_18:any;
  _el_19:any;
  _text_20:any;
  _el_21:any;
  _text_22:any;
  _text_23:any;
  _el_24:any;
  _text_25:any;
  _text_26:any;
  _text_27:any;
  _el_28:any;
  _text_29:any;
  _el_30:any;
  _text_31:any;
  _text_32:any;
  _el_33:any;
  _text_34:any;
  _text_35:any;
  _text_36:any;
  _text_37:any;
  _text_38:any;
  _text_39:any;
  _el_40:any;
  _text_41:any;
  _el_42:any;
  _text_43:any;
  _el_44:any;
  _text_45:any;
  _text_46:any;
  _el_47:any;
  _text_48:any;
  _text_49:any;
  _text_50:any;
  _text_51:any;
  _text_52:any;
  _el_53:any;
  _text_54:any;
  _el_55:any;
  /*private*/ _expr_56:any;
  /*private*/ _expr_57:any;
  /*private*/ _expr_58:any;
  /*private*/ _expr_59:any;
  /*private*/ _expr_60:any;
  /*private*/ _expr_61:any;
  /*private*/ _expr_62:any;
  /*private*/ _expr_63:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import2.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_TeammemberComponent0,renderType_TeammemberComponent,import6.ViewType.COMPONENT,viewUtils,parentView,parentIndex,parentElement,import7.ChangeDetectorStatus.CheckAlways);
    this._expr_56 = import1.UNINITIALIZED;
    this._expr_57 = import1.UNINITIALIZED;
    this._expr_58 = import1.UNINITIALIZED;
    this._expr_59 = import1.UNINITIALIZED;
    this._expr_60 = import1.UNINITIALIZED;
    this._expr_61 = import1.UNINITIALIZED;
    this._expr_62 = import1.UNINITIALIZED;
    this._expr_63 = import1.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import8.ComponentRef<any> {
    const parentRenderNode:any = this.renderer.createViewRoot(this.parentElement);
    this._el_0 = import3.createRenderElement(this.renderer,parentRenderNode,'div',new import3.InlineArray2(2,'class','teammember col-xs-12'),(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n  ',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,this._el_0,'div',new import3.InlineArray2(2,'class','row'),(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'\n    ',(null as any));
    this._el_4 = import3.createRenderElement(this.renderer,this._el_2,'div',new import3.InlineArray2(2,'class','col-xs-12 col-sm-3'),(null as any));
    this._text_5 = this.renderer.createText(this._el_4,'\n      ',(null as any));
    this._el_6 = import3.createRenderElement(this.renderer,this._el_4,'img',new import3.InlineArray2(2,'class','col-xs-12'),(null as any));
    this._text_7 = this.renderer.createText(this._el_4,'\n    ',(null as any));
    this._text_8 = this.renderer.createText(this._el_2,'\n    ',(null as any));
    this._el_9 = import3.createRenderElement(this.renderer,this._el_2,'div',new import3.InlineArray2(2,'class','col-xs-12 col-sm-9'),(null as any));
    this._text_10 = this.renderer.createText(this._el_9,'\n      ',(null as any));
    this._el_11 = import3.createRenderElement(this.renderer,this._el_9,'h2',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_12 = this.renderer.createText(this._el_11,'',(null as any));
    this._text_13 = this.renderer.createText(this._el_9,'\n      ',(null as any));
    this._el_14 = import3.createRenderElement(this.renderer,this._el_9,'h3',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_15 = this.renderer.createText(this._el_14,'',(null as any));
    this._text_16 = this.renderer.createText(this._el_9,'\n      ',(null as any));
    this._el_17 = import3.createRenderElement(this.renderer,this._el_9,'div',new import3.InlineArray2(2,'class','row'),(null as any));
    this._text_18 = this.renderer.createText(this._el_17,'\n        ',(null as any));
    this._el_19 = import3.createRenderElement(this.renderer,this._el_17,'div',new import3.InlineArray2(2,'class','col-xs-12 col-sm-6'),(null as any));
    this._text_20 = this.renderer.createText(this._el_19,'\n          ',(null as any));
    this._el_21 = import3.createRenderElement(this.renderer,this._el_19,'h4',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_22 = this.renderer.createText(this._el_21,'Passions',(null as any));
    this._text_23 = this.renderer.createText(this._el_19,'',(null as any));
    this._el_24 = import3.createRenderElement(this.renderer,this._el_19,'h4',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_25 = this.renderer.createText(this._el_24,'Region',(null as any));
    this._text_26 = this.renderer.createText(this._el_19,'',(null as any));
    this._text_27 = this.renderer.createText(this._el_17,'\n        ',(null as any));
    this._el_28 = import3.createRenderElement(this.renderer,this._el_17,'div',new import3.InlineArray2(2,'class','col-xs-12 col-sm-6'),(null as any));
    this._text_29 = this.renderer.createText(this._el_28,'\n          ',(null as any));
    this._el_30 = import3.createRenderElement(this.renderer,this._el_28,'h4',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_31 = this.renderer.createText(this._el_30,'Motto',(null as any));
    this._text_32 = this.renderer.createText(this._el_28,'',(null as any));
    this._el_33 = import3.createRenderElement(this.renderer,this._el_28,'h4',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_34 = this.renderer.createText(this._el_33,'Favorite Quote',(null as any));
    this._text_35 = this.renderer.createText(this._el_28,'',(null as any));
    this._text_36 = this.renderer.createText(this._el_17,'\n      ',(null as any));
    this._text_37 = this.renderer.createText(this._el_9,'\n    ',(null as any));
    this._text_38 = this.renderer.createText(this._el_2,'\n  ',(null as any));
    this._text_39 = this.renderer.createText(this._el_0,'\n  ',(null as any));
    this._el_40 = import3.createRenderElement(this.renderer,this._el_0,'div',new import3.InlineArray2(2,'class','row'),(null as any));
    this._text_41 = this.renderer.createText(this._el_40,'\n    ',(null as any));
    this._el_42 = import3.createRenderElement(this.renderer,this._el_40,'div',new import3.InlineArray2(2,'class','col-xs-12'),(null as any));
    this._text_43 = this.renderer.createText(this._el_42,'\n      ',(null as any));
    this._el_44 = import3.createRenderElement(this.renderer,this._el_42,'h4',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_45 = this.renderer.createText(this._el_44,'About',(null as any));
    this._text_46 = this.renderer.createText(this._el_42,'\n      ',(null as any));
    this._el_47 = import3.createRenderElement(this.renderer,this._el_42,'p',new import3.InlineArray2(2,'class','about'),(null as any));
    this._text_48 = this.renderer.createText(this._el_47,'',(null as any));
    this._text_49 = this.renderer.createText(this._el_42,'\n    ',(null as any));
    this._text_50 = this.renderer.createText(this._el_40,'\n  ',(null as any));
    this._text_51 = this.renderer.createText(this._el_0,'\n \n',(null as any));
    this._text_52 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._el_53 = import3.createRenderElement(this.renderer,parentRenderNode,'div',new import3.InlineArray2(2,'class','clearfix'),(null as any));
    this._text_54 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._el_55 = import3.createRenderElement(this.renderer,parentRenderNode,'br',import3.EMPTY_INLINE_ARRAY,(null as any));
    this.init((null as any),((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._el_11,
      this._text_12,
      this._text_13,
      this._el_14,
      this._text_15,
      this._text_16,
      this._el_17,
      this._text_18,
      this._el_19,
      this._text_20,
      this._el_21,
      this._text_22,
      this._text_23,
      this._el_24,
      this._text_25,
      this._text_26,
      this._text_27,
      this._el_28,
      this._text_29,
      this._el_30,
      this._text_31,
      this._text_32,
      this._el_33,
      this._text_34,
      this._text_35,
      this._text_36,
      this._text_37,
      this._text_38,
      this._text_39,
      this._el_40,
      this._text_41,
      this._el_42,
      this._text_43,
      this._el_44,
      this._text_45,
      this._text_46,
      this._el_47,
      this._text_48,
      this._text_49,
      this._text_50,
      this._text_51,
      this._text_52,
      this._el_53,
      this._text_54,
      this._el_55
    ]
    ),(null as any));
    return (null as any);
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_56:any = import3.inlineInterpolate(1,'../images/',this.context.teammember.image,'');
    if (import3.checkBinding(throwOnChange,this._expr_56,currVal_56)) {
      this.renderer.setElementProperty(this._el_6,'src',this.viewUtils.sanitizer.sanitize(import13.SecurityContext.URL,currVal_56));
      this._expr_56 = currVal_56;
    }
    const currVal_57:any = import3.inlineInterpolate(1,'',this.context.teammember.name,'');
    if (import3.checkBinding(throwOnChange,this._expr_57,currVal_57)) {
      this.renderer.setText(this._text_12,currVal_57);
      this._expr_57 = currVal_57;
    }
    const currVal_58:any = import3.inlineInterpolate(1,'',this.context.teammember.title,'');
    if (import3.checkBinding(throwOnChange,this._expr_58,currVal_58)) {
      this.renderer.setText(this._text_15,currVal_58);
      this._expr_58 = currVal_58;
    }
    const currVal_59:any = import3.inlineInterpolate(1,'\n          ',this.context.teammember.passions,'\n          ');
    if (import3.checkBinding(throwOnChange,this._expr_59,currVal_59)) {
      this.renderer.setText(this._text_23,currVal_59);
      this._expr_59 = currVal_59;
    }
    const currVal_60:any = import3.inlineInterpolate(1,'\n          ',this.context.teammember.region,'\n        ');
    if (import3.checkBinding(throwOnChange,this._expr_60,currVal_60)) {
      this.renderer.setText(this._text_26,currVal_60);
      this._expr_60 = currVal_60;
    }
    const currVal_61:any = import3.inlineInterpolate(1,'\n          ',this.context.teammember.moto,'\n          ');
    if (import3.checkBinding(throwOnChange,this._expr_61,currVal_61)) {
      this.renderer.setText(this._text_32,currVal_61);
      this._expr_61 = currVal_61;
    }
    const currVal_62:any = import3.inlineInterpolate(1,'\n          ',this.context.teammember.quote,'\n        ');
    if (import3.checkBinding(throwOnChange,this._expr_62,currVal_62)) {
      this.renderer.setText(this._text_35,currVal_62);
      this._expr_62 = currVal_62;
    }
    const currVal_63:any = import3.inlineInterpolate(1,'',this.context.teammember.about,'');
    if (import3.checkBinding(throwOnChange,this._expr_63,currVal_63)) {
      this.renderer.setText(this._text_48,currVal_63);
      this._expr_63 = currVal_63;
    }
  }
}