/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from './terms.component';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/view_utils';
import * as import4 from '@angular/core/src/metadata/view';
import * as import5 from '@angular/core/src/linker/view_type';
import * as import6 from '@angular/core/src/change_detection/constants';
import * as import7 from '@angular/core/src/linker/component_factory';
import * as import8 from './terms.component.css.shim.ngstyle';
import * as import9 from './pagetitle.component';
import * as import10 from './pagetitle.component.ngfactory';
export class Wrapper_TermsComponent {
  /*private*/ _eventHandler:Function;
  context:import0.TermsComponent;
  /*private*/ _changed:boolean;
  constructor() {
    this._changed = false;
    this.context = new import0.TermsComponent();
  }
  ngOnDetach(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any):void {
  }
  ngOnDestroy():void {
  }
  ngDoCheck(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this._changed;
    this._changed = false;
    if (!throwOnChange) { if ((view.numberOfChecks === 0)) { this.context.ngOnInit(); } }
    return changed;
  }
  checkHost(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any,throwOnChange:boolean):void {
  }
  handleEvent(eventName:string,$event:any):boolean {
    var result:boolean = true;
    return result;
  }
  subscribe(view:import1.AppView<any>,_eventHandler:any):void {
    this._eventHandler = _eventHandler;
  }
}
var renderType_TermsComponent_Host:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.None,([] as any[]),{});
class View_TermsComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  compView_0:import1.AppView<import0.TermsComponent>;
  _TermsComponent_0_3:Wrapper_TermsComponent;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_TermsComponent_Host0,renderType_TermsComponent_Host,import5.ViewType.HOST,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.selectOrCreateRenderHostElement(this.renderer,'terms',import3.EMPTY_INLINE_ARRAY,rootSelector,(null as any));
    this.compView_0 = new View_TermsComponent0(this.viewUtils,this,0,this._el_0);
    this._TermsComponent_0_3 = new Wrapper_TermsComponent();
    this.compView_0.create(this._TermsComponent_0_3.context);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return new import7.ComponentRef_<any>(0,this,this._el_0,this._TermsComponent_0_3.context);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.TermsComponent) && (0 === requestNodeIndex))) { return this._TermsComponent_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._TermsComponent_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this.compView_0.internalDetectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
export const TermsComponentNgFactory:import7.ComponentFactory<import0.TermsComponent> = new import7.ComponentFactory<import0.TermsComponent>('terms',View_TermsComponent_Host0,import0.TermsComponent);
const styles_TermsComponent:any[] = [import8.styles];
var renderType_TermsComponent:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.Emulated,styles_TermsComponent,{});
export class View_TermsComponent0 extends import1.AppView<import0.TermsComponent> {
  _el_0:any;
  compView_0:import1.AppView<import9.PageTitleComponent>;
  _PageTitleComponent_0_3:import10.Wrapper_PageTitleComponent;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _el_6:any;
  _text_7:any;
  _text_8:any;
  _text_9:any;
  _el_10:any;
  _text_11:any;
  _el_12:any;
  _text_13:any;
  _text_14:any;
  _text_15:any;
  _el_16:any;
  _text_17:any;
  _text_18:any;
  _el_19:any;
  _text_20:any;
  _el_21:any;
  _text_22:any;
  _text_23:any;
  _text_24:any;
  _el_25:any;
  _text_26:any;
  _text_27:any;
  _el_28:any;
  _text_29:any;
  _el_30:any;
  _text_31:any;
  _text_32:any;
  _text_33:any;
  _el_34:any;
  _text_35:any;
  _text_36:any;
  _el_37:any;
  _text_38:any;
  _el_39:any;
  _text_40:any;
  _text_41:any;
  _text_42:any;
  _el_43:any;
  _text_44:any;
  _text_45:any;
  _el_46:any;
  _text_47:any;
  _el_48:any;
  _text_49:any;
  _text_50:any;
  _text_51:any;
  _el_52:any;
  _text_53:any;
  _text_54:any;
  _el_55:any;
  _text_56:any;
  _text_57:any;
  _el_58:any;
  _text_59:any;
  _text_60:any;
  _el_61:any;
  _text_62:any;
  _el_63:any;
  _text_64:any;
  _el_65:any;
  _text_66:any;
  _text_67:any;
  _el_68:any;
  _text_69:any;
  _el_70:any;
  _text_71:any;
  _el_72:any;
  _text_73:any;
  _el_74:any;
  _text_75:any;
  _text_76:any;
  _text_77:any;
  _text_78:any;
  _el_79:any;
  _text_80:any;
  _el_81:any;
  _text_82:any;
  _text_83:any;
  _text_84:any;
  _text_85:any;
  _text_86:any;
  _el_87:any;
  _text_88:any;
  _el_89:any;
  _text_90:any;
  _text_91:any;
  _el_92:any;
  _text_93:any;
  _el_94:any;
  _text_95:any;
  _text_96:any;
  _el_97:any;
  _text_98:any;
  _el_99:any;
  _text_100:any;
  _text_101:any;
  _text_102:any;
  _el_103:any;
  _text_104:any;
  _text_105:any;
  _el_106:any;
  _text_107:any;
  _el_108:any;
  _text_109:any;
  _text_110:any;
  _text_111:any;
  _el_112:any;
  _text_113:any;
  _text_114:any;
  _text_115:any;
  _text_116:any;
  _el_117:any;
  _text_118:any;
  _el_119:any;
  _text_120:any;
  _text_121:any;
  _el_122:any;
  _text_123:any;
  _el_124:any;
  _text_125:any;
  _el_126:any;
  _text_127:any;
  _el_128:any;
  _text_129:any;
  _el_130:any;
  _text_131:any;
  _el_132:any;
  _text_133:any;
  _el_134:any;
  _text_135:any;
  _text_136:any;
  _el_137:any;
  _text_138:any;
  _text_139:any;
  _text_140:any;
  _el_141:any;
  _text_142:any;
  _text_143:any;
  _text_144:any;
  _text_145:any;
  _text_146:any;
  _text_147:any;
  _el_148:any;
  _text_149:any;
  _el_150:any;
  _text_151:any;
  _text_152:any;
  _el_153:any;
  _text_154:any;
  _text_155:any;
  _el_156:any;
  _text_157:any;
  _el_158:any;
  _text_159:any;
  _text_160:any;
  _el_161:any;
  _text_162:any;
  _text_163:any;
  _text_164:any;
  _text_165:any;
  _el_166:any;
  _text_167:any;
  _text_168:any;
  _el_169:any;
  _text_170:any;
  _text_171:any;
  _text_172:any;
  _text_173:any;
  _el_174:any;
  _text_175:any;
  _text_176:any;
  _el_177:any;
  _text_178:any;
  _el_179:any;
  _text_180:any;
  _text_181:any;
  _el_182:any;
  _text_183:any;
  _el_184:any;
  _text_185:any;
  _el_186:any;
  _text_187:any;
  _text_188:any;
  _text_189:any;
  _el_190:any;
  _text_191:any;
  _el_192:any;
  _text_193:any;
  _text_194:any;
  _text_195:any;
  _el_196:any;
  _text_197:any;
  _text_198:any;
  _text_199:any;
  _text_200:any;
  _el_201:any;
  _text_202:any;
  _el_203:any;
  _text_204:any;
  _text_205:any;
  _text_206:any;
  _text_207:any;
  _el_208:any;
  _text_209:any;
  _text_210:any;
  _el_211:any;
  _text_212:any;
  _text_213:any;
  _el_214:any;
  _text_215:any;
  _el_216:any;
  _text_217:any;
  _el_218:any;
  _text_219:any;
  _text_220:any;
  _text_221:any;
  _text_222:any;
  _el_223:any;
  _text_224:any;
  _text_225:any;
  _el_226:any;
  _text_227:any;
  _text_228:any;
  _el_229:any;
  _text_230:any;
  _text_231:any;
  _el_232:any;
  _text_233:any;
  _el_234:any;
  _text_235:any;
  _el_236:any;
  _text_237:any;
  _text_238:any;
  _text_239:any;
  _el_240:any;
  _text_241:any;
  _el_242:any;
  _text_243:any;
  _text_244:any;
  _text_245:any;
  _text_246:any;
  _el_247:any;
  _text_248:any;
  _text_249:any;
  _el_250:any;
  _text_251:any;
  _el_252:any;
  _text_253:any;
  _text_254:any;
  _el_255:any;
  _text_256:any;
  _text_257:any;
  _el_258:any;
  _text_259:any;
  _text_260:any;
  _el_261:any;
  _text_262:any;
  _text_263:any;
  _el_264:any;
  _text_265:any;
  _text_266:any;
  _el_267:any;
  _text_268:any;
  _text_269:any;
  _el_270:any;
  _text_271:any;
  _text_272:any;
  _text_273:any;
  _el_274:any;
  _text_275:any;
  _text_276:any;
  _el_277:any;
  _text_278:any;
  _el_279:any;
  _text_280:any;
  _el_281:any;
  _text_282:any;
  _text_283:any;
  _el_284:any;
  _text_285:any;
  _el_286:any;
  _text_287:any;
  _text_288:any;
  _el_289:any;
  _text_290:any;
  _el_291:any;
  _text_292:any;
  _text_293:any;
  _el_294:any;
  _el_295:any;
  _text_296:any;
  _text_297:any;
  _el_298:any;
  _text_299:any;
  _el_300:any;
  _text_301:any;
  _el_302:any;
  _text_303:any;
  _text_304:any;
  _text_305:any;
  _el_306:any;
  _text_307:any;
  _el_308:any;
  _text_309:any;
  _text_310:any;
  _text_311:any;
  _el_312:any;
  _text_313:any;
  _el_314:any;
  _text_315:any;
  _text_316:any;
  _text_317:any;
  _el_318:any;
  _text_319:any;
  _el_320:any;
  _text_321:any;
  _text_322:any;
  _text_323:any;
  _el_324:any;
  _text_325:any;
  _el_326:any;
  _text_327:any;
  _text_328:any;
  _text_329:any;
  _el_330:any;
  _text_331:any;
  _el_332:any;
  _text_333:any;
  _text_334:any;
  _text_335:any;
  _el_336:any;
  _text_337:any;
  _el_338:any;
  _text_339:any;
  _text_340:any;
  _text_341:any;
  _el_342:any;
  _text_343:any;
  _el_344:any;
  _text_345:any;
  _text_346:any;
  _text_347:any;
  _el_348:any;
  _text_349:any;
  _el_350:any;
  _text_351:any;
  _text_352:any;
  _text_353:any;
  _el_354:any;
  _text_355:any;
  _el_356:any;
  _text_357:any;
  _text_358:any;
  _text_359:any;
  _el_360:any;
  _text_361:any;
  _el_362:any;
  _text_363:any;
  _text_364:any;
  _text_365:any;
  _el_366:any;
  _text_367:any;
  _el_368:any;
  _text_369:any;
  _text_370:any;
  _text_371:any;
  _el_372:any;
  _text_373:any;
  _el_374:any;
  _text_375:any;
  _text_376:any;
  _text_377:any;
  _el_378:any;
  _text_379:any;
  _el_380:any;
  _text_381:any;
  _text_382:any;
  _text_383:any;
  _el_384:any;
  _text_385:any;
  _el_386:any;
  _text_387:any;
  _text_388:any;
  _text_389:any;
  _el_390:any;
  _text_391:any;
  _text_392:any;
  _text_393:any;
  _text_394:any;
  _el_395:any;
  _text_396:any;
  _el_397:any;
  _text_398:any;
  _text_399:any;
  _text_400:any;
  _el_401:any;
  _text_402:any;
  _text_403:any;
  _el_404:any;
  _text_405:any;
  _el_406:any;
  _text_407:any;
  _text_408:any;
  _text_409:any;
  _el_410:any;
  _text_411:any;
  _el_412:any;
  _text_413:any;
  _text_414:any;
  _text_415:any;
  _el_416:any;
  _text_417:any;
  _el_418:any;
  _text_419:any;
  _text_420:any;
  _text_421:any;
  _el_422:any;
  _text_423:any;
  _el_424:any;
  _text_425:any;
  _text_426:any;
  _el_427:any;
  _text_428:any;
  _el_429:any;
  _text_430:any;
  _text_431:any;
  _el_432:any;
  _text_433:any;
  _text_434:any;
  _el_435:any;
  _text_436:any;
  _text_437:any;
  _text_438:any;
  _text_439:any;
  _text_440:any;
  _text_441:any;
  _text_442:any;
  _text_443:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_TermsComponent0,renderType_TermsComponent,import5.ViewType.COMPONENT,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    const parentRenderNode:any = this.renderer.createViewRoot(this.parentElement);
    this._el_0 = import3.createRenderElement(this.renderer,parentRenderNode,'pagetitle',import3.EMPTY_INLINE_ARRAY,(null as any));
    this.compView_0 = new import10.View_PageTitleComponent0(this.viewUtils,this,0,this._el_0);
    this._PageTitleComponent_0_3 = new import10.Wrapper_PageTitleComponent();
    this.compView_0.create(this._PageTitleComponent_0_3.context);
    this._text_1 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,parentRenderNode,'div',new import3.InlineArray2(2,'class','container'),(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'\n  ',(null as any));
    this._el_4 = import3.createRenderElement(this.renderer,this._el_2,'p',new import3.InlineArray2(2,'style','text-align: center;'),(null as any));
    this._text_5 = this.renderer.createText(this._el_4,'\n    ',(null as any));
    this._el_6 = import3.createRenderElement(this.renderer,this._el_4,'strong',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_7 = this.renderer.createText(this._el_6,'Website Terms of Use',(null as any));
    this._text_8 = this.renderer.createText(this._el_4,'\n  ',(null as any));
    this._text_9 = this.renderer.createText(this._el_2,'\n  ',(null as any));
    this._el_10 = import3.createRenderElement(this.renderer,this._el_2,'p',new import3.InlineArray2(2,'style','text-align: center;'),(null as any));
    this._text_11 = this.renderer.createText(this._el_10,'\n    ',(null as any));
    this._el_12 = import3.createRenderElement(this.renderer,this._el_10,'strong',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_13 = this.renderer.createText(this._el_12,'Version 1.0',(null as any));
    this._text_14 = this.renderer.createText(this._el_10,'\n  ',(null as any));
    this._text_15 = this.renderer.createText(this._el_2,'\n  ',(null as any));
    this._el_16 = import3.createRenderElement(this.renderer,this._el_2,'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_17 = this.renderer.createText(this._el_16,'The website located at http://www.ibuyasis.com is a copyrighted work belonging to I Buy As Is, Inc.  Certain features of the Site may be subject to additional guidelines, terms, or rules, which will be posted on the Site in connection with such features.  All such additional terms, guidelines, and rules are incorporated by reference into these Terms.',(null as any));
    this._text_18 = this.renderer.createText(this._el_2,'\n  ',(null as any));
    this._el_19 = import3.createRenderElement(this.renderer,this._el_2,'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_20 = this.renderer.createText(this._el_19,'\n    ',(null as any));
    this._el_21 = import3.createRenderElement(this.renderer,this._el_19,'strong',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_22 = this.renderer.createText(this._el_21,'Cookies and Web Beacons',(null as any));
    this._text_23 = this.renderer.createText(this._el_19,'\n  ',(null as any));
    this._text_24 = this.renderer.createText(this._el_2,'\n  ',(null as any));
    this._el_25 = import3.createRenderElement(this.renderer,this._el_2,'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_26 = this.renderer.createText(this._el_25,'Like any other website,  uses ‘cookies’. These cookies are used to store information including visitors’ preferences, and the pages on the website that the visitor accessed or visited. The information is used to optimize the users’ experience by customizing our web page content based on visitors’ browser type and/or other information.',(null as any));
    this._text_27 = this.renderer.createText(this._el_2,'\n  ',(null as any));
    this._el_28 = import3.createRenderElement(this.renderer,this._el_2,'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_29 = this.renderer.createText(this._el_28,'\n    ',(null as any));
    this._el_30 = import3.createRenderElement(this.renderer,this._el_28,'strong',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_31 = this.renderer.createText(this._el_30,'DoubleClick DART Cookie',(null as any));
    this._text_32 = this.renderer.createText(this._el_28,'\n  ',(null as any));
    this._text_33 = this.renderer.createText(this._el_2,'\n  ',(null as any));
    this._el_34 = import3.createRenderElement(this.renderer,this._el_2,'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_35 = this.renderer.createText(this._el_34,'Google is one of a third-party vendor on our site. It also uses cookies, known as DART cookies, to serve ads to our site visitors based upon their visit to  and other sites on the internet. However, visitors may choose to decline the use of DART cookies by visiting the Google ad and content network Privacy Policy at the following URL – http://www.google.com/privacy_ads.html.',(null as any));
    this._text_36 = this.renderer.createText(this._el_2,'\n  ',(null as any));
    this._el_37 = import3.createRenderElement(this.renderer,this._el_2,'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_38 = this.renderer.createText(this._el_37,'\n    ',(null as any));
    this._el_39 = import3.createRenderElement(this.renderer,this._el_37,'strong',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_40 = this.renderer.createText(this._el_39,'Our Advertising Partners',(null as any));
    this._text_41 = this.renderer.createText(this._el_37,'\n  ',(null as any));
    this._text_42 = this.renderer.createText(this._el_2,'\n  ',(null as any));
    this._el_43 = import3.createRenderElement(this.renderer,this._el_2,'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_44 = this.renderer.createText(this._el_43,'Some of advertisers on our site may use cookies and web beacons. Our advertising partners include:',(null as any));
    this._text_45 = this.renderer.createText(this._el_2,'\n  ',(null as any));
    this._el_46 = import3.createRenderElement(this.renderer,this._el_2,'ul',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_47 = this.renderer.createText(this._el_46,'\n    ',(null as any));
    this._el_48 = import3.createRenderElement(this.renderer,this._el_46,'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_49 = this.renderer.createText(this._el_48,'Google',(null as any));
    this._text_50 = this.renderer.createText(this._el_46,'\n  ',(null as any));
    this._text_51 = this.renderer.createText(this._el_2,'\n  ',(null as any));
    this._el_52 = import3.createRenderElement(this.renderer,this._el_2,'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_53 = this.renderer.createText(this._el_52,'Each of our advertising partners has their own Privacy Policy for their website. For easier access, an updated and hyperlinked resource is maintained here:',(null as any));
    this._text_54 = this.renderer.createText(this._el_2,'\n  ',(null as any));
    this._el_55 = import3.createRenderElement(this.renderer,this._el_2,'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_56 = this.renderer.createText(this._el_55,'These Terms of Use described the legally binding terms and conditions that oversee your use of the Site.  BY LOGGING INTO THE SITE, YOU ARE BEING COMPLIANT THAT THESE TERMS and you represent that you have the authority and capacity to enter into these Terms.  YOU SHOULD BE AT LEAST 18 YEARS OF AGE TO ACCESS THE SITE. IF YOU DISAGREE WITH ALL OF THE PROVISION OF THESE TERMS, DO NOT LOG INTO AND/OR USE THE SITE.',(null as any));
    this._text_57 = this.renderer.createText(this._el_2,'\n  ',(null as any));
    this._el_58 = import3.createRenderElement(this.renderer,this._el_2,'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_59 = this.renderer.createText(this._el_58,'These terms require the use of arbitration Section 10.2 on an individual basis to resolve disputes and also limit the remedies available to you in the event of a dispute.',(null as any));
    this._text_60 = this.renderer.createText(this._el_2,'\n  ',(null as any));
    this._el_61 = import3.createRenderElement(this.renderer,this._el_2,'ol',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_62 = this.renderer.createText(this._el_61,'\n    ',(null as any));
    this._el_63 = import3.createRenderElement(this.renderer,this._el_61,'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_64 = this.renderer.createText(this._el_63,'\n      ',(null as any));
    this._el_65 = import3.createRenderElement(this.renderer,this._el_63,'strong',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_66 = this.renderer.createText(this._el_65,'Accounts ',(null as any));
    this._text_67 = this.renderer.createText(this._el_63,'\n      ',(null as any));
    this._el_68 = import3.createRenderElement(this.renderer,this._el_63,'ul',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_69 = this.renderer.createText(this._el_68,'\n        ',(null as any));
    this._el_70 = import3.createRenderElement(this.renderer,this._el_68,'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_71 = this.renderer.createText(this._el_70,'\n          ',(null as any));
    this._el_72 = import3.createRenderElement(this.renderer,this._el_70,'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_73 = this.renderer.createText(this._el_72,'\n            ',(null as any));
    this._el_74 = import3.createRenderElement(this.renderer,this._el_72,'strong',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_75 = this.renderer.createText(this._el_74,'Account Creation. ',(null as any));
    this._text_76 = this.renderer.createText(this._el_72,'For you to use the Site, you have to start an account and provide information about yourself. You warrant that: (a) all required registration information you submit is truthful, up-to-date and accurate; (b) you will maintain the accuracy of such information. You may delete your Account at any time by following the instructions on the Site.  Company may suspend or terminate your Account in accordance with Section\n          ',(null as any));
    this._text_77 = this.renderer.createText(this._el_70,'\n        ',(null as any));
    this._text_78 = this.renderer.createText(this._el_68,'\n        ',(null as any));
    this._el_79 = import3.createRenderElement(this.renderer,this._el_68,'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_80 = this.renderer.createText(this._el_79,'\n          ',(null as any));
    this._el_81 = import3.createRenderElement(this.renderer,this._el_79,'strong',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_82 = this.renderer.createText(this._el_81,'Account Responsibilities.',(null as any));
    this._text_83 = this.renderer.createText(this._el_79,' You are responsible for maintaining the confidentiality of your Account login information and are fully responsible for all activities that occur under your Account. You approve to immediately notify the Company of any unauthorized use, or suspected unauthorized use of your Account.  Company cannot and will not be liable for any loss or damage arising from your failure to comply with the above requirements.\n        ',(null as any));
    this._text_84 = this.renderer.createText(this._el_68,'\n      ',(null as any));
    this._text_85 = this.renderer.createText(this._el_63,'\n    ',(null as any));
    this._text_86 = this.renderer.createText(this._el_61,'\n    ',(null as any));
    this._el_87 = import3.createRenderElement(this.renderer,this._el_61,'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_88 = this.renderer.createText(this._el_87,'\n      ',(null as any));
    this._el_89 = import3.createRenderElement(this.renderer,this._el_87,'strong',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_90 = this.renderer.createText(this._el_89,'Access to the Site ',(null as any));
    this._text_91 = this.renderer.createText(this._el_87,'\n      ',(null as any));
    this._el_92 = import3.createRenderElement(this.renderer,this._el_87,'ul',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_93 = this.renderer.createText(this._el_92,'\n        ',(null as any));
    this._el_94 = import3.createRenderElement(this.renderer,this._el_92,'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_95 = this.renderer.createText(this._el_94,'Subject to these Terms, Company grants you a non-transferable, non-exclusive, revocable, limited license to access the Site solely for your own personal, noncommercial use.',(null as any));
    this._text_96 = this.renderer.createText(this._el_92,'\n        ',(null as any));
    this._el_97 = import3.createRenderElement(this.renderer,this._el_92,'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_98 = this.renderer.createText(this._el_97,'\n          ',(null as any));
    this._el_99 = import3.createRenderElement(this.renderer,this._el_97,'strong',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_100 = this.renderer.createText(this._el_99,'Certain Restrictions. ',(null as any));
    this._text_101 = this.renderer.createText(this._el_97,'The rights approved to you in these Terms are subject to the following restrictions: (a) you shall not sell, rent, lease, transfer, assign, distribute, host, or otherwise commercially exploit the Site; (b) you shall not change, make derivative works of, disassemble, reverse compile or reverse engineer any part of the Site; (c) you shall not access the Site in order to build a similar or competitive website; and (d) except as expressly stated herein, no part of the Site may be copied, reproduced, distributed, republished, downloaded, displayed, posted or transmitted in any form or by any means unless otherwise indicated, any future release, update, or other addition to functionality of the Site shall be subject to these Terms.  All copyright and other proprietary notices on the Site must be retained on all copies thereof.\n        ',(null as any));
    this._text_102 = this.renderer.createText(this._el_92,'\n        ',(null as any));
    this._el_103 = import3.createRenderElement(this.renderer,this._el_92,'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_104 = this.renderer.createText(this._el_103,'Company reserves the right to change, suspend, or cease the Site with or without notice to you.  You approved that Company will not be held liable to you or any third-party for any change, interruption, or termination of the Site or any part.',(null as any));
    this._text_105 = this.renderer.createText(this._el_92,'\n        ',(null as any));
    this._el_106 = import3.createRenderElement(this.renderer,this._el_92,'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_107 = this.renderer.createText(this._el_106,'\n          ',(null as any));
    this._el_108 = import3.createRenderElement(this.renderer,this._el_106,'strong',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_109 = this.renderer.createText(this._el_108,'No Support or Maintenance.',(null as any));
    this._text_110 = this.renderer.createText(this._el_106,' You agree that Company will have no obligation to provide you with any support in connection with the Site.\n        ',(null as any));
    this._text_111 = this.renderer.createText(this._el_92,'\n        ',(null as any));
    this._el_112 = import3.createRenderElement(this.renderer,this._el_92,'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_113 = this.renderer.createText(this._el_112,'Excluding any User Content that you may provide, you are aware that all the intellectual property rights, including copyrights, patents, trademarks, and trade secrets, in the Site and its content are owned by Company or Company’s suppliers. Note that these Terms and access to the Site do not give you any rights, title or interest in or to any intellectual property rights, except for the limited access rights expressed in Section 2.1. Company and its suppliers reserve all rights not granted in these Terms.',(null as any));
    this._text_114 = this.renderer.createText(this._el_92,'\n      ',(null as any));
    this._text_115 = this.renderer.createText(this._el_87,'\n    ',(null as any));
    this._text_116 = this.renderer.createText(this._el_61,'\n    ',(null as any));
    this._el_117 = import3.createRenderElement(this.renderer,this._el_61,'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_118 = this.renderer.createText(this._el_117,'\n      ',(null as any));
    this._el_119 = import3.createRenderElement(this.renderer,this._el_117,'strong',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_120 = this.renderer.createText(this._el_119,'User Content',(null as any));
    this._text_121 = this.renderer.createText(this._el_117,'\n      ',(null as any));
    this._el_122 = import3.createRenderElement(this.renderer,this._el_117,'ul',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_123 = this.renderer.createText(this._el_122,'\n        ',(null as any));
    this._el_124 = import3.createRenderElement(this.renderer,this._el_122,'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_125 = this.renderer.createText(this._el_124,'\n          ',(null as any));
    this._el_126 = import3.createRenderElement(this.renderer,this._el_124,'ul',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_127 = this.renderer.createText(this._el_126,'\n            ',(null as any));
    this._el_128 = import3.createRenderElement(this.renderer,this._el_126,'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_129 = this.renderer.createText(this._el_128,'\n              ',(null as any));
    this._el_130 = import3.createRenderElement(this.renderer,this._el_128,'ul',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_131 = this.renderer.createText(this._el_130,'\n                ',(null as any));
    this._el_132 = import3.createRenderElement(this.renderer,this._el_130,'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_133 = this.renderer.createText(this._el_132,'\n                  ',(null as any));
    this._el_134 = import3.createRenderElement(this.renderer,this._el_132,'strong',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_135 = this.renderer.createText(this._el_134,'User Content.',(null as any));
    this._text_136 = this.renderer.createText(this._el_132,' “\n                  ',(null as any));
    this._el_137 = import3.createRenderElement(this.renderer,this._el_132,'strong',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_138 = this.renderer.createText(this._el_137,'User Content',(null as any));
    this._text_139 = this.renderer.createText(this._el_132,'” means any and all information and content that a user submits to the Site. You are exclusively responsible for your User Content. You bear all risks associated with use of your User Content.  You hereby certify that your User Content does not violate our Acceptable Use Policy.  You may not represent or imply to others that your User Content is in any way provided, sponsored or endorsed by Company. Because you alone are responsible for your User Content, you may expose yourself to liability. Company is not obliged to backup any User Content that you post; also, your User Content may be deleted at any time without prior notice to you. You are solely responsible for making your own backup copies of your User Content if you desire.\n                ',(null as any));
    this._text_140 = this.renderer.createText(this._el_130,'\n                ',(null as any));
    this._el_141 = import3.createRenderElement(this.renderer,this._el_130,'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_142 = this.renderer.createText(this._el_141,'You hereby grant to Company an irreversible, nonexclusive, royalty-free and fully paid, worldwide license to reproduce, distribute, publicly display and perform, prepare derivative works of, incorporate into other works, and otherwise use and exploit your User Content, and to grant sublicenses of the foregoing rights, solely for the purposes of including your User Content in the Site.  You hereby irreversibly waive any claims and assertions of moral rights or attribution with respect to your User Content.',(null as any));
    this._text_143 = this.renderer.createText(this._el_130,'\n              ',(null as any));
    this._text_144 = this.renderer.createText(this._el_128,'\n            ',(null as any));
    this._text_145 = this.renderer.createText(this._el_126,'\n          ',(null as any));
    this._text_146 = this.renderer.createText(this._el_124,'\n        ',(null as any));
    this._text_147 = this.renderer.createText(this._el_122,'\n        ',(null as any));
    this._el_148 = import3.createRenderElement(this.renderer,this._el_122,'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_149 = this.renderer.createText(this._el_148,'\n          ',(null as any));
    this._el_150 = import3.createRenderElement(this.renderer,this._el_148,'strong',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_151 = this.renderer.createText(this._el_150,'Acceptable Use Policy.',(null as any));
    this._text_152 = this.renderer.createText(this._el_148,' The following terms constitute our “\n          ',(null as any));
    this._el_153 = import3.createRenderElement(this.renderer,this._el_148,'strong',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_154 = this.renderer.createText(this._el_153,'Acceptable Use Policy',(null as any));
    this._text_155 = this.renderer.createText(this._el_148,'”:\n          ',(null as any));
    this._el_156 = import3.createRenderElement(this.renderer,this._el_148,'ul',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_157 = this.renderer.createText(this._el_156,'\n            ',(null as any));
    this._el_158 = import3.createRenderElement(this.renderer,this._el_156,'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_159 = this.renderer.createText(this._el_158,'You agree not to use the Site to collect, upload, transmit, display, or distribute any User Content (i) that violates any third-party right or any intellectual property or proprietary right; (ii) that is unlawful, harassing, abusive, tortious, threatening, harmful, invasive of another’s privacy, vulgar, defamatory, false, intentionally misleading, trade libelous, pornographic, obscene, patently offensive, promotes racism, bigotry, hatred, or physical harm of any kind against any group or individual; (iii) that is harmful to minors in any way; or (iv) that is in violation of any law, regulation, or obligations or restrictions imposed by any third party.',(null as any));
    this._text_160 = this.renderer.createText(this._el_156,'\n            ',(null as any));
    this._el_161 = import3.createRenderElement(this.renderer,this._el_156,'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_162 = this.renderer.createText(this._el_161,'In addition, you agree not to: (i) upload, transmit, or distribute to or through the Site any software intended to damage or alter a computer system or data; (ii) send through the Site unsolicited or unauthorized advertising, promotional materials, junk mail, spam, chain letters, pyramid schemes, or any other form of duplicative or unsolicited messages; (iii) use the Site to harvest, collect, gather or assemble information or data regarding other users without their consent; (iv) interfere with, disrupt, or create an undue burden on servers or networks connected to the Site, or violate the regulations, policies or procedures of such networks; (v) attempt to gain unauthorized access to the Site, whether through password mining or any other means; (vi) harass or interfere with any other user’s use and enjoyment of the Site; or (vi) use software or automated agents or scripts to produce multiple accounts on the Site, or to generate automated searches, requests, or queries to the Site.',(null as any));
    this._text_163 = this.renderer.createText(this._el_156,'\n          ',(null as any));
    this._text_164 = this.renderer.createText(this._el_148,'\n        ',(null as any));
    this._text_165 = this.renderer.createText(this._el_122,'\n        ',(null as any));
    this._el_166 = import3.createRenderElement(this.renderer,this._el_122,'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_167 = this.renderer.createText(this._el_166,'We reserve the right to review any User Content, and to investigate and/or take appropriate action against you in our sole discretion if you violate the Acceptable Use Policy or any other provision of these Terms or otherwise create liability for us or any other person. Such action may include removing or modifying your User Content, terminating your Account in accordance with Section 8, and/or reporting you to law enforcement authorities.',(null as any));
    this._text_168 = this.renderer.createText(this._el_122,'\n        ',(null as any));
    this._el_169 = import3.createRenderElement(this.renderer,this._el_122,'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_170 = this.renderer.createText(this._el_169,'If you provide Company with any feedback or suggestions regarding the Site, you hereby assign to Company all rights in such Feedback and agree that Company shall have the right to use and fully exploit such Feedback and related information in any manner it believes appropriate.  Company will treat any Feedback you provide to Company as non-confidential and non-proprietary.',(null as any));
    this._text_171 = this.renderer.createText(this._el_122,'\n      ',(null as any));
    this._text_172 = this.renderer.createText(this._el_117,'\n    ',(null as any));
    this._text_173 = this.renderer.createText(this._el_61,'\n    ',(null as any));
    this._el_174 = import3.createRenderElement(this.renderer,this._el_61,'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_175 = this.renderer.createText(this._el_174,'You agree to indemnify and hold Company and its officers, employees, and agents harmless, including costs and attorneys’ fees, from any claim or demand made by any third-party due to or arising out of (a) your use of the Site, (b) your violation of these Terms, (c) your violation of applicable laws or regulations or (d) your User Content.  Company reserves the right to assume the exclusive defense and control of any matter for which you are required to indemnify us, and you agree to cooperate with our defense of these claims.  You agree not to settle any matter without the prior written consent of Company.  Company will use reasonable efforts to notify you of any such claim, action or proceeding upon becoming aware of it.',(null as any));
    this._text_176 = this.renderer.createText(this._el_61,'\n    ',(null as any));
    this._el_177 = import3.createRenderElement(this.renderer,this._el_61,'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_178 = this.renderer.createText(this._el_177,'\n      ',(null as any));
    this._el_179 = import3.createRenderElement(this.renderer,this._el_177,'strong',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_180 = this.renderer.createText(this._el_179,'Third-Party Links & Ads; Other Users',(null as any));
    this._text_181 = this.renderer.createText(this._el_177,'\n      ',(null as any));
    this._el_182 = import3.createRenderElement(this.renderer,this._el_177,'ul',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_183 = this.renderer.createText(this._el_182,'\n        ',(null as any));
    this._el_184 = import3.createRenderElement(this.renderer,this._el_182,'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_185 = this.renderer.createText(this._el_184,'\n          ',(null as any));
    this._el_186 = import3.createRenderElement(this.renderer,this._el_184,'strong',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_187 = this.renderer.createText(this._el_186,'Third-Party Links & Ads. ',(null as any));
    this._text_188 = this.renderer.createText(this._el_184,'The Site may contain links to third-party websites and services, and/or display advertisements for third-parties.  Such Third-Party Links & Ads are not under the control of Company, and Company is not responsible for any Third-Party Links & Ads.  Company provides access to these Third-Party Links & Ads only as a convenience to you, and does not review, approve, monitor, endorse, warrant, or make any representations with respect to Third-Party Links & Ads.  You use all Third-Party Links & Ads at your own risk, and should apply a suitable level of caution and discretion in doing so. When you click on any of the Third-Party Links & Ads, the applicable third party’s terms and policies apply, including the third party’s privacy and data gathering practices.\n        ',(null as any));
    this._text_189 = this.renderer.createText(this._el_182,'\n        ',(null as any));
    this._el_190 = import3.createRenderElement(this.renderer,this._el_182,'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_191 = this.renderer.createText(this._el_190,'\n          ',(null as any));
    this._el_192 = import3.createRenderElement(this.renderer,this._el_190,'strong',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_193 = this.renderer.createText(this._el_192,'Other Users. ',(null as any));
    this._text_194 = this.renderer.createText(this._el_190,'Each Site user is solely responsible for any and all of its own User Content.  Because we do not control User Content, you acknowledge and agree that we are not responsible for any User Content, whether provided by you or by others.  You agree that Company will not be responsible for any loss or damage incurred as the result of any such interactions.  If there is a dispute between you and any Site user, we are under no obligation to become involved.\n        ',(null as any));
    this._text_195 = this.renderer.createText(this._el_182,'\n        ',(null as any));
    this._el_196 = import3.createRenderElement(this.renderer,this._el_182,'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_197 = this.renderer.createText(this._el_196,'You hereby release and forever discharge the Company and our officers, employees, agents, successors, and assigns from, and hereby waive and relinquish, each and every past, present and future dispute, claim, controversy, demand, right, obligation, liability, action and cause of action of every kind and nature, that has arisen or arises directly or indirectly out of, or that relates directly or indirectly to, the Site. If you are a California resident, you hereby waive California civil code section 1542 in connection with the foregoing, which states: “a general release does not extend to claims which the creditor does not know or suspect to exist in his or her favor at the time of executing the release, which if known by him or her must have materially affected his or her settlement with the debtor.”',(null as any));
    this._text_198 = this.renderer.createText(this._el_182,'\n      ',(null as any));
    this._text_199 = this.renderer.createText(this._el_177,'\n    ',(null as any));
    this._text_200 = this.renderer.createText(this._el_61,'\n    ',(null as any));
    this._el_201 = import3.createRenderElement(this.renderer,this._el_61,'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_202 = this.renderer.createText(this._el_201,'\n      ',(null as any));
    this._el_203 = import3.createRenderElement(this.renderer,this._el_201,'strong',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_204 = this.renderer.createText(this._el_203,'Disclaimers',(null as any));
    this._text_205 = this.renderer.createText(this._el_201,'\n    ',(null as any));
    this._text_206 = this.renderer.createText(this._el_61,'\n  ',(null as any));
    this._text_207 = this.renderer.createText(this._el_2,'\n  ',(null as any));
    this._el_208 = import3.createRenderElement(this.renderer,this._el_2,'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_209 = this.renderer.createText(this._el_208,'The site is provided on an “as-is” and “as available” basis, and company and our suppliers expressly disclaim any and all warranties and conditions of any kind, whether express, implied, or statutory, including all warranties or conditions of merchantability, fitness for a particular purpose, title, quiet enjoyment, accuracy, or non-infringement.  We and our suppliers make not guarantee that the site will meet your requirements, will be available on an uninterrupted, timely, secure, or error-free basis, or will be accurate, reliable, free of viruses or other harmful code, complete, legal, or safe.  If applicable law requires any warranties with respect to the site, all such warranties are limited in duration to ninety (90) days from the date of first use.',(null as any));
    this._text_210 = this.renderer.createText(this._el_2,'\n  ',(null as any));
    this._el_211 = import3.createRenderElement(this.renderer,this._el_2,'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_212 = this.renderer.createText(this._el_211,'Some jurisdictions do not allow the exclusion of implied warranties, so the above exclusion may not apply to you.  Some jurisdictions do not allow limitations on how long an implied warranty lasts, so the above limitation may not apply to you.',(null as any));
    this._text_213 = this.renderer.createText(this._el_2,'\n  ',(null as any));
    this._el_214 = import3.createRenderElement(this.renderer,this._el_2,'ol',new import3.InlineArray2(2,'start','7'),(null as any));
    this._text_215 = this.renderer.createText(this._el_214,'\n    ',(null as any));
    this._el_216 = import3.createRenderElement(this.renderer,this._el_214,'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_217 = this.renderer.createText(this._el_216,'\n      ',(null as any));
    this._el_218 = import3.createRenderElement(this.renderer,this._el_216,'strong',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_219 = this.renderer.createText(this._el_218,'Limitation on Liability',(null as any));
    this._text_220 = this.renderer.createText(this._el_216,'\n    ',(null as any));
    this._text_221 = this.renderer.createText(this._el_214,'\n  ',(null as any));
    this._text_222 = this.renderer.createText(this._el_2,'\n  ',(null as any));
    this._el_223 = import3.createRenderElement(this.renderer,this._el_2,'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_224 = this.renderer.createText(this._el_223,'To the maximum extent permitted by law, in no event shall company or our suppliers be liable to you or any third-party for any lost profits, lost data, costs of procurement of substitute products, or any indirect, consequential, exemplary, incidental, special or punitive damages arising from or relating to these terms or your use of, or incapability to use the site even if company has been advised of the possibility of such damages.  Access to and use of the site is at your own discretion and risk, and you will be solely responsible for any damage to your device or computer system, or loss of data resulting therefrom.',(null as any));
    this._text_225 = this.renderer.createText(this._el_2,'\n  ',(null as any));
    this._el_226 = import3.createRenderElement(this.renderer,this._el_2,'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_227 = this.renderer.createText(this._el_226,'To the maximum extent permitted by law, notwithstanding anything to the contrary contained herein, our liability to you for any damages arising from or related to this agreement, will at all times be limited to a maximum of fifty U.S. dollars (u.s. $50). The existence of more than one claim will not enlarge this limit.  You agree that our suppliers will have no liability of any kind arising from or relating to this agreement.',(null as any));
    this._text_228 = this.renderer.createText(this._el_2,'\n  ',(null as any));
    this._el_229 = import3.createRenderElement(this.renderer,this._el_2,'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_230 = this.renderer.createText(this._el_229,'Some jurisdictions do not allow the limitation or exclusion of liability for incidental or consequential damages, so the above limitation or exclusion may not apply to you.',(null as any));
    this._text_231 = this.renderer.createText(this._el_2,'\n  ',(null as any));
    this._el_232 = import3.createRenderElement(this.renderer,this._el_2,'ol',new import3.InlineArray2(2,'start','8'),(null as any));
    this._text_233 = this.renderer.createText(this._el_232,'\n    ',(null as any));
    this._el_234 = import3.createRenderElement(this.renderer,this._el_232,'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_235 = this.renderer.createText(this._el_234,'\n      ',(null as any));
    this._el_236 = import3.createRenderElement(this.renderer,this._el_234,'strong',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_237 = this.renderer.createText(this._el_236,'Term and Termination. ',(null as any));
    this._text_238 = this.renderer.createText(this._el_234,'Subject to this Section, these Terms will remain in full force and effect while you use the Site.  We may suspend or terminate your rights to use the Site at any time for any reason at our sole discretion, including for any use of the Site in violation of these Terms.  Upon termination of your rights under these Terms, your Account and right to access and use the Site will terminate immediately.  You understand that any termination of your Account may involve deletion of your User Content associated with your Account from our live databases.  Company will not have any liability whatsoever to you for any termination of your rights under these Terms.  Even after your rights under these Terms are terminated, the following provisions of these Terms will remain in effect: Sections 2 through 2.5, Section 3 and Sections 4 through 10.\n    ',(null as any));
    this._text_239 = this.renderer.createText(this._el_232,'\n    ',(null as any));
    this._el_240 = import3.createRenderElement(this.renderer,this._el_232,'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_241 = this.renderer.createText(this._el_240,'\n      ',(null as any));
    this._el_242 = import3.createRenderElement(this.renderer,this._el_240,'strong',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_243 = this.renderer.createText(this._el_242,'Copyright Policy.',(null as any));
    this._text_244 = this.renderer.createText(this._el_240,'\n    ',(null as any));
    this._text_245 = this.renderer.createText(this._el_232,'\n  ',(null as any));
    this._text_246 = this.renderer.createText(this._el_2,'\n  ',(null as any));
    this._el_247 = import3.createRenderElement(this.renderer,this._el_2,'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_248 = this.renderer.createText(this._el_247,'Company respects the intellectual property of others and asks that users of our Site do the same.  In connection with our Site, we have adopted and implemented a policy respecting copyright law that provides for the removal of any infringing materials and for the termination of users of our online Site who are repeated infringers of intellectual property rights, including copyrights.  If you believe that one of our users is, through the use of our Site, unlawfully infringing the copyright(s) in a work, and wish to have the allegedly infringing material removed, the following information in the form of a written notification (pursuant to 17 U.S.C. § 512(c)) must be provided to our designated Copyright Agent:',(null as any));
    this._text_249 = this.renderer.createText(this._el_2,'\n  ',(null as any));
    this._el_250 = import3.createRenderElement(this.renderer,this._el_2,'ol',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_251 = this.renderer.createText(this._el_250,'\n    ',(null as any));
    this._el_252 = import3.createRenderElement(this.renderer,this._el_250,'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_253 = this.renderer.createText(this._el_252,'your physical or electronic signature;',(null as any));
    this._text_254 = this.renderer.createText(this._el_250,'\n    ',(null as any));
    this._el_255 = import3.createRenderElement(this.renderer,this._el_250,'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_256 = this.renderer.createText(this._el_255,'identification of the copyrighted work(s) that you claim to have been infringed;',(null as any));
    this._text_257 = this.renderer.createText(this._el_250,'\n    ',(null as any));
    this._el_258 = import3.createRenderElement(this.renderer,this._el_250,'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_259 = this.renderer.createText(this._el_258,'identification of the material on our services that you claim is infringing and that you request us to remove;',(null as any));
    this._text_260 = this.renderer.createText(this._el_250,'\n    ',(null as any));
    this._el_261 = import3.createRenderElement(this.renderer,this._el_250,'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_262 = this.renderer.createText(this._el_261,'sufficient information to permit us to locate such material;',(null as any));
    this._text_263 = this.renderer.createText(this._el_250,'\n    ',(null as any));
    this._el_264 = import3.createRenderElement(this.renderer,this._el_250,'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_265 = this.renderer.createText(this._el_264,'your address, telephone number, and e-mail address;',(null as any));
    this._text_266 = this.renderer.createText(this._el_250,'\n    ',(null as any));
    this._el_267 = import3.createRenderElement(this.renderer,this._el_250,'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_268 = this.renderer.createText(this._el_267,'a statement that you have a good faith belief that use of the objectionable material is not authorized by the copyright owner, its agent, or under the law; and',(null as any));
    this._text_269 = this.renderer.createText(this._el_250,'\n    ',(null as any));
    this._el_270 = import3.createRenderElement(this.renderer,this._el_250,'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_271 = this.renderer.createText(this._el_270,'a statement that the information in the notification is accurate, and under penalty of perjury, that you are either the owner of the copyright that has allegedly been infringed or that you are authorized to act on behalf of the copyright owner.',(null as any));
    this._text_272 = this.renderer.createText(this._el_250,'\n  ',(null as any));
    this._text_273 = this.renderer.createText(this._el_2,'\n  ',(null as any));
    this._el_274 = import3.createRenderElement(this.renderer,this._el_2,'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_275 = this.renderer.createText(this._el_274,'Please note that, pursuant to 17 U.S.C. § 512(f), any misrepresentation of material fact in a written notification automatically subjects the complaining party to liability for any damages, costs and attorney’s fees incurred by us in connection with the written notification and allegation of copyright infringement.',(null as any));
    this._text_276 = this.renderer.createText(this._el_2,'\n  ',(null as any));
    this._el_277 = import3.createRenderElement(this.renderer,this._el_2,'ol',new import3.InlineArray2(2,'start','10'),(null as any));
    this._text_278 = this.renderer.createText(this._el_277,'\n    ',(null as any));
    this._el_279 = import3.createRenderElement(this.renderer,this._el_277,'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_280 = this.renderer.createText(this._el_279,'\n      ',(null as any));
    this._el_281 = import3.createRenderElement(this.renderer,this._el_279,'strong',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_282 = this.renderer.createText(this._el_281,'General',(null as any));
    this._text_283 = this.renderer.createText(this._el_279,'\n      ',(null as any));
    this._el_284 = import3.createRenderElement(this.renderer,this._el_279,'ul',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_285 = this.renderer.createText(this._el_284,'\n        ',(null as any));
    this._el_286 = import3.createRenderElement(this.renderer,this._el_284,'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_287 = this.renderer.createText(this._el_286,'These Terms are subject to occasional revision, and if we make any substantial changes, we may notify you by sending you an e-mail to the last e-mail address you provided to us and/or by prominently posting notice of the changes on our Site.  You are responsible for providing us with your most current e-mail address.  In the event that the last e-mail address that you have provided us is not valid our dispatch of the e-mail containing such notice will nonetheless constitute effective notice of the changes described in the notice.  Any changes to these Terms will be effective upon the earliest of thirty (30) calendar days following our dispatch of an e-mail notice to you or thirty (30) calendar days following our posting of notice of the changes on our Site.  These changes will be effective immediately for new users of our Site.  Continued use of our Site following notice of such changes shall indicate your acknowledgement of such changes and agreement to be bound by the terms and conditions of such changes.',(null as any));
    this._text_288 = this.renderer.createText(this._el_284,'\n        ',(null as any));
    this._el_289 = import3.createRenderElement(this.renderer,this._el_284,'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_290 = this.renderer.createText(this._el_289,'\n          ',(null as any));
    this._el_291 = import3.createRenderElement(this.renderer,this._el_289,'strong',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_292 = this.renderer.createText(this._el_291,'Dispute Resolution. ',(null as any));
    this._text_293 = this.renderer.createText(this._el_289,'\n          ',(null as any));
    this._el_294 = import3.createRenderElement(this.renderer,this._el_289,'strong',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._el_295 = import3.createRenderElement(this.renderer,this._el_294,'em',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_296 = this.renderer.createText(this._el_295,'Please read this Arbitration Agreement carefully. It is part of your contract with Company and affects your rights.  It contains procedures for MANDATORY BINDING ARBITRATION AND A CLASS ACTION WAIVER.',(null as any));
    this._text_297 = this.renderer.createText(this._el_289,'\n          ',(null as any));
    this._el_298 = import3.createRenderElement(this.renderer,this._el_289,'ul',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_299 = this.renderer.createText(this._el_298,'\n            ',(null as any));
    this._el_300 = import3.createRenderElement(this.renderer,this._el_298,'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_301 = this.renderer.createText(this._el_300,'\n              ',(null as any));
    this._el_302 = import3.createRenderElement(this.renderer,this._el_300,'em',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_303 = this.renderer.createText(this._el_302,'Applicability of Arbitration Agreement.',(null as any));
    this._text_304 = this.renderer.createText(this._el_300,' All claims and disputes in connection with the Terms or the use of any product or service provided by the Company that cannot be resolved informally or in small claims court shall be resolved by binding arbitration on an individual basis under the terms of this Arbitration Agreement.  Unless otherwise agreed to, all arbitration proceedings shall be held in English.  This Arbitration Agreement applies to you and the Company, and to any subsidiaries, affiliates, agents, employees, predecessors in interest, successors, and assigns, as well as all authorized or unauthorized users or beneficiaries of services or goods provided under the Terms.\n            ',(null as any));
    this._text_305 = this.renderer.createText(this._el_298,'\n            ',(null as any));
    this._el_306 = import3.createRenderElement(this.renderer,this._el_298,'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_307 = this.renderer.createText(this._el_306,'\n              ',(null as any));
    this._el_308 = import3.createRenderElement(this.renderer,this._el_306,'em',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_309 = this.renderer.createText(this._el_308,'Notice Requirement and Informal Dispute Resolution',(null as any));
    this._text_310 = this.renderer.createText(this._el_306,'. Before either party may seek arbitration, the party must first send to the other party a written Notice of Dispute describing the nature and basis of the claim or dispute, and the requested relief.  A Notice to the Company should be sent to: 5033 W. Laurel St. Suite 100, 33607, Tampa. After the Notice is received, you and the Company may attempt to resolve the claim or dispute informally.  If you and the Company do not resolve the claim or dispute within thirty (30) days after the Notice is received, either party may begin an arbitration proceeding.  The amount of any settlement offer made by any party may not be disclosed to the arbitrator until after the arbitrator has determined the amount of the award to which either party is entitled.\n            ',(null as any));
    this._text_311 = this.renderer.createText(this._el_298,'\n            ',(null as any));
    this._el_312 = import3.createRenderElement(this.renderer,this._el_298,'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_313 = this.renderer.createText(this._el_312,'\n              Arbitration Rules. Arbitration shall be initiated through the American Arbitration Association, an established alternative dispute resolution provider that offers arbitration as set forth in this section.  If AAA is not available to arbitrate, the parties shall agree to select an alternative ADR Provider.  The rules of the ADR Provider shall govern all aspects of the arbitration except to the extent such rules are in conflict with the Terms.  The AAA Consumer Arbitration Rules governing the arbitration are available online at\n              ',(null as any));
    this._el_314 = import3.createRenderElement(this.renderer,this._el_312,'a',new import3.InlineArray4(4,'href','http://www.adr.org','target','_blank'),(null as any));
    this._text_315 = this.renderer.createText(this._el_314,'adr.org',(null as any));
    this._text_316 = this.renderer.createText(this._el_312,' or by calling the AAA at 1-800-778-7879.  The arbitration shall be conducted by a single, neutral arbitrator.  Any claims or disputes where the total amount of the award sought is less than Ten Thousand U.S. Dollars (US $10,000.00) may be resolved through binding non-appearance-based arbitration, at the option of the party seeking relief.  For claims or disputes where the total amount of the award sought is Ten Thousand U.S. Dollars (US $10,000.00) or more, the right to a hearing will be determined by the Arbitration Rules.  Any hearing will be held in a location within 100 miles of your residence, unless you reside outside of the United States, and unless the parties agree otherwise.  If you reside outside of the U.S., the arbitrator shall give the parties reasonable notice of the date, time and place of any oral hearings. Any judgment on the award rendered by the arbitrator may be entered in any court of competent jurisdiction.  If the arbitrator grants you an award that is greater than the last settlement offer that the Company made to you prior to the initiation of arbitration, the Company will pay you the greater of the award or $2,500.00.  Each party shall bear its own costs and disbursements arising out of the arbitration and shall pay an equal share of the fees and costs of the ADR Provider.\n            ',(null as any));
    this._text_317 = this.renderer.createText(this._el_298,'\n            ',(null as any));
    this._el_318 = import3.createRenderElement(this.renderer,this._el_298,'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_319 = this.renderer.createText(this._el_318,'\n              ',(null as any));
    this._el_320 = import3.createRenderElement(this.renderer,this._el_318,'em',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_321 = this.renderer.createText(this._el_320,'Additional Rules for Non-Appearance Based Arbitration',(null as any));
    this._text_322 = this.renderer.createText(this._el_318,'. If non-appearance based arbitration is elected, the arbitration shall be conducted by telephone, online and/or based solely on written submissions; the specific manner shall be chosen by the party initiating the arbitration.  The arbitration shall not involve any personal appearance by the parties or witnesses unless otherwise agreed by the parties.\n            ',(null as any));
    this._text_323 = this.renderer.createText(this._el_298,'\n            ',(null as any));
    this._el_324 = import3.createRenderElement(this.renderer,this._el_298,'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_325 = this.renderer.createText(this._el_324,'\n              ',(null as any));
    this._el_326 = import3.createRenderElement(this.renderer,this._el_324,'em',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_327 = this.renderer.createText(this._el_326,'Time Limits.',(null as any));
    this._text_328 = this.renderer.createText(this._el_324,' If you or the Company pursues arbitration, the arbitration action must be initiated and/or demanded within the statute of limitations and within any deadline imposed under the AAA Rules for the pertinent claim.\n            ',(null as any));
    this._text_329 = this.renderer.createText(this._el_298,'\n            ',(null as any));
    this._el_330 = import3.createRenderElement(this.renderer,this._el_298,'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_331 = this.renderer.createText(this._el_330,'\n              ',(null as any));
    this._el_332 = import3.createRenderElement(this.renderer,this._el_330,'em',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_333 = this.renderer.createText(this._el_332,'Authority of Arbitrator',(null as any));
    this._text_334 = this.renderer.createText(this._el_330,'. If arbitration is initiated, the arbitrator will decide the rights and liabilities of you and the Company, and the dispute will not be consolidated with any other matters or joined with any other cases or parties.  The arbitrator shall have the authority to grant motions dispositive of all or part of any claim.  The arbitrator shall have the authority to award monetary damages, and to grant any non-monetary remedy or relief available to an individual under applicable law, the AAA Rules, and the Terms.  The arbitrator shall issue a written award and statement of decision describing the essential findings and conclusions on which the award is based.  The arbitrator has the same authority to award relief on an individual basis that a judge in a court of law would have.  The award of the arbitrator is final and binding upon you and the Company.\n            ',(null as any));
    this._text_335 = this.renderer.createText(this._el_298,'\n            ',(null as any));
    this._el_336 = import3.createRenderElement(this.renderer,this._el_298,'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_337 = this.renderer.createText(this._el_336,'\n              ',(null as any));
    this._el_338 = import3.createRenderElement(this.renderer,this._el_336,'em',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_339 = this.renderer.createText(this._el_338,'Waiver of Jury Trial.',(null as any));
    this._text_340 = this.renderer.createText(this._el_336,' THE PARTIES HEREBY WAIVE THEIR CONSTITUTIONAL AND STATUTORY RIGHTS TO GO TO COURT AND HAVE A TRIAL IN FRONT OF A JUDGE OR A JURY, instead electing that all claims and disputes shall be resolved by arbitration under this Arbitration Agreement.  Arbitration procedures are typically more limited, more efficient and less expensive than rules applicable in a court and are subject to very limited review by a court.  In the event any litigation should arise between you and the Company in any state or federal court in a suit to vacate or enforce an arbitration award or otherwise, YOU AND THE COMPANY WAIVE ALL RIGHTS TO A JURY TRIAL, instead electing that the dispute be resolved by a judge.\n            ',(null as any));
    this._text_341 = this.renderer.createText(this._el_298,'\n            ',(null as any));
    this._el_342 = import3.createRenderElement(this.renderer,this._el_298,'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_343 = this.renderer.createText(this._el_342,'\n              ',(null as any));
    this._el_344 = import3.createRenderElement(this.renderer,this._el_342,'em',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_345 = this.renderer.createText(this._el_344,'Waiver of Class or Consolidated Actions',(null as any));
    this._text_346 = this.renderer.createText(this._el_342,'. All claims and disputes within the scope of this arbitration agreement must be arbitrated or litigated on an individual basis and not on a class basis, and claims of more than one customer or user cannot be arbitrated or litigated jointly or consolidated with those of any other customer or user.\n            ',(null as any));
    this._text_347 = this.renderer.createText(this._el_298,'\n            ',(null as any));
    this._el_348 = import3.createRenderElement(this.renderer,this._el_298,'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_349 = this.renderer.createText(this._el_348,'\n              ',(null as any));
    this._el_350 = import3.createRenderElement(this.renderer,this._el_348,'em',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_351 = this.renderer.createText(this._el_350,'Confidentiality',(null as any));
    this._text_352 = this.renderer.createText(this._el_348,'. All aspects of the arbitration proceeding shall be strictly confidential.  The parties agree to maintain confidentiality unless otherwise required by law.  This paragraph shall not prevent a party from submitting to a court of law any information necessary to enforce this Agreement, to enforce an arbitration award, or to seek injunctive or equitable relief.\n            ',(null as any));
    this._text_353 = this.renderer.createText(this._el_298,'\n            ',(null as any));
    this._el_354 = import3.createRenderElement(this.renderer,this._el_298,'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_355 = this.renderer.createText(this._el_354,'\n              ',(null as any));
    this._el_356 = import3.createRenderElement(this.renderer,this._el_354,'em',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_357 = this.renderer.createText(this._el_356,'Severability',(null as any));
    this._text_358 = this.renderer.createText(this._el_354,'. If any part or parts of this Arbitration Agreement are found under the law to be invalid or unenforceable by a court of competent jurisdiction, then such specific part or parts shall be of no force and effect and shall be severed and the remainder of the Agreement shall continue in full force and effect.\n            ',(null as any));
    this._text_359 = this.renderer.createText(this._el_298,'\n            ',(null as any));
    this._el_360 = import3.createRenderElement(this.renderer,this._el_298,'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_361 = this.renderer.createText(this._el_360,'\n              ',(null as any));
    this._el_362 = import3.createRenderElement(this.renderer,this._el_360,'em',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_363 = this.renderer.createText(this._el_362,'Right to Waive.',(null as any));
    this._text_364 = this.renderer.createText(this._el_360,' Any or all of the rights and limitations set forth in this Arbitration Agreement may be waived by the party against whom the claim is asserted.  Such waiver shall not waive or affect any other portion of this Arbitration Agreement.\n            ',(null as any));
    this._text_365 = this.renderer.createText(this._el_298,'\n            ',(null as any));
    this._el_366 = import3.createRenderElement(this.renderer,this._el_298,'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_367 = this.renderer.createText(this._el_366,'\n              ',(null as any));
    this._el_368 = import3.createRenderElement(this.renderer,this._el_366,'em',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_369 = this.renderer.createText(this._el_368,'Survival of Agreement',(null as any));
    this._text_370 = this.renderer.createText(this._el_366,'. This Arbitration Agreement will survive the termination of your relationship with Company.\n            ',(null as any));
    this._text_371 = this.renderer.createText(this._el_298,'\n            ',(null as any));
    this._el_372 = import3.createRenderElement(this.renderer,this._el_298,'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_373 = this.renderer.createText(this._el_372,'\n              ',(null as any));
    this._el_374 = import3.createRenderElement(this.renderer,this._el_372,'em',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_375 = this.renderer.createText(this._el_374,'Small Claims Court.',(null as any));
    this._text_376 = this.renderer.createText(this._el_372,' Nonetheless the foregoing, either you or the Company may bring an individual action in small claims court.\n            ',(null as any));
    this._text_377 = this.renderer.createText(this._el_298,'\n            ',(null as any));
    this._el_378 = import3.createRenderElement(this.renderer,this._el_298,'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_379 = this.renderer.createText(this._el_378,'\n              ',(null as any));
    this._el_380 = import3.createRenderElement(this.renderer,this._el_378,'em',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_381 = this.renderer.createText(this._el_380,'Emergency Equitable Relief',(null as any));
    this._text_382 = this.renderer.createText(this._el_378,'. Anyhow the foregoing, either party may seek emergency equitable relief before a state or federal court in order to maintain the status quo pending arbitration.  A request for interim measures shall not be deemed a waiver of any other rights or obligations under this Arbitration Agreement.\n            ',(null as any));
    this._text_383 = this.renderer.createText(this._el_298,'\n            ',(null as any));
    this._el_384 = import3.createRenderElement(this.renderer,this._el_298,'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_385 = this.renderer.createText(this._el_384,'\n              ',(null as any));
    this._el_386 = import3.createRenderElement(this.renderer,this._el_384,'em',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_387 = this.renderer.createText(this._el_386,'Claims Not Subject to Arbitration. ',(null as any));
    this._text_388 = this.renderer.createText(this._el_384,'Notwithstanding the foregoing, claims of defamation, violation of the Computer Fraud and Abuse Act, and infringement or misappropriation of the other party’s patent, copyright, trademark or trade secrets shall not be subject to this Arbitration Agreement.\n            ',(null as any));
    this._text_389 = this.renderer.createText(this._el_298,'\n            ',(null as any));
    this._el_390 = import3.createRenderElement(this.renderer,this._el_298,'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_391 = this.renderer.createText(this._el_390,'In any circumstances where the foregoing Arbitration Agreement permits the parties to litigate in court, the parties hereby agree to submit to the personal jurisdiction of the courts located within Netherlands County, California, for such purposes.',(null as any));
    this._text_392 = this.renderer.createText(this._el_298,'\n          ',(null as any));
    this._text_393 = this.renderer.createText(this._el_289,'\n        ',(null as any));
    this._text_394 = this.renderer.createText(this._el_284,'\n        ',(null as any));
    this._el_395 = import3.createRenderElement(this.renderer,this._el_284,'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_396 = this.renderer.createText(this._el_395,'\n          The\n          ',(null as any));
    this._el_397 = import3.createRenderElement(this.renderer,this._el_395,'a',new import3.InlineArray4(4,'href','https://youtubeembedcode.com/en/','target','_blank'),(null as any));
    this._text_398 = this.renderer.createText(this._el_397,'Site',(null as any));
    this._text_399 = this.renderer.createText(this._el_395,' may be subject to U.S. export control laws and may be subject to export or import regulations in other countries. You agree not to export, re-export, or transfer, directly or indirectly, any U.S. technical data acquired from Company, or any products utilizing such data, in violation of the United States export laws or regulations.\n        ',(null as any));
    this._text_400 = this.renderer.createText(this._el_284,'\n        ',(null as any));
    this._el_401 = import3.createRenderElement(this.renderer,this._el_284,'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_402 = this.renderer.createText(this._el_401,'Company is located at the address in Section 10.8. If you are a California resident, you may report complaints to the Complaint Assistance Unit of the Division of Consumer Product of the California Department of Consumer Affairs by contacting them in writing at 400 R Street, Sacramento, CA 95814, or by telephone at (800) 952-5210.',(null as any));
    this._text_403 = this.renderer.createText(this._el_284,'\n        ',(null as any));
    this._el_404 = import3.createRenderElement(this.renderer,this._el_284,'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_405 = this.renderer.createText(this._el_404,'\n          ',(null as any));
    this._el_406 = import3.createRenderElement(this.renderer,this._el_404,'strong',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_407 = this.renderer.createText(this._el_406,'Electronic Communications.',(null as any));
    this._text_408 = this.renderer.createText(this._el_404,' The communications between you and Company use electronic means, whether you use the Site or send us emails, or whether Company posts notices on the Site or communicates with you via email. For contractual purposes, you (a) consent to receive communications from Company in an electronic form; and (b) agree that all terms and conditions, agreements, notices, disclosures, and other communications that Company provides to you electronically satisfy any legal obligation that such communications would satisfy if it were be in a hard copy writing.\n        ',(null as any));
    this._text_409 = this.renderer.createText(this._el_284,'\n        ',(null as any));
    this._el_410 = import3.createRenderElement(this.renderer,this._el_284,'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_411 = this.renderer.createText(this._el_410,'\n          ',(null as any));
    this._el_412 = import3.createRenderElement(this.renderer,this._el_410,'strong',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_413 = this.renderer.createText(this._el_412,'Entire Terms.',(null as any));
    this._text_414 = this.renderer.createText(this._el_410,' These Terms constitute the entire agreement between you and us regarding the use of the Site. Our failure to exercise or enforce any right or provision of these Terms shall not operate as a waiver of such right or provision. The section titles in these Terms are for convenience only and have no legal or contractual effect. The word “including” means “including without limitation”. If any provision of these Terms is held to be invalid or unenforceable, the other provisions of these Terms will be unimpaired and the invalid or unenforceable provision will be deemed modified so that it is valid and enforceable to the maximum extent permitted by law.  Your relationship to Company is that of an independent contractor, and neither party is an agent or partner of the other.  These Terms, and your rights and obligations herein, may not be assigned, subcontracted, delegated, or otherwise transferred by you without Company’s prior written consent, and any attempted assignment, subcontract, delegation, or transfer in violation of the foregoing will be null and void.  Company may freely assign these Terms.  The terms and conditions set forth in these Terms shall be binding upon assignees.\n        ',(null as any));
    this._text_415 = this.renderer.createText(this._el_284,'\n        ',(null as any));
    this._el_416 = import3.createRenderElement(this.renderer,this._el_284,'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_417 = this.renderer.createText(this._el_416,'\n          ',(null as any));
    this._el_418 = import3.createRenderElement(this.renderer,this._el_416,'strong',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_419 = this.renderer.createText(this._el_418,'Copyright/Trademark Information',(null as any));
    this._text_420 = this.renderer.createText(this._el_416,'. Copyright © 2017. All rights reserved.  All trademarks, logos and service marks displayed on the Site are our property or the property of other third-parties. You are not permitted to use these Marks without our prior written consent or the consent of such third party which may own the Marks.\n        ',(null as any));
    this._text_421 = this.renderer.createText(this._el_284,'\n        ',(null as any));
    this._el_422 = import3.createRenderElement(this.renderer,this._el_284,'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_423 = this.renderer.createText(this._el_422,'\n          ',(null as any));
    this._el_424 = import3.createRenderElement(this.renderer,this._el_422,'strong',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_425 = this.renderer.createText(this._el_424,'Contact Information:',(null as any));
    this._text_426 = this.renderer.createText(this._el_422,'\n          ',(null as any));
    this._el_427 = import3.createRenderElement(this.renderer,this._el_422,'ul',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_428 = this.renderer.createText(this._el_427,'\n            ',(null as any));
    this._el_429 = import3.createRenderElement(this.renderer,this._el_427,'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_430 = this.renderer.createText(this._el_429,'Address: Tampa',(null as any));
    this._text_431 = this.renderer.createText(this._el_427,'\n            ',(null as any));
    this._el_432 = import3.createRenderElement(this.renderer,this._el_427,'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_433 = this.renderer.createText(this._el_432,'Telephone: 813.444.4567',(null as any));
    this._text_434 = this.renderer.createText(this._el_427,'\n            ',(null as any));
    this._el_435 = import3.createRenderElement(this.renderer,this._el_427,'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_436 = this.renderer.createText(this._el_435,'Email: info@illbuyanyhouse.com',(null as any));
    this._text_437 = this.renderer.createText(this._el_427,'\n          ',(null as any));
    this._text_438 = this.renderer.createText(this._el_422,'\n        ',(null as any));
    this._text_439 = this.renderer.createText(this._el_284,'\n      ',(null as any));
    this._text_440 = this.renderer.createText(this._el_279,'\n    ',(null as any));
    this._text_441 = this.renderer.createText(this._el_277,'\n  ',(null as any));
    this._text_442 = this.renderer.createText(this._el_2,'\n  ',(null as any));
    this._text_443 = this.renderer.createText(this._el_2,'\n',(null as any));
    this.init((null as any),((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._text_8,
      this._text_9,
      this._el_10,
      this._text_11,
      this._el_12,
      this._text_13,
      this._text_14,
      this._text_15,
      this._el_16,
      this._text_17,
      this._text_18,
      this._el_19,
      this._text_20,
      this._el_21,
      this._text_22,
      this._text_23,
      this._text_24,
      this._el_25,
      this._text_26,
      this._text_27,
      this._el_28,
      this._text_29,
      this._el_30,
      this._text_31,
      this._text_32,
      this._text_33,
      this._el_34,
      this._text_35,
      this._text_36,
      this._el_37,
      this._text_38,
      this._el_39,
      this._text_40,
      this._text_41,
      this._text_42,
      this._el_43,
      this._text_44,
      this._text_45,
      this._el_46,
      this._text_47,
      this._el_48,
      this._text_49,
      this._text_50,
      this._text_51,
      this._el_52,
      this._text_53,
      this._text_54,
      this._el_55,
      this._text_56,
      this._text_57,
      this._el_58,
      this._text_59,
      this._text_60,
      this._el_61,
      this._text_62,
      this._el_63,
      this._text_64,
      this._el_65,
      this._text_66,
      this._text_67,
      this._el_68,
      this._text_69,
      this._el_70,
      this._text_71,
      this._el_72,
      this._text_73,
      this._el_74,
      this._text_75,
      this._text_76,
      this._text_77,
      this._text_78,
      this._el_79,
      this._text_80,
      this._el_81,
      this._text_82,
      this._text_83,
      this._text_84,
      this._text_85,
      this._text_86,
      this._el_87,
      this._text_88,
      this._el_89,
      this._text_90,
      this._text_91,
      this._el_92,
      this._text_93,
      this._el_94,
      this._text_95,
      this._text_96,
      this._el_97,
      this._text_98,
      this._el_99,
      this._text_100,
      this._text_101,
      this._text_102,
      this._el_103,
      this._text_104,
      this._text_105,
      this._el_106,
      this._text_107,
      this._el_108,
      this._text_109,
      this._text_110,
      this._text_111,
      this._el_112,
      this._text_113,
      this._text_114,
      this._text_115,
      this._text_116,
      this._el_117,
      this._text_118,
      this._el_119,
      this._text_120,
      this._text_121,
      this._el_122,
      this._text_123,
      this._el_124,
      this._text_125,
      this._el_126,
      this._text_127,
      this._el_128,
      this._text_129,
      this._el_130,
      this._text_131,
      this._el_132,
      this._text_133,
      this._el_134,
      this._text_135,
      this._text_136,
      this._el_137,
      this._text_138,
      this._text_139,
      this._text_140,
      this._el_141,
      this._text_142,
      this._text_143,
      this._text_144,
      this._text_145,
      this._text_146,
      this._text_147,
      this._el_148,
      this._text_149,
      this._el_150,
      this._text_151,
      this._text_152,
      this._el_153,
      this._text_154,
      this._text_155,
      this._el_156,
      this._text_157,
      this._el_158,
      this._text_159,
      this._text_160,
      this._el_161,
      this._text_162,
      this._text_163,
      this._text_164,
      this._text_165,
      this._el_166,
      this._text_167,
      this._text_168,
      this._el_169,
      this._text_170,
      this._text_171,
      this._text_172,
      this._text_173,
      this._el_174,
      this._text_175,
      this._text_176,
      this._el_177,
      this._text_178,
      this._el_179,
      this._text_180,
      this._text_181,
      this._el_182,
      this._text_183,
      this._el_184,
      this._text_185,
      this._el_186,
      this._text_187,
      this._text_188,
      this._text_189,
      this._el_190,
      this._text_191,
      this._el_192,
      this._text_193,
      this._text_194,
      this._text_195,
      this._el_196,
      this._text_197,
      this._text_198,
      this._text_199,
      this._text_200,
      this._el_201,
      this._text_202,
      this._el_203,
      this._text_204,
      this._text_205,
      this._text_206,
      this._text_207,
      this._el_208,
      this._text_209,
      this._text_210,
      this._el_211,
      this._text_212,
      this._text_213,
      this._el_214,
      this._text_215,
      this._el_216,
      this._text_217,
      this._el_218,
      this._text_219,
      this._text_220,
      this._text_221,
      this._text_222,
      this._el_223,
      this._text_224,
      this._text_225,
      this._el_226,
      this._text_227,
      this._text_228,
      this._el_229,
      this._text_230,
      this._text_231,
      this._el_232,
      this._text_233,
      this._el_234,
      this._text_235,
      this._el_236,
      this._text_237,
      this._text_238,
      this._text_239,
      this._el_240,
      this._text_241,
      this._el_242,
      this._text_243,
      this._text_244,
      this._text_245,
      this._text_246,
      this._el_247,
      this._text_248,
      this._text_249,
      this._el_250,
      this._text_251,
      this._el_252,
      this._text_253,
      this._text_254,
      this._el_255,
      this._text_256,
      this._text_257,
      this._el_258,
      this._text_259,
      this._text_260,
      this._el_261,
      this._text_262,
      this._text_263,
      this._el_264,
      this._text_265,
      this._text_266,
      this._el_267,
      this._text_268,
      this._text_269,
      this._el_270,
      this._text_271,
      this._text_272,
      this._text_273,
      this._el_274,
      this._text_275,
      this._text_276,
      this._el_277,
      this._text_278,
      this._el_279,
      this._text_280,
      this._el_281,
      this._text_282,
      this._text_283,
      this._el_284,
      this._text_285,
      this._el_286,
      this._text_287,
      this._text_288,
      this._el_289,
      this._text_290,
      this._el_291,
      this._text_292,
      this._text_293,
      this._el_294,
      this._el_295,
      this._text_296,
      this._text_297,
      this._el_298,
      this._text_299,
      this._el_300,
      this._text_301,
      this._el_302,
      this._text_303,
      this._text_304,
      this._text_305,
      this._el_306,
      this._text_307,
      this._el_308,
      this._text_309,
      this._text_310,
      this._text_311,
      this._el_312,
      this._text_313,
      this._el_314,
      this._text_315,
      this._text_316,
      this._text_317,
      this._el_318,
      this._text_319,
      this._el_320,
      this._text_321,
      this._text_322,
      this._text_323,
      this._el_324,
      this._text_325,
      this._el_326,
      this._text_327,
      this._text_328,
      this._text_329,
      this._el_330,
      this._text_331,
      this._el_332,
      this._text_333,
      this._text_334,
      this._text_335,
      this._el_336,
      this._text_337,
      this._el_338,
      this._text_339,
      this._text_340,
      this._text_341,
      this._el_342,
      this._text_343,
      this._el_344,
      this._text_345,
      this._text_346,
      this._text_347,
      this._el_348,
      this._text_349,
      this._el_350,
      this._text_351,
      this._text_352,
      this._text_353,
      this._el_354,
      this._text_355,
      this._el_356,
      this._text_357,
      this._text_358,
      this._text_359,
      this._el_360,
      this._text_361,
      this._el_362,
      this._text_363,
      this._text_364,
      this._text_365,
      this._el_366,
      this._text_367,
      this._el_368,
      this._text_369,
      this._text_370,
      this._text_371,
      this._el_372,
      this._text_373,
      this._el_374,
      this._text_375,
      this._text_376,
      this._text_377,
      this._el_378,
      this._text_379,
      this._el_380,
      this._text_381,
      this._text_382,
      this._text_383,
      this._el_384,
      this._text_385,
      this._el_386,
      this._text_387,
      this._text_388,
      this._text_389,
      this._el_390,
      this._text_391,
      this._text_392,
      this._text_393,
      this._text_394,
      this._el_395,
      this._text_396,
      this._el_397,
      this._text_398,
      this._text_399,
      this._text_400,
      this._el_401,
      this._text_402,
      this._text_403,
      this._el_404,
      this._text_405,
      this._el_406,
      this._text_407,
      this._text_408,
      this._text_409,
      this._el_410,
      this._text_411,
      this._el_412,
      this._text_413,
      this._text_414,
      this._text_415,
      this._el_416,
      this._text_417,
      this._el_418,
      this._text_419,
      this._text_420,
      this._text_421,
      this._el_422,
      this._text_423,
      this._el_424,
      this._text_425,
      this._text_426,
      this._el_427,
      this._text_428,
      this._el_429,
      this._text_430,
      this._text_431,
      this._el_432,
      this._text_433,
      this._text_434,
      this._el_435,
      this._text_436,
      this._text_437,
      this._text_438,
      this._text_439,
      this._text_440,
      this._text_441,
      this._text_442,
      this._text_443
    ]
    ),(null as any));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import9.PageTitleComponent) && (0 === requestNodeIndex))) { return this._PageTitleComponent_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_0_0_0:any = this.context.title;
    this._PageTitleComponent_0_3.check_title(currVal_0_0_0,throwOnChange,false);
    this._PageTitleComponent_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this.compView_0.internalDetectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
  }
}