import { PropertyAttributes, Property } from './property';

export const PROPERTIES: Property[] = [

    {
        propertyguid: '',
        name: 'Single Family Home',
        location: 'Crisp Park',
        address: '334 36th Ave',
        city: 'Saint Petersburg',
        state: 'FL',
        zip: '33704',
        description: 'This beautifully renovated home sits steps away from the water and popular Crisp Park, which has access to a public boat ramp. An open floor plan invites you into this stylish home. Beautiful new bamboo floors throughout, brand new kitchen featuring stainless steel appliances, real wood cabinets, granite countertops with decorative glass and metal backsplash. You will notice ceramic tile along with custom inlays, decorative tile, brand new vanities with granite countertops and new commodes in both bathrooms. Freshly painted inside and out, new interior doors, new lighting throughout, new 30-year dimensional shingle roof, new water heater, all windows have been upgraded to the new low-E standard with storm shutters, new HVAC air handler and condenser and even a new garage door with opener. Large creened back porch off of garage with alley access. All work was permitted and done by licensed contractors. Remodeled home in a prime location. 10 minutes to downtown St. Pete.',
        masterimage: 'IMG_2.jpg',
        images: ['IMG_1.jpg', 'IMG_3.jpg', 'IMG_4.jpg', 'IMG_5.jpg', 'IMG_6.jpg'],
        propertyattributes: [
            { key: 'rooms', value: '3' },
            { key: 'baths', value: '2' },
            { key: 'sq ft', value: '1101' },
        ],
    },
    {
        propertyguid: '',
        name: 'Multi Family Home',
        location: 'River Oaks',
        address: '8514 Briar Grove Cir',
        city: 'Tampa',
        state: 'FL',
        zip: '33615',
        description: '',
        masterimage: 'IMG_2458.jpg',
        images: ['IMG_2461.jpg', 'IMG_2462.jpg', 'IMG_2463.jpg', 'IMG_2464.jpg', 'IMG_2467.jpg'],
        propertyattributes: [
            { key: 'rooms', value: '3' },
            { key: 'baths', value: '1' },
            { key: 'sq ft', value: '1056' },
        ],
    },
    {
        propertyguid: '',
        name: 'Single Family Home',
        location: 'Clearwater',
        address: '1800 Magnolia Dr.',
        city: 'Clearwater',
        state: 'FL',
        zip: '33764',
        description: 'Just minutes from shopping, restaurants, and Clearwater Beach, this exquisite home feels like you stepped into true Florida living. Natural light soars through this house making it bright & airy. Fabulous layout with all the right spaces-entertain in either the living room or the Florida room; cook for 2 or 20 in the well-appointed kitchen; or take the gathering outdoors to your secluded backyard. Relax & unwind in the master suite whether it is reading a book or taking a shower in spa inspired master bath. Impressive upgrades make this the perfect family home. Plenty of room to store your RV/boat/recreational vehicle in the fenced-in backyard.',
        masterimage: 'IMG_0.jpg',
        images: ['IMG_01.jpg', 'IMG_02.jpg', 'IMG_03.jpg'],
        propertyattributes: [
                { key: 'rooms', value: '3' },
                { key: 'baths', value: '3' },
                { key: 'sq ft', value: '1658' },
            ],
    },
    {
        propertyguid: '',
        name: 'Single Family Home',
        location: 'Northwest Tampa',
        address: '2907 W Dewey St',
        city: 'Tampa',
        state: 'FL',
        zip: '33607',
        description: 'This sleek & modern remodeled home is located in a well-established neighborhood and is conveniently located just minutes away from Downtown Tampa, South Tampa, International Plaza and Westshore Malls, Raymond James Stadium, Tampa International Airport, I-275, and St. Josephs Hospital.Stepping inside the front door your are graced by soaring ceilings and ornate crown molding.Beautiful new laminate floors throughout, brand new kitchen featuring Stainless Steel appliances, real wood cabinets, Granite countertops with decorative glass & metal backsplash. The master suite has its own private bath plus a huge walk-in closet, All three bathrooms boast new ceramic tile along with custom inlays, decorative tile, brand new vanities with Granite countertops and new commodes. Freshly painted inside and out, new interior doors, new lighting & ceiling fans throughout. Outdoor entertaining is a breeze on the covered patio (there is also an uncovered patio).', 
        masterimage: 'IMG_9.jpg',
        images: ['IMG_8.jpg', 'IMG_10.jpg', 'IMG_11.jpg'],
        propertyattributes: [
                { key: 'rooms', value: '3' },
                { key: 'baths', value: '3' },
                { key: 'sq ft', value: '1380' },
            ],
    },
    {
        propertyguid: '',
        name: 'Single Family Home',
        location: 'Beach Park',
        address: '116 S Lauber Way',
        city: 'Tampa',
        state: 'FL',
        zip: '33609',
        description: 'Single family home built in 1959.',
        masterimage: 'IMG_45.jpg',
        images: ['IMG_46.jpg', 'IMG_47.jpg', 'IMG_48.jpg'],
        propertyattributes: [
                { key: 'rooms', value: '4' },
                { key: 'baths', value: '2' },
                { key: 'sq ft', value: '1877' },
            ],
    },

    {
        propertyguid: '',
        name: 'Single Family Home',
        location: 'Madeira Beach',
        address: '14052 Vivian Dr.',
        city: 'Madiera Beach',
        state: 'FL',
        zip: '33708',
        description: 'Remarkable value, unbeatable location to build your dream home in Madeira Beach. Just 2 blocks to the Gulf of Mexicos pristine beaches, restaurants, Johns Pass Village and a beautiful new multi-million dollar project coming soon that will put our Island on the map.', 
        masterimage: 'IMG_0474.jpg',
        images: ['IMG_0473.jpg'],
        propertyattributes: [
            { key: 'rooms', value: '2' },
            { key: 'baths', value: '1' },
            { key: 'sq ft', value: '780' },
        ],
    },
]