import { PropertyAttributes, PropertyImgAttributes, Property } from './property';

export const PROPERTIES: Property[] = [
    {
        propertyid: '3',
        name: 'Condo',
        location: 'Thames St',
        address: '1759 Thames St',
        city: 'Clearwater',
        state: 'FL',
        zip: '33755',
        zillow: 'https://www.zillow.com/homedetails/1759-Thames-St-Clearwater-FL-33755/46954253_zpid/',
        description: 'Do you have a large family? Pets? Home office? 4 Bedrooms w/ Den, 2 Bathrooms, screened in Porch w/ Hot Tub; Fenced in yard, room for all!! Nice neighborhood, public records show 1531 sq ft.',
        masterimage: 'THAMESstreetview.jpg',
        images: [
            { img: 'assets/userassets/images/properties/THAMESstreetview.jpg', title: '', caption: '', slide: 0 }
        ],
        propertyattributes: [
            { key: 'Structure Type ', value: 'Block' },
            //{ key: 'Last Remodel', value: '2017' },
            { key: 'Bedrooms', value: '4' },
            { key: 'Sq Ft', value: '1,531' },
            { key: 'Total Rooms', value: '6' },
            { key: 'Lot Size', value: '7,000 Sq Ft' },
            //{ key: 'Sale Price', value: 'open' },
        ],
    }, {
        propertyid: '4',
        name: 'Single Family Home',
        location: 'Ter N',
        address: '5585 85th Ter N',
        city: 'Pinellas Park',
        state: 'FL',
        zip: '33781',
        zillow: 'https://www.zillow.com/homedetails/5585-85th-Ter-N-Pinellas-Park-FL-33781/47204943_zpid/',
        description: 'Tucked away in a winding low traffic Pinellas Park neighborhood you will find this 1500+ sq ft 4 bedroom 2 bath block home. Large tiled kitchen with extra full wall of counters & cabinets opens to the living area. Dual windowed & tiled dining area with 2 pantry/storage closets. Split bedrooms for privacy. Large fenced backyard. This home is priced to move!',
        masterimage: 'TERstreetview.jpg',
        images: [
            { img: 'assets/userassets/images/properties/TERstreetview.jpg', title: '', caption: '', slide: 0 },
            { img: 'assets/userassets/images/properties/85thter.jpg', title: '', caption: '', slide: 1 }
        ],
        propertyattributes: [
            { key: 'Structure Type ', value: 'Block' },
            //{ key: 'Last Remodel', value: '2017' },
            { key: 'Bedrooms', value: '4' },
            { key: 'Sq Ft', value: '1,505' },
            { key: 'Total Rooms', value: '6' },
            { key: 'Lot Size', value: '6,500 Sq Ft' },
           // { key: 'Sale Price', value: 'open' },
        ],
    }, {
        propertyid: '5',
        name: 'Single Family Home',
        location: 'Aragon Way S',
        address: '5131 Aragon Way S',
        city: 'Saint Petersburg',
        state: 'FL',
        zip: '33705',
        zillow: 'https://www.zillow.com/homedetails/5131-Aragon-Way-S-Saint-Petersburg-FL-33705/46953211_zpid/',
        description: '5131 Aragon Way S, Saint Petersburg, FL is a single family home that contains 1,593 sq ft and was built in 1953. It contains 2 bedrooms and 1 bathroom.',
        masterimage: 'Aragonstreetview.jpg',
        images: [
            { img: 'assets/userassets/images/properties/Aragonstreetview.jpg', title: '', caption: '', slide: 0 }
        ],
        propertyattributes: [
            { key: 'Structure Type ', value: 'Concrete' },
            //{ key: 'Last Remodel', value: '2017' },
            { key: 'Bedrooms', value: '2' },
            { key: 'Sq Ft', value: '1,593' },
            { key: 'Total Rooms', value: '5' },
            { key: 'Lot Size', value: '21,344 Sq Ft' },
            //{ key: 'Sale Price', value: 'open' },
        ],
    },
    {
        propertyid: '6',
        name: 'Single Family Home',
        location: 'River View and Hillsborough River',
        address: '4038 N River View Ave',
        city: 'Tampa',
        state: 'FL',
        zip: '33607',
        zillow: 'https://www.zillow.com/homedetails/4038-N-River-View-Ave-Tampa-FL-33607/45044423_zpid/',
        description: 'Home located in the sought after River View section of Tampa, blocks from the Hillsborough River/Close to city it is being totally rehabed from floor to roof evertyhing brand new.',
        masterimage: 'IMG_0864.JPG',
        images: [
            { img: 'assets/userassets/images/properties/4038RV.jpg', title: '', caption: '', slide: 0 },
            { img: 'assets/userassets/images/properties/4038RV2.jpg', title: '', caption: '', slide: 1 },
            { img: 'assets/userassets/images/properties/4038RV3.jpg', title: '', caption: '', slide: 1 },
            { img: 'assets/userassets/images/properties/4038RV4.jpg', title: '', caption: '', slide: 1 },
            { img: 'assets/userassets/images/properties/4038RV5.jpg', title: '', caption: '', slide: 1 },
            { img: 'assets/userassets/images/properties/4038RV6.jpg', title: '', caption: '', slide: 1 },
            { img: 'assets/userassets/images/properties/4038RV7.jpg', title: '', caption: '', slide: 1 },
            { img: 'assets/userassets/images/properties/4038RV8.jpg', title: '', caption: '', slide: 1 }
        ],
        propertyattributes: [
            { key: 'Structure Type ', value: 'Contemporary' },
            { key: 'Last Remodel', value: '2017' },
            { key: 'Bedrooms', value: '5' },
            { key: 'Sq Ft', value: '3010' },
            { key: 'Total Rooms', value: '14' },
            { key: 'Lot Size', value: '9,750 Sq Ft' },
            { key: 'Sale Price', value: 'open' },
        ],
    },
    {
        propertyid: '7',
        name: 'Single Family Home',
        location: 'Brandon',
        address: '1001 Calumet Way',
        city: 'Brandon',
        state: 'FL',
        zip: '33511',
        zillow: 'https://www.zillow.com/homes/1001-Calumet-Way,-Brandon,-FL-33511-_rb/',
        description: 'This home has been SOLD',
        masterimage: 'IMG_1030.jpg',
        images: [
            { img: 'assets/userassets/images/properties/IMG_1030.jpg', title: '', caption: '', slide: 0 },
        ],
        propertyattributes: [
            { key: 'Construction', value: 'Block, Stucco' },
            { key: 'Villa', value: ' End Unit, 1 Story' },
            { key: 'Bedrooms', value: '2' },
            { key: 'Bathrooms', value: '2' },
            { key: 'Sq Ft', value: '1078' },
            { key: 'Pets', value: 'size 16-35lbs' },
        ],
    },
    {
        propertyid: '8',
        name: 'Single Family Home',
        location: 'Tampa',
        address: '7103 W Creek Dr',
        city: 'Tampa',
        state: 'FL',
        zip: '34615',
        zillow: 'https://www.zillow.com/homes/for_sale/fsba,fsbo,new_lt/44868838_zpid/globalrelevanceex_sort/28.016678,-82.589057,28.014225,-82.592721_rect/17_zm/0_mmm/?view=public',
        description: 'This home has been SOLD',
        masterimage: 'IMG_F1.JPG',
        images: [
            { img: 'assets/userassets/images/properties/wcreek.JPG', title: '', caption: '', slide: 0 }
        ],
        propertyattributes: [
            { key: 'Structure Type ', value: 'Concrete Block' },
            { key: 'Last Remodel', value: '' },
            { key: 'Bedrooms', value: '3' },
            { key: 'Bathrooms', value: '1' },
            { key: 'Sq Ft', value: '1,247' },
            { key: 'Total Rooms', value: '8' },
            { key: 'Lot Size', value: '11,088 Sq Ft' },
            { key: 'Sale Price', value: 'inquire.' },
        ],
    },
    {
        propertyid: '9',
        name: 'Single Family Home',
        location: 'Northwest Tampa',
        address: '2907 W Dewey St',
        city: 'Tampa',
        state: 'FL',
        zip: '33607',
        zillow: 'https://www.zillow.com/homes/2907-W-Dewey-St,-Tampa,-FL-33607_rb/',
        description: 'This home has been SOLD',
        masterimage: 'IMG_9.jpg',
        images: [
            { img: 'assets/userassets/images/properties/IMG_9.jpg', title: '', caption: '', slide: 0 },
            { img: 'assets/userassets/images/properties/IMG_8.jpg', title: '', caption: '', slide: 1 },
            { img: 'assets//userassets/images/properties/IMG_10.jpg', title: '', caption: '', slide: 2 },
            { img: 'assets/userassets/images/properties/IMG_11.jpg', title: '', caption: '', slide: 3 }
        ],
        propertyattributes: [
            { key: 'rooms', value: '3' },
            { key: 'baths', value: '3' },
            { key: 'sq ft', value: '1380' },
        ],
    },
    {
        propertyid: '10',
        name: 'Single Family Home',
        location: 'Beach Park',
        address: '116 S Lauber Way',
        city: 'Tampa',
        state: 'FL',
        zip: '33609',
        zillow: 'https://www.zillow.com/homes/116-S-Lauber-Way,-Tampa,-FL-33609-_rb/',
        description: 'This home has been SOLD',
        masterimage: 'IMG_45.jpg',
        images: [
            { img: 'assets/userassets/images/properties/IMG_45.jpg', title: '', caption: '', slide: 0 },
            { img: 'assets/userassets/images/properties/IMG_46.jpg', title: '', caption: '', slide: 1 },
            { img: 'assets/userassets/images/properties/IMG_47.jpg', title: '', caption: '', slide: 2 },
            { img: 'assets/userassets/images/properties/IMG_48.jpg', title: '', caption: '', slide: 3 }
        ],
        propertyattributes: [
            { key: 'rooms', value: '4' },
            { key: 'baths', value: '2' },
            { key: 'sq ft', value: '1877' },
        ],
    },
    {
        propertyid: '11',
        name: 'Single Family Home',
        location: 'Madeira Beach',
        address: '14052 Vivian Dr.',
        city: 'Madiera Beach',
        state: 'FL',
        zip: '33708',
        zillow: 'https://www.zillow.com/homes/14052-Vivian-Dr.,-Madiera-Beach,-FL-33708-_rb/',
        description: 'This home has been SOLD',
        masterimage: 'IMG_0474.jpg',
        images: [
            { img: 'assets/userassets/images/properties/IMG_0474.jpg', title: '', caption: '', slide: 0 },
            { img:'assets/userassets/images/properties/IMG_0473.jpg',title:'', caption:'', slide:1 }
                ],
        propertyattributes: [
            { key: 'rooms', value: '2' },
            { key: 'baths', value: '1' },
            { key: 'sq ft', value: '780' },
        ],
    },
    {
        propertyid: '12',
        name: 'Single Family Home',
        location: 'Crisp Park',
        address: '334 36th Ave',
        city: 'Saint Petersburg',
        state: 'FL',
        zip: '33704',
        zillow: 'https://www.zillow.com/homes/for_sale/334-36th-Ave,-Saint-Petersburg,-FL-33704-_rb/?fromHomePage=true&shouldFireSellPageImplicitClaimGA=false&fromHomePageTab=buy',
        description: 'This home has been SOLD',
        masterimage: 'IMG_2.jpg',
        images: [
            { img: 'assets/userassets/images/properties/IMG_1.jpg', title: '', caption: '', slide: 0 },
            {img:'assets/userassets/images/properties/IMG_3.jpg',title:'', caption:'', slide:1},
            {img:'assets/userassets/images/properties/IMG_4.jpg',title:'', caption:'', slide:2},
            {img:'assets/userassets/images/properties/IMG_5.jpg',title:'', caption:'', slide:3},
            { img: 'assets/userassets/images/properties/IMG_6.jpg', title: '', caption: '', slide: 4 }
        ],
        propertyattributes: [
            { key: 'rooms', value: '3' },
            { key: 'baths', value: '2' },
            { key: 'sq ft', value: '1101' },
        ],
    },
    {
        propertyid: '13',
        name: 'Multi Family Home',
        location: 'River Oaks',
        address: '8514 Briar Grove Cir',
        city: 'Tampa',
        state: 'FL',
        zip: '33615',
        zillow: 'https://www.zillow.com/homes/for_sale/8514-Briar-Grove-Cir,-Tampa,-FL-33615-_rb/?fromHomePage=true&shouldFireSellPageImplicitClaimGA=false&fromHomePageTab=buy',
        description: 'This home has been SOLD',
        masterimage: 'IMG_2458.jpg',
        images: [
            { img: 'assets/userassets/images/properties/IMG_2458.jpg', title: '', caption: '', slide: 0 },
            {img:'assets/userassets/images/properties/IMG_2462.jpg', title:'', caption:'', slide:1},
            {img:'assets/userassets/images/properties/IMG_2463.jpg', title:'', caption:'', slide:2},
            {img:'assets/userassets/images/properties/IMG_2464.jpg', title:'', caption:'', slide:3},
            { img:'assets/userassets/images/properties/IMG_2467.jpg', title:'', caption:'', slide:4}
        ],
        propertyattributes: [
            { key: 'rooms', value: '3' },
            { key: 'baths', value: '1' },
            { key: 'sq ft', value: '1056' },
        ],
    },
    {
        propertyid: '14',
        name: 'Single Family Home',
        location: 'Clearwater',
        address: '1800 Magnolia Dr.',
        city: 'Clearwater',
        state: 'FL',
        zip: '33764',
        zillow: 'https://www.zillow.com/homes/1800-Magnolia-Dr.,-Clearwater,-FL-33764-_rb/',
        description: 'This home has been SOLD',
        masterimage: 'IMG_0.jpg',
        images: [
            { img: 'assets/userassets/images/properties/IMG_0.jpg', title: '', caption: '', slide: 0 },
            {img:'assets/userassets/images/properties/IMG_01.jpg', title:'', caption:'', slide:1},
            {img:'assets/userassets/images/properties/IMG_02.jpg', title:'', caption:'', slide:2},
            { img:'assets/userassets/images/properties/IMG_03.jpg', title:'', caption:'', slide:3}
        ],
        propertyattributes: [
            { key: 'rooms', value: '3' },
            { key: 'baths', value: '3' },
            { key: 'sq ft', value: '1658' },
        ],
    },
]

export const FEATUREDPROPERTIES: Property[] = [
    {
        propertyid: '15',
        name: 'Condo',
        location: 'Thames St',
        address: '1759 Thames St',
        city: 'Clearwater',
        state: 'FL',
        zip: '33755',
        zillow: 'https://www.zillow.com/homedetails/1759-Thames-St-Clearwater-FL-33755/46954253_zpid/',
        description: 'Do you have a large family? Pets? Home office? 4 Bedrooms w/ Den, 2 Bathrooms, screened in Porch w/ Hot Tub; Fenced in yard, room for all!! Nice neighborhood, public records show 1531 sq ft.',
        masterimage: 'THAMESstreetview.jpg',
        images: [
            { img: 'assets/userassets/images/properties/THAMESstreetview.jpg', title: '', caption: '', slide: 0 }
        ],
        propertyattributes: [
            { key: 'Structure Type ', value: 'Block' },
            //{ key: 'Last Remodel', value: '2017' },
            { key: 'Bedrooms', value: '4' },
            { key: 'Sq Ft', value: '1,531' },
            { key: 'Total Rooms', value: '6' },
            { key: 'Lot Size', value: '7,000 Sq Ft' },
            //{ key: 'Sale Price', value: 'open' },
        ],
    },
    {
        propertyid: '16',
        name: 'Single Family Home',
        location: 'Ter N',
        address: '5585 85th Ter N',
        city: 'Pinellas Park',
        state: 'FL',
        zip: '33781',
        zillow: 'https://www.zillow.com/homedetails/5585-85th-Ter-N-Pinellas-Park-FL-33781/47204943_zpid/',
        description: 'Tucked away in a winding low traffic Pinellas Park neighborhood you will find this 1500+ sq ft 4 bedroom 2 bath block home. Large tiled kitchen with extra full wall of counters & cabinets opens to the living area. Dual windowed & tiled dining area with 2 pantry/storage closets. Split bedrooms for privacy. Large fenced backyard. This home is priced to move!',
        masterimage: 'TERstreetview.jpg',
        images: [
            { img: 'assets/userassets/images/properties/TERstreetview.jpg', title: '', caption: '', slide: 0 },
            { img: 'assets/userassets/images/properties/85thter.jpg', title: '', caption: '', slide: 1 }
        ],
        propertyattributes: [
            { key: 'Structure Type ', value: 'Block' },
            //{ key: 'Last Remodel', value: '2017' },
            { key: 'Bedrooms', value: '4' },
            { key: 'Sq Ft', value: '1,505' },
            { key: 'Total Rooms', value: '6' },
            { key: 'Lot Size', value: '6,500 Sq Ft' },
            //{ key: 'Sale Price', value: 'open' },
        ],
    },
    {
        propertyid: '17',
        name: 'Single Family Home',
        location: 'Aragon Way S',
        address: '5131 Aragon Way S',
        city: 'Saint Petersburg',
        state: 'FL',
        zip: '33705',
        zillow: 'https://www.zillow.com/homedetails/5131-Aragon-Way-S-Saint-Petersburg-FL-33705/46953211_zpid/',
        description: '5131 Aragon Way S, Saint Petersburg, FL is a single family home that contains 1,593 sq ft and was built in 1953. It contains 2 bedrooms and 1 bathroom.',
        masterimage: 'Aragonstreetview.jpg',
        images: [
            { img: 'assets/userassets/images/properties/Aragonstreetview.jpg', title: '', caption: '', slide: 0 }
        ],
        propertyattributes: [
            { key: 'Structure Type ', value: 'Concrete' },
            //{ key: 'Last Remodel', value: '2017' },
            { key: 'Bedrooms', value: '2' },
            { key: 'Sq Ft', value: '1,593' },
            { key: 'Total Rooms', value: '5' },
            { key: 'Lot Size', value: '21,344 Sq Ft' },
            //{ key: 'Sale Price', value: 'open' },
        ],
    },
         
]



////////////////////////////////////////////////
//export const PROPERTIES: Property[] = [

//    {
//        propertyguid: '',
//        name: 'Single Family Home',
//        location: 'Crisp Park',
//        address: '334 36th Ave',
//        city: 'Saint Petersburg',
//        state: 'FL',
//        zip: '33704',
//        description: 'This beautifully renovated home sits steps away from the water and popular Crisp Park, which has access to a public boat ramp. An open floor plan invites you into this stylish home. Beautiful new bamboo floors throughout, brand new kitchen featuring stainless steel appliances, real wood cabinets, granite countertops with decorative glass and metal backsplash. You will notice ceramic tile along with custom inlays, decorative tile, brand new vanities with granite countertops and new commodes in both bathrooms. Freshly painted inside and out, new interior doors, new lighting throughout, new 30-year dimensional shingle roof, new water heater, all windows have been upgraded to the new low-E standard with storm shutters, new HVAC air handler and condenser and even a new garage door with opener. Large creened back porch off of garage with alley access. All work was permitted and done by licensed contractors. Remodeled home in a prime location. 10 minutes to downtown St. Pete.',
//        masterimage: 'IMG_2.jpg',
//        images: ['IMG_1.jpg', 'IMG_3.jpg', 'IMG_4.jpg', 'IMG_5.jpg', 'IMG_6.jpg'],
//        propertyattributes: [
//            { key: 'rooms', value: '3' },
//            { key: 'baths', value: '2' },
//            { key: 'sq ft', value: '1101' },
//        ],
//    },
//    {
//        propertyguid: '',
//        name: 'Multi Family Home',
//        location: 'River Oaks',
//        address: '8514 Briar Grove Cir',
//        city: 'Tampa',
//        state: 'FL',
//        zip: '33615',
//        description: '',
//        masterimage: 'IMG_2458.jpg',
//        images: ['IMG_2461.jpg', 'IMG_2462.jpg', 'IMG_2463.jpg', 'IMG_2464.jpg', 'IMG_2467.jpg'],
//        propertyattributes: [
//            { key: 'rooms', value: '3' },
//            { key: 'baths', value: '1' },
//            { key: 'sq ft', value: '1056' },
//        ],
//    },
//    {
//        propertyguid: '',
//        name: 'Single Family Home',
//        location: 'Clearwater',
//        address: '1800 Magnolia Dr.',
//        city: 'Clearwater',
//        state: 'FL',
//        zip: '33764',
//        description: 'Just minutes from shopping, restaurants, and Clearwater Beach, this exquisite home feels like you stepped into true Florida living. Natural light soars through this house making it bright & airy. Fabulous layout with all the right spaces-entertain in either the living room or the Florida room; cook for 2 or 20 in the well-appointed kitchen; or take the gathering outdoors to your secluded backyard. Relax & unwind in the master suite whether it is reading a book or taking a shower in spa inspired master bath. Impressive upgrades make this the perfect family home. Plenty of room to store your RV/boat/recreational vehicle in the fenced-in backyard.',
//        masterimage: 'IMG_0.jpg',
//        images: ['IMG_01.jpg', 'IMG_02.jpg', 'IMG_03.jpg'],
//        propertyattributes: [
//                { key: 'rooms', value: '3' },
//                { key: 'baths', value: '3' },
//                { key: 'sq ft', value: '1658' },
//            ],
//    },
//    {
//        propertyguid: '',
//        name: 'Single Family Home',
//        location: 'Northwest Tampa',
//        address: '2907 W Dewey St',
//        city: 'Tampa',
//        state: 'FL',
//        zip: '33607',
//        description: 'This sleek & modern remodeled home is located in a well-established neighborhood and is conveniently located just minutes away from Downtown Tampa, South Tampa, International Plaza and Westshore Malls, Raymond James Stadium, Tampa International Airport, I-275, and St. Josephs Hospital.Stepping inside the front door your are graced by soaring ceilings and ornate crown molding.Beautiful new laminate floors throughout, brand new kitchen featuring Stainless Steel appliances, real wood cabinets, Granite countertops with decorative glass & metal backsplash. The master suite has its own private bath plus a huge walk-in closet, All three bathrooms boast new ceramic tile along with custom inlays, decorative tile, brand new vanities with Granite countertops and new commodes. Freshly painted inside and out, new interior doors, new lighting & ceiling fans throughout. Outdoor entertaining is a breeze on the covered patio (there is also an uncovered patio).', 
//        masterimage: 'IMG_9.jpg',
//        images: ['IMG_8.jpg', 'IMG_10.jpg', 'IMG_11.jpg'],
//        propertyattributes: [
//                { key: 'rooms', value: '3' },
//                { key: 'baths', value: '3' },
//                { key: 'sq ft', value: '1380' },
//            ],
//    },
//    {
//        propertyguid: '',
//        name: 'Single Family Home',
//        location: 'Beach Park',
//        address: '116 S Lauber Way',
//        city: 'Tampa',
//        state: 'FL',
//        zip: '33609',
//        description: 'Single family home built in 1959.',
//        masterimage: 'IMG_45.jpg',
//        images: ['IMG_46.jpg', 'IMG_47.jpg', 'IMG_48.jpg'],
//        propertyattributes: [
//                { key: 'rooms', value: '4' },
//                { key: 'baths', value: '2' },
//                { key: 'sq ft', value: '1877' },
//            ],
//    },

//    {
//        propertyguid: '',
//        name: 'Single Family Home',
//        location: 'Madeira Beach',
//        address: '14052 Vivian Dr.',
//        city: 'Madiera Beach',
//        state: 'FL',
//        zip: '33708',
//        description: 'Remarkable value, unbeatable location to build your dream home in Madeira Beach. Just 2 blocks to the Gulf of Mexicos pristine beaches, restaurants, Johns Pass Village and a beautiful new multi-million dollar project coming soon that will put our Island on the map.', 
//        masterimage: 'IMG_0474.jpg',
//        images: ['IMG_0473.jpg'],
//        propertyattributes: [
//            { key: 'rooms', value: '2' },
//            { key: 'baths', value: '1' },
//            { key: 'sq ft', value: '780' },
//        ],
//    },
//]
