/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '../../app/footer.component';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/view_utils';
import * as import4 from '@angular/core/src/metadata/view';
import * as import5 from '@angular/core/src/linker/view_type';
import * as import6 from '@angular/core/src/change_detection/constants';
import * as import7 from '@angular/core/src/linker/component_factory';
import * as import8 from './footer.component.css.shim.ngstyle';
import * as import9 from '../node_modules/@angular/router/src/directives/router_link.ngfactory';
import * as import10 from '../node_modules/@angular/router/src/directives/router_link_active.ngfactory';
import * as import11 from '@angular/core/src/linker/query_list';
import * as import12 from '@angular/router/src/router';
import * as import13 from '@angular/router/src/router_state';
import * as import14 from '@angular/common/src/location/location_strategy';
import * as import15 from '@angular/core/src/linker/element_ref';
import * as import16 from '@angular/router/src/directives/router_link';
import * as import17 from '@angular/router/src/directives/router_link_active';
export class Wrapper_FooterComponent {
  /*private*/ _eventHandler:Function;
  context:import0.FooterComponent;
  /*private*/ _changed:boolean;
  constructor() {
    this._changed = false;
    this.context = new import0.FooterComponent();
  }
  ngOnDetach(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any):void {
  }
  ngOnDestroy():void {
  }
  ngDoCheck(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this._changed;
    this._changed = false;
    if (!throwOnChange) { if ((view.numberOfChecks === 0)) { this.context.ngOnInit(); } }
    return changed;
  }
  checkHost(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any,throwOnChange:boolean):void {
  }
  handleEvent(eventName:string,$event:any):boolean {
    var result:boolean = true;
    return result;
  }
  subscribe(view:import1.AppView<any>,_eventHandler:any):void {
    this._eventHandler = _eventHandler;
  }
}
var renderType_FooterComponent_Host:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.None,([] as any[]),{});
class View_FooterComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  compView_0:import1.AppView<import0.FooterComponent>;
  _FooterComponent_0_3:Wrapper_FooterComponent;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_FooterComponent_Host0,renderType_FooterComponent_Host,import5.ViewType.HOST,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.selectOrCreateRenderHostElement(this.renderer,'footer',import3.EMPTY_INLINE_ARRAY,rootSelector,(null as any));
    this.compView_0 = new View_FooterComponent0(this.viewUtils,this,0,this._el_0);
    this._FooterComponent_0_3 = new Wrapper_FooterComponent();
    this.compView_0.create(this._FooterComponent_0_3.context);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return new import7.ComponentRef_<any>(0,this,this._el_0,this._FooterComponent_0_3.context);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.FooterComponent) && (0 === requestNodeIndex))) { return this._FooterComponent_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._FooterComponent_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this.compView_0.internalDetectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
export const FooterComponentNgFactory:import7.ComponentFactory<import0.FooterComponent> = new import7.ComponentFactory<import0.FooterComponent>('footer',View_FooterComponent_Host0,import0.FooterComponent);
const styles_FooterComponent:any[] = [import8.styles];
var renderType_FooterComponent:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.Emulated,styles_FooterComponent,{});
export class View_FooterComponent0 extends import1.AppView<import0.FooterComponent> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _el_6:any;
  _text_7:any;
  _text_8:any;
  _el_9:any;
  _text_10:any;
  _el_11:any;
  _RouterLinkWithHref_11_3:import9.Wrapper_RouterLinkWithHref;
  _RouterLinkActive_11_4:import10.Wrapper_RouterLinkActive;
  _query_RouterLink_11_0:import11.QueryList<any>;
  _query_RouterLinkWithHref_11_1:import11.QueryList<any>;
  _text_12:any;
  _text_13:any;
  _el_14:any;
  _RouterLinkWithHref_14_3:import9.Wrapper_RouterLinkWithHref;
  _RouterLinkActive_14_4:import10.Wrapper_RouterLinkActive;
  _query_RouterLink_14_0:import11.QueryList<any>;
  _query_RouterLinkWithHref_14_1:import11.QueryList<any>;
  _text_15:any;
  _text_16:any;
  _text_17:any;
  _text_18:any;
  _text_19:any;
  _text_20:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_FooterComponent0,renderType_FooterComponent,import5.ViewType.COMPONENT,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    const parentRenderNode:any = this.renderer.createViewRoot(this.parentElement);
    this._el_0 = import3.createRenderElement(this.renderer,parentRenderNode,'div',new import3.InlineArray2(2,'class','container-fluid footer'),(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n  ',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,this._el_0,'div',new import3.InlineArray2(2,'class','container xs-col-12 footer'),(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'\n    ',(null as any));
    this._el_4 = import3.createRenderElement(this.renderer,this._el_2,'div',new import3.InlineArray2(2,'class','row'),(null as any));
    this._text_5 = this.renderer.createText(this._el_4,'\n      ',(null as any));
    this._el_6 = import3.createRenderElement(this.renderer,this._el_4,'div',new import3.InlineArray2(2,'class','col-xs-12 col-sm-9'),(null as any));
    this._text_7 = this.renderer.createText(this._el_6,'©2017 - I Buy As Is, Inc.',(null as any));
    this._text_8 = this.renderer.createText(this._el_4,'\n      ',(null as any));
    this._el_9 = import3.createRenderElement(this.renderer,this._el_4,'div',new import3.InlineArray2(2,'class','col-xs-12 col-sm-3'),(null as any));
    this._text_10 = this.renderer.createText(this._el_9,'\n        ',(null as any));
    this._el_11 = import3.createRenderElement(this.renderer,this._el_9,'a',new import3.InlineArray8(6,'class','center','routerLink','/terms','routerLinkActive','active'),(null as any));
    this._RouterLinkWithHref_11_3 = new import9.Wrapper_RouterLinkWithHref(this.parentView.injectorGet(import12.Router,this.parentIndex),this.parentView.injectorGet(import13.ActivatedRoute,this.parentIndex),this.parentView.injectorGet(import14.LocationStrategy,this.parentIndex));
    this._RouterLinkActive_11_4 = new import10.Wrapper_RouterLinkActive(this.parentView.injectorGet(import12.Router,this.parentIndex),new import15.ElementRef(this._el_11),this.renderer,this.ref);
    this._query_RouterLink_11_0 = new import11.QueryList<any>();
    this._query_RouterLinkWithHref_11_1 = new import11.QueryList<any>();
    this._text_12 = this.renderer.createText(this._el_11,'terms',(null as any));
    this._text_13 = this.renderer.createText(this._el_9,' |\n        ',(null as any));
    this._el_14 = import3.createRenderElement(this.renderer,this._el_9,'a',new import3.InlineArray8(6,'class','center','routerLink','/privacy','routerLinkActive','active'),(null as any));
    this._RouterLinkWithHref_14_3 = new import9.Wrapper_RouterLinkWithHref(this.parentView.injectorGet(import12.Router,this.parentIndex),this.parentView.injectorGet(import13.ActivatedRoute,this.parentIndex),this.parentView.injectorGet(import14.LocationStrategy,this.parentIndex));
    this._RouterLinkActive_14_4 = new import10.Wrapper_RouterLinkActive(this.parentView.injectorGet(import12.Router,this.parentIndex),new import15.ElementRef(this._el_14),this.renderer,this.ref);
    this._query_RouterLink_14_0 = new import11.QueryList<any>();
    this._query_RouterLinkWithHref_14_1 = new import11.QueryList<any>();
    this._text_15 = this.renderer.createText(this._el_14,'privacy',(null as any));
    this._text_16 = this.renderer.createText(this._el_9,'\n      ',(null as any));
    this._text_17 = this.renderer.createText(this._el_4,'\n    ',(null as any));
    this._text_18 = this.renderer.createText(this._el_2,'\n  ',(null as any));
    this._text_19 = this.renderer.createText(this._el_0,'\n',(null as any));
    this._text_20 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_11,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_11));
    var disposable_1:Function = import3.subscribeToRenderElement(this,this._el_14,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_14));
    this.init((null as any),((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._el_11,
      this._text_12,
      this._text_13,
      this._el_14,
      this._text_15,
      this._text_16,
      this._text_17,
      this._text_18,
      this._text_19,
      this._text_20
    ]
    ),[
      disposable_0,
      disposable_1
    ]
    );
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import16.RouterLinkWithHref) && ((11 <= requestNodeIndex) && (requestNodeIndex <= 12)))) { return this._RouterLinkWithHref_11_3.context; }
    if (((token === import17.RouterLinkActive) && ((11 <= requestNodeIndex) && (requestNodeIndex <= 12)))) { return this._RouterLinkActive_11_4.context; }
    if (((token === import16.RouterLinkWithHref) && ((14 <= requestNodeIndex) && (requestNodeIndex <= 15)))) { return this._RouterLinkWithHref_14_3.context; }
    if (((token === import17.RouterLinkActive) && ((14 <= requestNodeIndex) && (requestNodeIndex <= 15)))) { return this._RouterLinkActive_14_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_11_0_0:any = '/terms';
    this._RouterLinkWithHref_11_3.check_routerLink(currVal_11_0_0,throwOnChange,false);
    this._RouterLinkWithHref_11_3.ngDoCheck(this,this._el_11,throwOnChange);
    const currVal_11_1_0:any = 'active';
    this._RouterLinkActive_11_4.check_routerLinkActive(currVal_11_1_0,throwOnChange,false);
    this._RouterLinkActive_11_4.ngDoCheck(this,this._el_11,throwOnChange);
    const currVal_14_0_0:any = '/privacy';
    this._RouterLinkWithHref_14_3.check_routerLink(currVal_14_0_0,throwOnChange,false);
    this._RouterLinkWithHref_14_3.ngDoCheck(this,this._el_14,throwOnChange);
    const currVal_14_1_0:any = 'active';
    this._RouterLinkActive_14_4.check_routerLinkActive(currVal_14_1_0,throwOnChange,false);
    this._RouterLinkActive_14_4.ngDoCheck(this,this._el_14,throwOnChange);
    if (!throwOnChange) {
      if (this._query_RouterLink_11_0.dirty) {
        this._query_RouterLink_11_0.reset(([] as any[]));
        this._RouterLinkActive_11_4.context.links = this._query_RouterLink_11_0;
        this._query_RouterLink_11_0.notifyOnChanges();
      }
      if (this._query_RouterLinkWithHref_11_1.dirty) {
        this._query_RouterLinkWithHref_11_1.reset([this._RouterLinkWithHref_11_3.context]);
        this._RouterLinkActive_11_4.context.linksWithHrefs = this._query_RouterLinkWithHref_11_1;
        this._query_RouterLinkWithHref_11_1.notifyOnChanges();
      }
      if (this._query_RouterLink_14_0.dirty) {
        this._query_RouterLink_14_0.reset(([] as any[]));
        this._RouterLinkActive_14_4.context.links = this._query_RouterLink_14_0;
        this._query_RouterLink_14_0.notifyOnChanges();
      }
      if (this._query_RouterLinkWithHref_14_1.dirty) {
        this._query_RouterLinkWithHref_14_1.reset([this._RouterLinkWithHref_14_3.context]);
        this._RouterLinkActive_14_4.context.linksWithHrefs = this._query_RouterLinkWithHref_14_1;
        this._query_RouterLinkWithHref_14_1.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._RouterLinkActive_11_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._RouterLinkActive_14_4.context.ngAfterContentInit(); }
    }
    this._RouterLinkWithHref_11_3.checkHost(this,this,this._el_11,throwOnChange);
    this._RouterLinkWithHref_14_3.checkHost(this,this,this._el_14,throwOnChange);
  }
  destroyInternal():void {
    this._RouterLinkWithHref_11_3.ngOnDestroy();
    this._RouterLinkActive_11_4.ngOnDestroy();
    this._RouterLinkWithHref_14_3.ngOnDestroy();
    this._RouterLinkActive_14_4.ngOnDestroy();
  }
  handleEvent_11(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._RouterLinkWithHref_11_3.handleEvent(eventName,$event) && result);
    return result;
  }
  handleEvent_14(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._RouterLinkWithHref_14_3.handleEvent(eventName,$event) && result);
    return result;
  }
}