/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

export const styles:any[] = ['body[_ngcontent-%COMP%] {\r\n}\r\n\r\n.logo[_ngcontent-%COMP%]{\r\n  position:relative;\r\n  top:0px;\r\n}\r\n\r\n.header[_ngcontent-%COMP%] {\r\n  \r\n  background-color: #000;\r\n  color: white;\r\n}\r\n\r\n.banner[_ngcontent-%COMP%] \r\n{\r\n    background-color: #FFF;\r\n    color:blue;\r\n\r\n}\r\n\r\n.topmenu[_ngcontent-%COMP%]{\r\n  height:100%;\r\n}\r\n\r\nnav[_ngcontent-%COMP%]{\r\n  padding-top:10px;\r\n}\r\n\r\n.banner[_ngcontent-%COMP%]   div[_ngcontent-%COMP%]{\r\n  display:table;\r\n}\r\n\r\n.banner[_ngcontent-%COMP%]   a[_ngcontent-%COMP%]:link, .banner[_ngcontent-%COMP%]   a[_ngcontent-%COMP%]:visited{\r\n  color:blue;\r\n}\r\n\r\n\r\n.topnav[_ngcontent-%COMP%]\r\n{\r\n\r\n}\r\n\r\n.topnav[_ngcontent-%COMP%]   a[_ngcontent-%COMP%], .topnav[_ngcontent-%COMP%]   a[_ngcontent-%COMP%]:link, .topnav[_ngcontent-%COMP%]   a[_ngcontent-%COMP%]:visited\r\n{\r\n  color:white;\r\n}\r\n\r\n.topnav[_ngcontent-%COMP%]   a[_ngcontent-%COMP%]:hover{\r\n  color:white;\r\n  font-weight:bold;\r\n}\r\n\r\n.phone[_ngcontent-%COMP%] {\r\n  font-size:larger;\r\n}'];