/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '../../app/home.component';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/view_utils';
import * as import4 from '@angular/core/src/metadata/view';
import * as import5 from '@angular/core/src/linker/view_type';
import * as import6 from '@angular/core/src/change_detection/constants';
import * as import7 from '@angular/core/src/linker/component_factory';
import * as import8 from '../../app/pagetitle.component';
import * as import9 from './pagetitle.component.ngfactory';
export class Wrapper_HomeComponent {
  /*private*/ _eventHandler:Function;
  context:import0.HomeComponent;
  /*private*/ _changed:boolean;
  constructor() {
    this._changed = false;
    this.context = new import0.HomeComponent();
  }
  ngOnDetach(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any):void {
  }
  ngOnDestroy():void {
  }
  ngDoCheck(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this._changed;
    this._changed = false;
    if (!throwOnChange) { if ((view.numberOfChecks === 0)) { this.context.ngOnInit(); } }
    return changed;
  }
  checkHost(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any,throwOnChange:boolean):void {
  }
  handleEvent(eventName:string,$event:any):boolean {
    var result:boolean = true;
    return result;
  }
  subscribe(view:import1.AppView<any>,_eventHandler:any):void {
    this._eventHandler = _eventHandler;
  }
}
var renderType_HomeComponent_Host:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.None,([] as any[]),{});
class View_HomeComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  compView_0:import1.AppView<import0.HomeComponent>;
  _HomeComponent_0_3:Wrapper_HomeComponent;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_HomeComponent_Host0,renderType_HomeComponent_Host,import5.ViewType.HOST,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.selectOrCreateRenderHostElement(this.renderer,'home',import3.EMPTY_INLINE_ARRAY,rootSelector,(null as any));
    this.compView_0 = new View_HomeComponent0(this.viewUtils,this,0,this._el_0);
    this._HomeComponent_0_3 = new Wrapper_HomeComponent();
    this.compView_0.create(this._HomeComponent_0_3.context);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return new import7.ComponentRef_<any>(0,this,this._el_0,this._HomeComponent_0_3.context);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.HomeComponent) && (0 === requestNodeIndex))) { return this._HomeComponent_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._HomeComponent_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this.compView_0.internalDetectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
export const HomeComponentNgFactory:import7.ComponentFactory<import0.HomeComponent> = new import7.ComponentFactory<import0.HomeComponent>('home',View_HomeComponent_Host0,import0.HomeComponent);
const styles_HomeComponent:any[] = ([] as any[]);
var renderType_HomeComponent:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.None,styles_HomeComponent,{});
export class View_HomeComponent0 extends import1.AppView<import0.HomeComponent> {
  _el_0:any;
  compView_0:import1.AppView<import8.PageTitleComponent>;
  _PageTitleComponent_0_3:import9.Wrapper_PageTitleComponent;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _text_6:any;
  _el_7:any;
  _text_8:any;
  _text_9:any;
  _el_10:any;
  _text_11:any;
  _text_12:any;
  _el_13:any;
  _text_14:any;
  _text_15:any;
  _el_16:any;
  _text_17:any;
  _text_18:any;
  _el_19:any;
  _text_20:any;
  _text_21:any;
  _el_22:any;
  _text_23:any;
  _text_24:any;
  _el_25:any;
  _text_26:any;
  _el_27:any;
  _text_28:any;
  _text_29:any;
  _el_30:any;
  _text_31:any;
  _text_32:any;
  _el_33:any;
  _text_34:any;
  _text_35:any;
  _el_36:any;
  _text_37:any;
  _text_38:any;
  _el_39:any;
  _text_40:any;
  _text_41:any;
  _el_42:any;
  _text_43:any;
  _text_44:any;
  _el_45:any;
  _text_46:any;
  _text_47:any;
  _el_48:any;
  _text_49:any;
  _text_50:any;
  _el_51:any;
  _text_52:any;
  _text_53:any;
  _text_54:any;
  _el_55:any;
  _text_56:any;
  _text_57:any;
  _el_58:any;
  _text_59:any;
  _text_60:any;
  _el_61:any;
  _text_62:any;
  _text_63:any;
  _el_64:any;
  _text_65:any;
  _text_66:any;
  _el_67:any;
  _text_68:any;
  _text_69:any;
  _el_70:any;
  _text_71:any;
  _text_72:any;
  _el_73:any;
  _text_74:any;
  _text_75:any;
  _el_76:any;
  _text_77:any;
  _text_78:any;
  _el_79:any;
  _text_80:any;
  _el_81:any;
  _text_82:any;
  _text_83:any;
  _el_84:any;
  _text_85:any;
  _text_86:any;
  _el_87:any;
  _text_88:any;
  _text_89:any;
  _el_90:any;
  _text_91:any;
  _text_92:any;
  _el_93:any;
  _text_94:any;
  _text_95:any;
  _el_96:any;
  _text_97:any;
  _text_98:any;
  _el_99:any;
  _text_100:any;
  _text_101:any;
  _el_102:any;
  _text_103:any;
  _text_104:any;
  _text_105:any;
  _text_106:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_HomeComponent0,renderType_HomeComponent,import5.ViewType.COMPONENT,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    const parentRenderNode:any = this.renderer.createViewRoot(this.parentElement);
    this._el_0 = import3.createRenderElement(this.renderer,parentRenderNode,'pagetitle',import3.EMPTY_INLINE_ARRAY,(null as any));
    this.compView_0 = new import9.View_PageTitleComponent0(this.viewUtils,this,0,this._el_0);
    this._PageTitleComponent_0_3 = new import9.Wrapper_PageTitleComponent();
    this.compView_0.create(this._PageTitleComponent_0_3.context);
    this._text_1 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,parentRenderNode,'div',new import3.InlineArray2(2,'class','container'),(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'\n  ',(null as any));
    this._el_4 = import3.createRenderElement(this.renderer,this._el_2,'h2',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_5 = this.renderer.createText(this._el_4,'We are...',(null as any));
    this._text_6 = this.renderer.createText(this._el_2,'\n\n  ',(null as any));
    this._el_7 = import3.createRenderElement(this.renderer,this._el_2,'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_8 = this.renderer.createText(this._el_7,'I Buy As Is, Inc. is the areas’ premier real estate solutions company, and since our inception we have been helping homeowners along with improving communities in each city we work in.',(null as any));
    this._text_9 = this.renderer.createText(this._el_2,'\n  ',(null as any));
    this._el_10 = import3.createRenderElement(this.renderer,this._el_2,'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_11 = this.renderer.createText(this._el_10,'Through our extensive knowledge of the business, network of resources, and years of expertise, we can assist homeowners with a wide variety of real estate problems. We pride ourselves on our reputation for working one-on-one with each customer to handle their individual situations.',(null as any));
    this._text_12 = this.renderer.createText(this._el_2,'\n  ',(null as any));
    this._el_13 = import3.createRenderElement(this.renderer,this._el_2,'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_14 = this.renderer.createText(this._el_13,'With the ability to directly purchase homes and make cash offers, we can create an extremely fast, and hassle-free transaction.',(null as any));
    this._text_15 = this.renderer.createText(this._el_2,'\n  ',(null as any));
    this._el_16 = import3.createRenderElement(this.renderer,this._el_2,'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_17 = this.renderer.createText(this._el_16,'In addition, we re-develop many single family and multi-family properties throughout the state with the intention of revitalizing communities and encouraging home ownership.',(null as any));
    this._text_18 = this.renderer.createText(this._el_2,'\n  ',(null as any));
    this._el_19 = import3.createRenderElement(this.renderer,this._el_2,'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_20 = this.renderer.createText(this._el_19,'Our mission is to rejuvenate neighborhoods and increase the standard of living by improving the overall quality of housing for the residents. Call us today and let’s see how we can work together!',(null as any));
    this._text_21 = this.renderer.createText(this._el_2,'\n  ',(null as any));
    this._el_22 = import3.createRenderElement(this.renderer,this._el_2,'h3',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_23 = this.renderer.createText(this._el_22,'Real Estate Specialties',(null as any));
    this._text_24 = this.renderer.createText(this._el_2,'\n  ',(null as any));
    this._el_25 = import3.createRenderElement(this.renderer,this._el_2,'ul',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_26 = this.renderer.createText(this._el_25,'\n    ',(null as any));
    this._el_27 = import3.createRenderElement(this.renderer,this._el_25,'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_28 = this.renderer.createText(this._el_27,'Foreclosure Avoidance Debt Removal or Renegotiation',(null as any));
    this._text_29 = this.renderer.createText(this._el_25,'\n    ',(null as any));
    this._el_30 = import3.createRenderElement(this.renderer,this._el_25,'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_31 = this.renderer.createText(this._el_30,'Bank Owned Property & REO’s',(null as any));
    this._text_32 = this.renderer.createText(this._el_25,'\n    ',(null as any));
    this._el_33 = import3.createRenderElement(this.renderer,this._el_25,'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_34 = this.renderer.createText(this._el_33,'Sell Your Property Without Realtor Commissions',(null as any));
    this._text_35 = this.renderer.createText(this._el_25,'\n    ',(null as any));
    this._el_36 = import3.createRenderElement(this.renderer,this._el_25,'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_37 = this.renderer.createText(this._el_36,'Solving Title Issues',(null as any));
    this._text_38 = this.renderer.createText(this._el_25,'\n    ',(null as any));
    this._el_39 = import3.createRenderElement(this.renderer,this._el_25,'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_40 = this.renderer.createText(this._el_39,'Vacant Properties & Houses in Major Disrepair',(null as any));
    this._text_41 = this.renderer.createText(this._el_25,'\n    ',(null as any));
    this._el_42 = import3.createRenderElement(this.renderer,this._el_25,'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_43 = this.renderer.createText(this._el_42,'Environmental or Structural Problems',(null as any));
    this._text_44 = this.renderer.createText(this._el_25,'\n    ',(null as any));
    this._el_45 = import3.createRenderElement(this.renderer,this._el_25,'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_46 = this.renderer.createText(this._el_45,'Apartment & House Rental Specialists',(null as any));
    this._text_47 = this.renderer.createText(this._el_25,'\n    ',(null as any));
    this._el_48 = import3.createRenderElement(this.renderer,this._el_25,'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_49 = this.renderer.createText(this._el_48,'Bankruptcy Over-Leveraged Properties',(null as any));
    this._text_50 = this.renderer.createText(this._el_25,'\n    ',(null as any));
    this._el_51 = import3.createRenderElement(this.renderer,this._el_25,'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_52 = this.renderer.createText(this._el_51,'Clearing up Judgments or Outside Liens',(null as any));
    this._text_53 = this.renderer.createText(this._el_25,'\n  ',(null as any));
    this._text_54 = this.renderer.createText(this._el_2,'\n  ',(null as any));
    this._el_55 = import3.createRenderElement(this.renderer,this._el_2,'h3',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_56 = this.renderer.createText(this._el_55,'And many others… ',(null as any));
    this._text_57 = this.renderer.createText(this._el_2,'\n  ',(null as any));
    this._el_58 = import3.createRenderElement(this.renderer,this._el_2,'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_59 = this.renderer.createText(this._el_58,'We not only purchase property but we also sell homes, many of which are completely renovated and in move-in condition. Whether you are dreaming of becoming a first-time home buyer or looking to upgrade your current home, we can help.',(null as any));
    this._text_60 = this.renderer.createText(this._el_2,'\n  ',(null as any));
    this._el_61 = import3.createRenderElement(this.renderer,this._el_2,'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_62 = this.renderer.createText(this._el_61,'I Buy As Is, Inc. is truly committed to helping each individual customer. We focus on fast response, integrity and over-delivering on customer service. By putting the customer’s needs first, whether selling or buying a home, we can help you realize your real estate goals.',(null as any));
    this._text_63 = this.renderer.createText(this._el_2,'\n  ',(null as any));
    this._el_64 = import3.createRenderElement(this.renderer,this._el_2,'h3',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_65 = this.renderer.createText(this._el_64,'Giving Back',(null as any));
    this._text_66 = this.renderer.createText(this._el_2,'\n  ',(null as any));
    this._el_67 = import3.createRenderElement(this.renderer,this._el_2,'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_68 = this.renderer.createText(this._el_67,'I Buy As Is, Inc. Gives network of companies dedicated to giving back to our community. We are passionate about philanthropy and we have had the honor of working with amazing organizations like Habitat for Humanity and the Red Cross.',(null as any));
    this._text_69 = this.renderer.createText(this._el_2,'\n\n\n  ',(null as any));
    this._el_70 = import3.createRenderElement(this.renderer,this._el_2,'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_71 = this.renderer.createText(this._el_70,'I Buy As Is, Inc. is the Tampa Bay area’s prime real estate investment company. With over 45 years of combined expertise we are able to help homeowners overcome a multitude of financial situations. We recognize that each situation is different, we take great pride in catering to each individual homeowners needs. We are capable of buying homes and making cash offers with a fast and efficient process. We also rehabilitate numerous properties throughout our area in order to assist in the redevelopment of our local communities with a proven track record.',(null as any));
    this._text_72 = this.renderer.createText(this._el_2,'\n\n  ',(null as any));
    this._el_73 = import3.createRenderElement(this.renderer,this._el_2,'h2',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_74 = this.renderer.createText(this._el_73,'Our team works for you and yours.',(null as any));
    this._text_75 = this.renderer.createText(this._el_2,'\n\n  ',(null as any));
    this._el_76 = import3.createRenderElement(this.renderer,this._el_2,'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_77 = this.renderer.createText(this._el_76,'We specialize in :',(null as any));
    this._text_78 = this.renderer.createText(this._el_2,'\n  ',(null as any));
    this._el_79 = import3.createRenderElement(this.renderer,this._el_2,'ul',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_80 = this.renderer.createText(this._el_79,'\n    ',(null as any));
    this._el_81 = import3.createRenderElement(this.renderer,this._el_79,'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_82 = this.renderer.createText(this._el_81,'Avoiding Foreclosure',(null as any));
    this._text_83 = this.renderer.createText(this._el_79,'\n    ',(null as any));
    this._el_84 = import3.createRenderElement(this.renderer,this._el_79,'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_85 = this.renderer.createText(this._el_84,'Defaulted Mortgage Payments',(null as any));
    this._text_86 = this.renderer.createText(this._el_79,'\n    ',(null as any));
    this._el_87 = import3.createRenderElement(this.renderer,this._el_79,'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_88 = this.renderer.createText(this._el_87,'Divorce, Land Disputes',(null as any));
    this._text_89 = this.renderer.createText(this._el_79,'\n    ',(null as any));
    this._el_90 = import3.createRenderElement(this.renderer,this._el_79,'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_91 = this.renderer.createText(this._el_90,'Owed Tax Debts, Liens',(null as any));
    this._text_92 = this.renderer.createText(this._el_79,'\n    ',(null as any));
    this._el_93 = import3.createRenderElement(this.renderer,this._el_79,'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_94 = this.renderer.createText(this._el_93,'Costly Home Repairs',(null as any));
    this._text_95 = this.renderer.createText(this._el_79,'\n    ',(null as any));
    this._el_96 = import3.createRenderElement(this.renderer,this._el_79,'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_97 = this.renderer.createText(this._el_96,'Tax Delinquencies',(null as any));
    this._text_98 = this.renderer.createText(this._el_79,'\n    ',(null as any));
    this._el_99 = import3.createRenderElement(this.renderer,this._el_79,'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_100 = this.renderer.createText(this._el_99,'Probate or Estate Sale',(null as any));
    this._text_101 = this.renderer.createText(this._el_79,'\n    ',(null as any));
    this._el_102 = import3.createRenderElement(this.renderer,this._el_79,'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_103 = this.renderer.createText(this._el_102,'Non Owner Occupied',(null as any));
    this._text_104 = this.renderer.createText(this._el_79,'\n  ',(null as any));
    this._text_105 = this.renderer.createText(this._el_2,'\n',(null as any));
    this._text_106 = this.renderer.createText(parentRenderNode,'\n\n\n\n\n\n',(null as any));
    this.init((null as any),((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._text_6,
      this._el_7,
      this._text_8,
      this._text_9,
      this._el_10,
      this._text_11,
      this._text_12,
      this._el_13,
      this._text_14,
      this._text_15,
      this._el_16,
      this._text_17,
      this._text_18,
      this._el_19,
      this._text_20,
      this._text_21,
      this._el_22,
      this._text_23,
      this._text_24,
      this._el_25,
      this._text_26,
      this._el_27,
      this._text_28,
      this._text_29,
      this._el_30,
      this._text_31,
      this._text_32,
      this._el_33,
      this._text_34,
      this._text_35,
      this._el_36,
      this._text_37,
      this._text_38,
      this._el_39,
      this._text_40,
      this._text_41,
      this._el_42,
      this._text_43,
      this._text_44,
      this._el_45,
      this._text_46,
      this._text_47,
      this._el_48,
      this._text_49,
      this._text_50,
      this._el_51,
      this._text_52,
      this._text_53,
      this._text_54,
      this._el_55,
      this._text_56,
      this._text_57,
      this._el_58,
      this._text_59,
      this._text_60,
      this._el_61,
      this._text_62,
      this._text_63,
      this._el_64,
      this._text_65,
      this._text_66,
      this._el_67,
      this._text_68,
      this._text_69,
      this._el_70,
      this._text_71,
      this._text_72,
      this._el_73,
      this._text_74,
      this._text_75,
      this._el_76,
      this._text_77,
      this._text_78,
      this._el_79,
      this._text_80,
      this._el_81,
      this._text_82,
      this._text_83,
      this._el_84,
      this._text_85,
      this._text_86,
      this._el_87,
      this._text_88,
      this._text_89,
      this._el_90,
      this._text_91,
      this._text_92,
      this._el_93,
      this._text_94,
      this._text_95,
      this._el_96,
      this._text_97,
      this._text_98,
      this._el_99,
      this._text_100,
      this._text_101,
      this._el_102,
      this._text_103,
      this._text_104,
      this._text_105,
      this._text_106
    ]
    ),(null as any));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import8.PageTitleComponent) && (0 === requestNodeIndex))) { return this._PageTitleComponent_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_0_0_0:any = this.context.title;
    this._PageTitleComponent_0_3.check_title(currVal_0_0_0,throwOnChange,false);
    this._PageTitleComponent_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this.compView_0.internalDetectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
  }
}