/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

export const styles:any[] = ['label[_ngcontent-%COMP%]{\r\n    display:block;\r\n    clear:both;\r\n}\r\n}'];